### ISSUE TITLE
terra-date-picker does allows selected-value  to be cleared programmatically. whereas terra-date-time-picker  does not.

### ISSUE THREAD

**Issue by supreethmr** [cerner/terra-framework#1000]
# Bug Report

1. Unable to clear selected date and time in terra-date-time-picker. 
2. Time value in terra-date-time-picker is not updating when date and time is set programmatically.

## Description
1. One of our Terra Consumer team have implementation to clear selected date from terra-date-picker on button click and they were not able to achieve the same with terra-date-time-picker. 
date-picker provides ability for consumer to clear `selected-date` by using `value` prop. whereas date-time-picker does not allows to clear the selected date as shown in below images.

2. Only date value gets updated when we set date and time programmatically in date-time-picker.  

## Steps to Reproduce
---issue 1
* Set any date value like '2019-02-09T09:10:00' as default value for date-time-picker
* Add Button to clear the date-time-picker on click
```javascript
const DateTimePickerExample = () => {
  const [dateTime, setDate] = useState('2019-02-09T09:10:00');

  return (
    <div>
      <button type="button" onClick={() => { setDate(''); }}>Clears</button>
      <DateTimePicker
        value={dateTime}
        selectedDate={dateTime}
      />
    </div>
  );
};
```
* We can observe that selected date remains same even after setting date value to empty('') on button click.

---issue 2
* Set any date value like '2019-02-09T09:10:00' as default value for date-time-picker
* Add Button to set the date-time value on click
```javascript
const DateTimePickerExample = () => {
  const [dateTime, setDate] = useState('');

  return (
    <div>
      <button type="button" onClick={() => { setDate('2020-01-01T01:10:09'); }}>Set 2020-01-01T01:10:09</button>
      <DateTimePicker
        value={dateTime}
        selectedDate={dateTime}
      />
    </div>
  );
};

```
* We can observe that selected date remains same even after setting date value to empty('') on button click.

## Additional Context / Screenshots

**Date-Picker with default-date, Clears previous set date on button click  :** 

![Date-Picker-Clear-Onclick](https://user-images.githubusercontent.com/12869809/72150012-8837f380-33ca-11ea-824a-fa05921fd327.gif)

**Date-Time-Picker with default date and time, Does not clears previously set date on button click :** 

![Date-Time-Picker-Clear-Onclick](https://user-images.githubusercontent.com/12869809/72150210-03010e80-33cb-11ea-8216-dd58ec74ff8c.gif)

**Date-Time-Picker with default date and time, Changes only date-value on button click :** 

![Date-Time-Picker-Set-Onclick](https://user-images.githubusercontent.com/12869809/72151362-077af680-33ce-11ea-833e-7a39e6c9af86.gif)

**Empty Date-Time-Picker, Changes only date-value on button click and ignores time-value :** 

![Date-Time-Picker-Set-Empty-Onclick](https://user-images.githubusercontent.com/12869809/72151426-2e392d00-33ce-11ea-81be-4084171dd813.gif)

## Expected Behavior
1. Need input on clearing out selected date and time from date-time-picker programmatically.
2. Should update time-value.

## Possible Solution
1. date-picker has [logic to block date-value update when the value prop is undefined](https://github.com/cerner/terra-framework/blob/5ed477fafea09d0e0d89476706592d97f918c01d/packages/terra-date-picker/src/DatePicker.jsx#L383). When user sets value prop as empty value('') to clear date-time in date-time-picker, value prop is converted to `undefined` by DateTimeUtils.createSafeDate() method. Hence date-picker blocks clearing the date-value. Possible Fix would be handling empty value in date-time-picker similar to date-picker. So that empty value gets passed to date-picker from date-time-picker instead of undefined value.

2. When updating date-time value in date-time-picker only date-value gets the new value in render method. 
```javascript
 const dateValue = DateUtil.formatMomentDate(dateTime, 'YYYY-MM-DD');
```
updating time-value also like [date-value](https://github.com/cerner/terra-framework/blob/5ed477fafea09d0e0d89476706592d97f918c01d/packages/terra-date-time-picker/src/DateTimePicker.jsx#L615) in render method will resolve the above mentioned issue of 'Time value in terra-date-time-picker is not updating when date and time is set programmatically'

## Environment
* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@benbcai

**Comment by benbcai** [comment]
@supreethmr 

Issue 1: The date picker can be either an uncontrolled or controlled component. However, the date-time picker should always be an uncontrolled component and should not allow updating the value after the initial render so we do not expect the consumer to be able to clear the value.

Issue 2: I think this is a bug. The date-time picker should not allow updating the date value when the default value is empty. The fact that you are able to is due to this [block of code](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-time-picker/src/DateTimePicker.jsx#L190-L196) for updating the state. I believe this piece of code should be removed to prevent updating the state so that consumer cannot update the value.
