### ISSUE TITLE
Terra Theme Provider cannot provide proper theme encapsulation.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-framework#1002]
# Bug Report

## Description
Terra theme provider does not provide theme encapsulation for all theme-able values. By default theme provider places the theme class on a div that the component renders. This will only apply the css theme variables to selectors below this div. Terra base places theme-able variables on both `html` and `body` which will not be themed by a default theme provider.

Theme provider has a `isGlobalTheme` prop which will place the theme class on the html div which will theme the html and body theme-able variables but does not allow nested theme providers.

## Steps to Reproduce
1. Setup theme provider to not use `isGlobalTheme`.
2. Theme a variable on `html` or `body`.

## Expected Behavior
All theme-able variables are themed.

## Possible Solution
I investigated possibly moving the theme variables from `html` and `body` to being applied the theme provider div, which works for most them-able variables except `font-size` which must remain on `html` due to REM calculation.

My recommendation as of now is to remove the optional `isGlobalTheme` prop and to make that behavior the default. This does not allow for theme encapsulation and cannot as long as `font-size` remains a theme-able variable.

**Comment by ShettyAkarsh** [comment]
@mjhenkes  shouldn't  this be an MVB ? as consumers using this prop isGlobalTheme will have to update their code.

**Comment by mjhenkes** [comment]
@ShettyAkarsh, no this is not a MVB. terra-theme-provider is broken as it is now. Consumers passing in `isGlobalTheme` are the only consumers with a completely working version of terra-theme-provider. After we remove the `isGlobalTheme` prop and make that behaviour the default, consumers passing in the isGlobalTheme prop would be passing in an unneeded prop, but the behaviour of the component will be exactly the same. They can remove the prop whenever they desire or not at all.
