### ISSUE TITLE
[application-navigation] Update background color value

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#1037]
# Feature Request

## Description

Update variable value from white to `transparent` to allow terra-base background to display in terra-application-navigation.

https://github.com/cerner/terra-framework/blob/19f601ac23a4aa0d1951cccf3cb8f2e45d0482c7/packages/terra-application-navigation/src/ApplicationNavigation.module.scss#L41

Change to:
```
    background-color: var(--terra-application-navigation-content-layout-background-color, transparent);
```

**Comment by tbiethman** [comment]
#1038 was reverted by #1040 due to an unexpected impact to the component's animations. Reopening this for more discussion.
