### ISSUE TITLE
[terra-slide-panel] Component is mounting and unmounting when changing panelPosition

### ISSUE THREAD

**Issue by Me999999999** [cerner/terra-framework#1068]
# Bug Report

## Description

When using terra-slide-panel and switching the panelPosition prop value, the mainContent is mounted and unmounted. After investigating this issue it was found that the reason this is occurring is the following **if** statement - [Link](https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.jsx#L124
). When panelPosition is changed a new React.Fragment is created causing the mounting and unmounting. After removing this if statement and instead always rendering the same React.Fragment we are not seeing any mounting/unmounting and the slide panel still seems to act as expected.

## Steps to Reproduce

1. Setup a slide panel
2. Create a button that updates panelPosition
3. The mainContent unmounts when the panelPosition is changed

## Expected Behavior

We expect that our mainContent should not mount or unmount when panelPosition is changed.

## Possible Solution

Remove the **if** statement on this [line](https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.jsx#L124).

## Environment

* Component Name and Version: terra-slide-panel v3.23.0
* Browser Name and Version: Chrome
* Node/npm Version: [npm 5.6.0]
* Webpack Version: 4.42.0
* Operating System and version (desktop or mobile): desktop

## @ Mentions

@tbiethman

**Comment by tbiethman** [comment]
The flexing of the panel/mainDiv order is important for accessibility purposes. I wonder if putting an explicit key on both fragments would keep them from unmounting?

**Comment by Me999999999** [comment]
@tbiethman 
I briefly tested the idea of adding a key to both the Panel and Main content. This removed the mounting and unmounting and both the Panel and Main content were still able to be changed. I'm sure further testing would need to be done to verify nothing else is broken.
If we want to move forward with such a fix would you accept a contribution? We are needing a change to fix the unmounting before we can move forward with one of our implementations.

**Comment by tbiethman** [comment]
@Me999999999 A contribution would be great.

**Comment by supreethmr** [comment]
Do you have any screenshots or reduced test case for showing mounting and unmounting of maini component..?
