### ISSUE TITLE
[terra-tabs] Application w/clinical theme and clinical-lowlight-theme interfere

### ISSUE THREAD

**Issue by jdnarvaez** [cerner/terra-framework#1092]
# Bug Report
We have been using a component that activates the clinical lowlight theme when it is mounted as it is intended to be used within an imaging environment. We embed this component in a regular clinical application that uses the clinical theme and previously the theme would activate/deactivate without issue. It now seems that with the latest terra-tabs and clinical lowlight theme there is bleed through between the clinical theme and the clinical lowlight theme for the tab backgrounds:

## Steps to Reproduce
Create an application with the clinical theme applied
Create a child component that later activates the lowlight theme

## Additional Context / Screenshots
<img width="1718" alt="Screen Shot 2020-04-09 at 1 43 16 PM" src="https://user-images.githubusercontent.com/3358381/78931080-e4aebb80-7a6a-11ea-8848-7fc7d8a63a4e.png">

## Expected Behavior
I would expect the tabs to render as they normally do with the lowlight theme applied

## Possible Solution
Fill out all theme properties for the themed components.

## Environment

* Component Name and Version: terra-tabs 6.32
* Browser Name and Version: Chrome 
* Node/npm Version: node 10
* Webpack Version: 4
* Operating System and version (desktop or mobile): macOS Catalina

## @ Mentions
@mjhenkes

**Comment by saket2403** [comment]
I was unable to re create the issue on dev site. Am I doing something wrong as far as workflow is concerned. cc @mjhenkes @jdnarvaez .
![TabIssue](https://user-images.githubusercontent.com/42207428/81803307-1ec12080-9535-11ea-8a84-7e9a3c814093.gif)

**Comment by mjhenkes** [comment]
@saket2403 You won't be able to recreate this on dev-site. The issue occurs when the lowlight theme is applied over a theme other than the terra-default-theme because the lowlight theme is not defining all the theming variables. To correct this backfill missing theme variables in the lowlight theme with the terra-default-theme values. This is basically the same work we're doing while we're adding the theme context.
