### ISSUE TITLE
date-picker does not appear to honor locale correctly when date is selected

### ISSUE THREAD

**Issue by JB016205** [cerner/terra-framework#1103]
# Bug Report

## Description
We noticed in our WDIO testing that dates weren't being displayed correctly based on locale in the date-picker. We first wondered if we were passing data incorrectly, but the issue is reproducible on the [TERRA](https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker) site. 

## Steps to Reproduce
1. Change locale to one that does not follow MM-DD-YYYY
2. Choose a date and see that the locale's pattern is not followed (IE: DD-MM-YYYY)

## Additional Context / Screenshots
![Screen Shot 2020-05-01 at 1 59 53 PM](https://user-images.githubusercontent.com/3382775/80833461-2e934900-8bb4-11ea-8dd7-6ee27cf905b7.png)
Helper text looks good.

I then entered May 28th, 2020.

![Screen Shot 2020-05-01 at 2 00 01 PM](https://user-images.githubusercontent.com/3382775/80833498-41a61900-8bb4-11ea-9919-6d777a0f9fe4.png)

## Expected Behavior
We expect the locale to be honored. We noticed this problem in the clinical-onset-picker but tracked it down to the date-picker being at fault (per the test site).

## Possible Solution
An underlying dependency could have caused locale to be blank or strings to be formatted incorrectly. The component has the locale since the helper text is handled correctly (unless these are hardcoded string values, in which case it may still be locale getting to the component).

## Environment

* Component Name and Version: date-picker, clinical-onset-picker (current release for both)
* Browser Name and Version: Chrome 81.0.4044.129 (Official Build) (64-bit)
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): Mac OS, Android OS

## @ Mentions
N/A

**Comment by benbcai** [comment]
This was introduced by the recent release of moment v2.25.0. A patch version ([2.25.1](https://github.com/moment/moment/releases/tag/2.25.1)) just got released which fixes this.
