### ISSUE TITLE
Hamburger sign not visible on terra application navigation while zooming in the page.

### ISSUE THREAD

**Issue by Laveena1998** [cerner/terra-framework#1111]
# Bug Report

## Description
Hamburger sign not visible on terra application navigation while zooming in the page.
https://github.cerner.com/hi-malvern/dwt-app/tree/Devupdate

## Steps to Reproduce

1. Launch the page
2. Zoom in the page
3. On the top left of page, hamburger sign not visible

## Additional Context / Screenshots

<img width="988" alt="Untitled" src="https://user-images.githubusercontent.com/26977581/81573810-a20e3500-93c2-11ea-9206-35ae962995e2.png">
<img width="988" alt="Untitled1" src="https://user-images.githubusercontent.com/26977581/81573820-a5a1bc00-93c2-11ea-857e-b099a6bfed2c.png">

## Expected Behavior

Hamburger sign should be available.
## Environment

* Component Name and Version: terra-application-navigation and 1.25.0
* Browser Name and Version: Google Chrome and IE11
* Node/npm Version: [e.g. Node 10.16.0/npm 6.9.0]
* Webpack Version: 
* Operating System and version (desktop or mobile): Windows 64bit

## @ Mentions

https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1588832992087?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1588832992087&teamName=Terra&channelName=Component%20Support&createdTime=1588832992087

**Comment by ryanthemanuel** [comment]
@Laveena1998 how are you zooming in?  We were able to zoom in on the terra ui site using chrome (View -> Zoom In) and it seems to work fine.  Are you zooming in some other way?

**Comment by Laveena1998** [comment]
@ryanthemanuel Its working on terra ui site. But when we apply the same code and try to run it in chrome its not working.

**Comment by ryanthemanuel** [comment]
@Laveena1998 spoke with UX and our team about this.  Unfortunately, we do not first class support zooming in in this fashion yet as a mechanism for making the app respond.

cc @neilpfeiffer @jeremyfuksa
