### ISSUE TITLE
Modal Manager Scroll Behavior

### ISSUE THREAD

**Issue by DimplesSan** [cerner/terra-framework#114]
# Issue Description
The scroll bar behavior for terra-modal-manager seems odd on Internet Explorer and Safari & Chrome on iOS. We checked the examples on terra-framework's doc site http://engineering.cerner.com/terra-framework/#/site/components/modal-manager/index  in IE and Safari. 

**NOTE: Scroll functionality is unaltered. Visual discrepancy only.**

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
1. In Internet Explorer, we can should see one vertical single scroll bar(preferably thin)
2. In Safari, on an iOS emulator and on device, the vertical scroll bar should be visible disclosures greater than 2.

## Current Behavior
1. In Internet Explorer, we can see two vertical scroll bars (one thick and one thin).
![modalmanagerscrollissue1](https://user-images.githubusercontent.com/9302440/37438587-e4a3fa7e-27c9-11e8-8320-e9acac461b30.gif)

2. In Safari/Chrome, on an iOS emulator and on device, the scroll bar disappears when we disclose after the first disclosure.
![modalmanagerscrollissue](https://user-images.githubusercontent.com/9302440/37438520-530b4842-27c9-11e8-884f-a6a436224fa5.gif)

## Steps to Reproduce
For the issue on IE
1. Open IE 11 and navigate to http://engineering.cerner.com/terra-framework/#/site/components/modal-manager/index
2. Scroll all the way to the bottom where the examples are available.
3. Click on button labeled `Disclose (Medium)`.
4. Reduce the size the window such that the content is more than the height of the window.
5. If only vertical scroll is used, we can see a thin scroll bar.
6. If the mouse is moved horizontally, we can see a thick scroll bar that sometimes overlaps the content of the disclosure.

For the issue in Safari/Chrome on iOS
1. Open IE 11 and navigate to http://engineering.cerner.com/terra-framework/#/site/components/modal-manager/index
2. Scroll all the way to the bottom where the examples are available.
3. Click on button labeled `Disclose (Medium)` .
4. Reduce the size the window such that the content is more than the height of the window.
5. Click on disclose again to view the nested disclosure. The scroll bar disappears on the nested disclosure

## Environment

* Component Version: 2.1.0
* Browser Name and Version: Internet Explorer 11 
* Operating System and version (desktop or mobile): Windows 7 desktop (mobile view)

* Browser Name, Version and OS: Safari on iOS 10.2 emulator and Chrome (65.0.3325.152) on iOS 11.0.3

**Comment by nramamurth** [comment]
I tested it out on Modal Manager v6.17.0 on IE 11.0.9600.19463 and on iOS 13.2 and I do not see this issue. This could be closed, imo. 

cc / @ryanthemanuel @dkasper-was-taken
