### ISSUE TITLE
[terra-application-name] Missing themeable variable

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-framework#1171]
# Bug Report

**clinical-lowlight-them**

--terra-application-name-demo-background-color - packages/terra-application-name/lib/terra-dev-site/test/application-name/demoStyles.module.scss (line: 3, column: 4)

**orion-fusion-theme**

--terra-application-name-demo-background-color - packages/terra-application-name/lib/terra-dev-site/test/application-name/demoStyles.module.scss (line: 3, column: 4)

**Comment by lokesh-0813** [comment]
@ryanthemanuel  `--terra-application-name-demo-background-color` is used for terra-dev-site examples and test.

**Comment by emilyrohrbough** [comment]
@lokesh-0813 I think this issue is to add the theme values for `--terra-application-name-demo-background-color` in the clincial-lowlight-theme and the orion-fusion-theme.

**Comment by ryanthemanuel** [comment]
@lokesh-0813 yes this is used for examples and tests but we want to provide good examples for our consumers including how those might be themed.

**Comment by lokesh-0813** [comment]
> @lokesh-0813 yes this is used for examples and tests but we want to provide good examples for our consumers including how those might be themed.

@ryanthemanuel Got it. Are there any recommended/preferred colours for fusion and lowlight theme that match the standards and do not cause colour contrast issues?

**Comment by ShettyAkarsh** [comment]
Adding @neilpfeiffer , @jeremyfuksa

**Comment by jeremyfuksa** [comment]
Fusion can use the same color as open source. Low Light can use `#407d17`.
