### ISSUE TITLE
[terra-application-utility] Missing themeable variables

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-framework#1173]
# Bug Report

The following variables are missing:

**clinical-lowlight-theme**

--terra-application-utility-header-type-menu-button-close-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 108, column: 4)
--terra-application-utility-header-type-menu-page-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 116, column: 4)

**orion-fusion-theme**

--terra-application-utility-header-type-menu-button-close-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 108, column: 4)
--terra-application-utility-header-type-menu-page-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 116, column: 4)

**Comment by jeremyfuksa** [comment]
Neither variable is defined in the parent stylesheet. Both values can be set to `flex`.
