### ISSUE TITLE
[terra-notification-dialog] Missing themeable variables

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-framework#1175]
# Bug Report

The following variables are missing:

**clinical-lowlight-theme**

--terra-notification-dialog-max-width - packages/terra-notification-dialog/lib/NotificationDialog.module.scss (line: 19, column: 6)
--terra-notification-dialog-title-margin-top - packages/terra-notification-dialog/lib/NotificationDialog.module.scss (line: 102, column: 4)

**orion-fusion-theme**

--terra-notification-dialog-max-width - packages/terra-notification-dialog/lib/NotificationDialog.module.scss (line: 19, column: 6)
--terra-notification-dialog-title-margin-top - packages/terra-notification-dialog/lib/NotificationDialog.module.scss (line: 102, column: 4)

**Comment by jeremyfuksa** [comment]
@emilyrohrbough 's PR should take care of this when it's done. I've replied to specific spots within the PR itself.
