### ISSUE TITLE
Date picker is not displaying correct year on invalid date

### ISSUE THREAD

**Issue by saigorantla** [cerner/terra-framework#1185]
# Bug Report

## Description
If you enter date manually in date picker (10/10/1990) and click on the calendar Icon it displays 10 date and 10 month but it will display current year.

## Steps to Reproduce
1. Manually enter date that is in past year (10/10/2019)
2.Click on calendar Icon.

## Additional Context / Screenshots
<img width="227" alt="Screen Shot 2020-07-10 at 11 07 10 PM" src="https://user-images.githubusercontent.com/8334184/87216218-2ddd0880-c303-11ea-9966-ff9d1fe06a4f.png">

## Expected Behavior
Expecting to see year as entered in date field. for example if this date (10/10/2019) is entered expecting to see 2019 in calendar display

## Environment

* Component Name and Version: Terra-date-picker (4.40.0)
* Browser Name and Version: chrome (83.0.4103.116)
* Node/npm Version: 11.0.0/6.13.7
* Webpack Version: 4.41.2
* Operating System and version (desktop or mobile): mac os

**Comment by saigorantla** [comment]
Note: Date in past is invalid date.

**Comment by saigorantla** [comment]
Looks like its happening only for invalid dates, 
<img width="185" alt="Screen Shot 2020-07-10 at 11 32 43 PM" src="https://user-images.githubusercontent.com/8334184/87216472-ba88c600-c305-11ea-83ec-ccb6b0722ad1.png">

**Comment by benbcai** [comment]
@saigorantla It appears that you have set a minDate and the date (06/29/1990) is before the minDate you defined. In this scenario, the `06/29/1990` date that you entered will not be registered as a valid date. As a result, the entered will be ignored by the date picker and the previous valid date will be kept. This is working the way that it is intended.

**Comment by neilpfeiffer** [comment]
@ShettyAkarsh Confirmed with @benbcai that we consider this a bug and we went through some scenarios that should help describe how to resolve:

Scenarios:
_Use the "Min Max Selection Options" docsite example on [Terra-Date-Picker](https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker)_

_(adding)_

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.
