### ISSUE TITLE
[terra-slide-panel] side content z-index

### ISSUE THREAD

**Issue by ezargar** [cerner/terra-framework#1195]
# Bug Report

## Description
While scrolling down the  slide panel in powerchart ,  the title header provided from workflow component is overlapped by the side content of slide panel so using powerchart debugger tools we can see the zIndex of the side content of slide panel is greater than workflow title header . I have tried decreasing the zIndex of the side content using query selector , it works only in gaia server . 

## Steps to Reproduce

1. Open Powerchart in deveng domain
2. Search for the **graph, overview**  patient
2. Select the Pregnancy Workflow tab in the toolbar 
3. Look for Add pregnancy cloud component
4. click on the slide panel 

## Expected Behavior

Side content of slide panel should not overlap the title header 

## Possible Solution

lowering  the z-index of side content

## Environment

* Component Name and Version: Add Pregnancy Cloud Component 
* Browser Name and Version:
* Node/npm Version: node 8.9.2
* Webpack Version: 
* Operating System and version (desktop or mobile): desktop

**Comment by ryanthemanuel** [comment]
This is an internal issue. Closing and will log something internally.
