### ISSUE TITLE
[date-picker] : dotted border gets added to selected day / active day on mouse enter 

### ISSUE THREAD

**Issue by supreethmr** [cerner/terra-framework#1215]
# Bug Report
dotted border gets added to selected day / active day on mouse enter when calendar is opened via keyboard.

## Steps to Reproduce
1. navigate to default date picker example : https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker
2. click on date input and press TAB to access calendar button 📅  of date-picker component.
3. press ENTER to open a calendar and move cursor into days region.
4. dotted border gets added to current day.

## Additional Context / Screenshots
![date-picker-hover-inconsistency](https://user-images.githubusercontent.com/12869809/89987279-6a51aa80-dc9b-11ea-8d7b-6bc6645a367d.gif)

## Expected Behavior
should not add dotted border on mouse enter. 

## Possible Solution
I suspect the focus styles ( dotted border on day ) would be appearing due to the re-render that caused by state updates on [mouseEnter](https://github.com/cerner/terra-framework/blob/d3d47c6515f352e306f0e69958e06cad787b1b31/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L437). So we might need to evaluate the use case of setting selectingDate on MouseEnter and we can rid of this event if not required to prevent focus styles from getting appeared on mouse enter.

OR

in calendar.jsx value of `keyboardFocus` is set to prop `isCalendarKeyboardFocused` which is part of [condition statement](https://github.com/cerner/terra-framework/blob/d3d47c6515f352e306f0e69958e06cad787b1b31/packages/terra-date-picker/src/react-datepicker/day.jsx#L222) that adds dotted-border around day.

`keyboardFocus` is being set on line [642](
https://github.com/cerner/terra-framework/blob/d3d47c6515f352e306f0e69958e06cad787b1b31/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L642) depending on the props `isCalendarOpenedViaKeyboard` OR `isCalendarKeyboardFocused` value, which will be true when calendar is opened via keyboard. 

here we might need to consider state 'this.state.calendarIsKeyboardFocused` (in this [condition](https://github.com/cerner/terra-framework/blob/d3d47c6515f352e306f0e69958e06cad787b1b31/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L641)) before setting value for `keyboardFoucs` so that focus styles will appear only when calendar is focused keyboard interactions like TAB or Arrow keys.
```diff
+     if((this.props.isCalendarOpenedViaKeyboard || this.props.isCalendarKeyboardFocused) && this.state.calendarIsKeyboardFocused) {
      keyboardFocus = true;
    }

-  if(!keyboardFocus && this.state.calendarIsKeyboardFocused) {
-      keyboardFocus = true;
-   }
```

## Environment

* Component Name and Version: terra-date-picker 
* Browser Name and Version: Chrome

**Comment by benbcai** [comment]
Based on this [comment](https://github.com/cerner/terra-framework/pull/994#issuecomment-587482809), the pre-selected day should have the dotted focus style when the picker is opened using the keyboard whereas there should be no initial focus style if opened by mouse click or touch. However, the issue appears to be that when opened by keyboard the focus style appears only when hovering over the calendar area.

> Pressing the calendar-icon-button before the calendar picker appears by mouse/touch would set style to false, selecting the calendar-icon-button by pressing the enter key would set it to true (or assume for keyboard first and turn off with mouse clicks of any button).
