### ISSUE TITLE
[terra-date-picker] Remove `onClickOutside` that is replaced by `onDismiss`

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-framework#1222]
## Description
`onDismiss` was introduced in #1219 to replace the deprecated `onClickOutside`. `onClickOutside` can be removed in the next major version.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by emilyrohrbough** [comment]
Is this function called when the display should be dismissed or after it has been dismissed?

@tbiethman Left this comment on a recent PR mentioning `onRequestClosed` was better for my scenario. Not sure if it could be applied here as well.

Comment left on the Notification Banner PR: https://github.com/cerner/terra-application/pull/45#discussion_r438549394

**Comment by benbcai** [comment]
The callback function will be invoked when it is _about_ to be dismissed but not yet dismissed. It will be dismissed after this [state](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L464) is updated and re-rendered. @emilyrohrbough Are you thinking `onRequestClosed` is a more appropriate name than `onDismiss` for the date-picker case?

**Comment by ShettyAkarsh** [comment]
Closed in [PR](https://github.com/cerner/terra-framework/pull/1224)

**Comment by benbcai** [comment]
Should we reopen this? #1224 only deprecated `onClickOutside`. This issue is for completely removing it in the next MVB.
