### ISSUE TITLE
nl-BE translations missing for notification-dialog

### ISSUE THREAD

**Issue by sudharshanv1992** [cerner/terra-framework#1232]
# Bug Report

## Description

nl-BE translations missing for notification-dialog title. But works fine for en-US and sv-SE

## Steps to Reproduce

1. go to https://engineering.cerner.com/terra-framework/tests/terra-notification-dialog/notification-dialog/hazard-medium-variant
2. change the locale to nl-BE
3. click on trigger NotificationDialog button
4. Warning title doesn't show up
5. change the locale, warning title shows up

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/28642254/92584199-f7931980-f2b0-11ea-9985-a68814e2310c.png)

## Environment

* Component Name and Version: notification-dialog
* Browser Name and Version: chrome
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by supreethmr** [comment]
looks like translations for variant `hazard-medium` are missing in both [nl](https://github.com/cerner/terra-framework/blob/main/packages/terra-notification-dialog/translations/nl.json) and [nl-BE](https://github.com/cerner/terra-framework/blob/main/packages/terra-notification-dialog/translations/nl-BE.json)
