### ISSUE TITLE
[terra-date-input] Enhance month select for better usability

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#1241]
# Feature Request
PR #1230 updates the `DateInput` component to remove the placeholders from the inputs ('DD' from day, 'YYYY' from year) and changes the placeholder in the month dropdown select from "Month" to the new UX standard placeholder "_- Select -_" but does not change the behavior of the month select. The previous behavior originally implemented is now not up to the latest UX behavior standards.

## Description

Cerner UX standards dictate that a user should be able to "_clear_" the selected value in a select dropdown after choosing a value by selecting the placeholder option value. The current implementation is unclear to the user, as it shows in the closed/faceup state of the select the placeholder, but when opening the options list, it shows the first option, "January" with a check as if it is selected, even though the user hasn't selected it. Then after a user does select an actual value (e.g. "January", "February", "March", etc.), they are unable to clear it, if it was on accident and not a required field, unable to  return it to an unset value.

| Current behavior  |
| --- |
| ![date-input-after-PR#1230](https://user-images.githubusercontent.com/1355485/92984356-2e169300-f46f-11ea-92a8-b05bb27ce226.gif) |

\
\
The default behavior built-in to the [terra-form-select/.../NativeSelect](https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/native-select) shows the intended behavior desired for the month selector in `DateInput`, where when the placeholder displays ("_- Select -_"), the user understands nothing has been selected. A user can choose/set an option from the list, then choose the placeholder again to "_clear_" & unset the previously selected/set option.

| Intended behavior - same as Native-Select |
| --- |
| ![native-select-intended-behavior](https://user-images.githubusercontent.com/1355485/92984435-b1d07f80-f46f-11ea-9a29-4b3fc6171cd6.gif) |

## @ Mentions
Followup for PR #1230
@pranav300 @jeremyfuksa

**Comment by saket2403** [comment]
Although I have made the changes, has there been any discussions to replace the html select with the recently added native-select variant in terra-form select? cc @neilpfeiffer
