### ISSUE TITLE
[terra-date-input] Firefox wrapping the year input when set to inline

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#1243]
# Bug Report

## Description
Firefox displays the year input wrapped on the next line when DateInputField is set to `isInline`

## Steps to Reproduce
1. See the `Inline DateInputField` example in Firefox

## Additional Context / Screenshots
<img width="488" alt="Screen Shot 2020-09-12 at 9 02 06 PM" src="https://user-images.githubusercontent.com/1355485/93037268-a3b56700-f607-11ea-92f8-e04c05a4e542.png">

## Expected Behavior
When set to Inline, should not wrap the year input.

## Possible Solution
https://github.com/cerner/terra-framework/blob/0cbfdf5745af49f9e3b4273a34253078e1dd9aed/packages/terra-date-input/src/DateInput.module.scss#L10
Revert to original default styles before PR #1230, `flex-wrap: wrap` to `flex-wrap: nowrap`

**Comment by benbcai** [comment]
I'm seeing the wrapping in other examples in Chrome as well. Not just the `inline` example and Firefox.

**Comment by PaulSolDev** [comment]
Was unable to reproduce this issue on the existing component example.  Sync'd with Neil and noted wrapping issue on his device/browser and the corrected display with the new deployment.  No further issues noted.  Functional review complete.

**Comment by neilpfeiffer** [comment]
@benbcai can you verify that the PR fixes the issues you are seeing in Chrome?
https://terra-framew-date-input-8g9nja.herokuapp.com/components/terra-date-input/date-input/date-input-field

Paul reviewed the the current state in his Firefox, and it wasn't wrapping like I saw, we had same version numbers (`80.0.1 (64-bit)`). Sounds like your Chrome might be doing the same thing, as I don't see it at Chrome (Mine is `Version 85.0.4183.102 (Official Build) (64-bit)`) . Trying to determine what might be causing the layout calculation difference (browser add-on perhaps?), but regardless, the style change in the PR should resolve it.

**Comment by benbcai** [comment]
@neilpfeiffer Yes, it does fix the issue in FF and Chrome for me. One difference I see between FF and Chrome is as the screen size gets smaller, the inputs in Chrome keeps shrinking where as in FF those inputs gets to a minimum width and stops shrinking. My FF and Chrome versions are the same as yours.

![wrap3](https://user-images.githubusercontent.com/22618655/93355132-59003e80-f803-11ea-8ce5-53e435ddca49.gif)
