### ISSUE TITLE
[terra-navigation-side-menu] Update chevrons for rtl support

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#125]
# Issue Description
The chevrons inside NavigationSideMenu items are not flipped for the 'rtl' direction.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The chevron should be rotated when the direction is changed.

## Current Behavior
The chevron remains right-facing when 'rtl' direction is enabled.

**Comment by tbiethman** [comment]
![https://user-images.githubusercontent.com/29487301/37796269-de4bac46-2de4-11e8-9f10-29e036f94f1a.png](https://user-images.githubusercontent.com/29487301/37796269-de4bac46-2de4-11e8-9f10-29e036f94f1a.png)

**Comment by Blackop778** [comment]
Chevrons are functioning as expected in rtl mode
![screen shot 2018-06-08 at 3 28 54 pm](https://user-images.githubusercontent.com/11130785/41179569-b6901ee2-6b30-11e8-8c00-8674eb6a5eb4.png)
