### ISSUE TITLE
[terra-application-utility] Update chevron in ApplicationMenuUtility for rtl support

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#126]
# Issue Description
The chevron inside the ApplicationMenuUtility is not flipped for the 'rtl' direction.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The chevron should be rotated when the direction is changed.

## Current Behavior
The chevron remains right-facing when 'rtl' direction is enabled.

**Comment by tbiethman** [comment]
![https://user-images.githubusercontent.com/29487301/37796269-de4bac46-2de4-11e8-9f10-29e036f94f1a.png](https://user-images.githubusercontent.com/29487301/37796269-de4bac46-2de4-11e8-9f10-29e036f94f1a.png)

**Comment by Blackop778** [comment]
The chevrons are functioning as expected in rtl mode
![screen shot 2018-06-08 at 3 24 13 pm](https://user-images.githubusercontent.com/11130785/41179429-4b7f9fd8-6b30-11e8-8fce-3761fa7aa900.png)
