### ISSUE TITLE
document the need to mock uuid for date/time component jest snapshots

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#1271]
# Feature Request
with the date/time component placeholder removals, a component will have a unique id per instance via uuid - let's document this for consumers and recommend mocking these ids for jest snapshots, otherwise snapshots will differ on each run.

- [ ] terra-date-input
- [ ] terra-date-time-input
- [ ] terra-time-input
- [ ] terra-date-time-picker

i could have missed a component

**Comment by ryanthemanuel** [comment]
Let's include documentation with this that we would recommend teams use "shallow" (which would negate this problem).  If for some reason they need to use mount, then they would need to mock uuid as described above.
