### ISSUE TITLE
terra-date-time-picker date and time fields not reflecting updated value

### ISSUE THREAD

**Issue by leducquan** [cerner/terra-framework#1281]
# Bug Report

## Description
Attempting to update the terra-date-time-picker value via a button does not get reflected in the fields.

## Steps to Reproduce

Added code sandbox to display issue:

1. Click on 'Reset' Button
2. Values in date time fields do not get updated.

https://codesandbox.io/s/trusting-poincare-oxopd?file=/src/App.js

## Expected Behavior
Value in date and time fields to be updated to reflect latest value in state

## Environment
Chrome/IE

**Comment by pranav300** [comment]
@leducquan, date-time-picker is an uncontrolled component. Therefore it isn't supposed to update programmatically.

You can go through issue #1000 for more information.

**Comment by mjhenkes** [comment]
Closing as a duplicate
