### ISSUE TITLE
 Create template component for Application Menu

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-framework#13]
# Issue Description
 Create template component for Application Menu

## Issue Type
- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Template should provide buckets to place content into, to be used with the navigation layout.

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by neilpfeiffer** [comment]
Tested: PR #14
Resolves: Issue #13 & #6


**Reviewed:**
- Follows UX defined design implementation for initial release


\
\
Verified by @mndrsn and @neilpfeiffer, Ready for Release.

**Pass** |
-----------|
UX Review|

**Comment by jmsv6d** [comment]
Closed with https://github.com/cerner/terra-framework/pull/14
