### ISSUE TITLE
[terra-menu]  Menu items almost invisible in lowlight

### ISSUE THREAD

**Issue by hboege** [cerner/terra-framework#1348]
# Bug Report

## Description
The disabled menu items are almost completely invisible in lowlight.  

## Additional Context / Screenshots
See the lowlight [screenprint](https://github.com/cerner/terra-framework/blob/main/packages/terra-menu/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/menu-item-spec/Menu_Item-Disabled%5Bdisabled%5D.png) as an example.  There should be menu items below the first sentence.

## Expected Behavior
Items should be dimmed, but should not be so dark it looks like nothing more is in the menu.

## Possible Solution
Increase the lowlight text contrast for disabled text.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by ryanthemanuel** [comment]
@jeremyfuksa we will need some input on this.

**Comment by jeremyfuksa** [comment]
Disabled text can be `#656565`.
