### ISSUE TITLE
[terra-application-navigation] Screen Reader is not reading the username.

### ISSUE THREAD

**Issue by saket2403** [cerner/terra-framework#1355]
# Bug Report

## Description
Screen Reader is not reading the username in the top right corner of the page instead it reads it `user settings button`.

## Steps to Reproduce

1. Open dev site [example](https://engineering.cerner.com/terra-ui/components/terra-application-navigation/application-navigation/example)
2. Turn on Voice Over.
3. Navigate using tabs to the username 

![Uploading Screenshot 2021-01-15 at 4.47.57 PM.png…]()

## Expected Behavior
Should read username also along with `user settings button`

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by saket2403** [comment]
The aria-label for the button has been set [here](https://github.com/cerner/terra-framework/blob/946edacbadc181ba083a4e5df403d7fd521af816/packages/terra-application-navigation/src/utility-menu/_UtilityMenuHeaderButton.jsx#L42), which reads as 'User Settings' (Translation [here](https://github.com/cerner/terra-framework/blob/946edacbadc181ba083a4e5df403d7fd521af816/packages/terra-application-navigation/translations/en-AU.json#L13)). If it is to read the username as well this needs to be changed.

**Comment by neilpfeiffer** [comment]
Yes, this could be updated for better accessibility, thanks @saket2403 and @tbiethman.

Let's update the translation to be able to receive the provided username, so the translations team can adjust the phrase structure, adjusting the separator as needed (e.g. ":") and moving the username around as it best fits for the language, something like what [paginator](https://github.com/cerner/terra-core/blob/8d5ad998fd564eeaa7b7484f1cd72e743bcd907d/packages/terra-paginator/src/ControlledPaginator.jsx#L101 ) does:

```diff
-      "Terra.applicationNavigation.header.utilityButtonTitleUser": "User Settings",
+      "Terra.applicationNavigation.header.utilityButtonTitleUser": "User Settings for: {currentUserName}",
```

Note: you'll need to be sure to explain this in the translation JIRA description, that they can put the `{currentUserName}` part anywhere in the localized phrase that is most appropriate, and change the colon as most appropriate, for that language when they are creating the updated phrases. Something like "User Settings for: {currentUserName}" will generate "User Settings for: Neil Pfeiffer"



\
\
The implementation then passes in the userConfig.name to the translated phrase:
```diff
-    ariaLabel = intl.formatMessage({ id: 'Terra.applicationNavigation.header.utilityButtonTitleUser' });
+    ariaLabel = intl.formatMessage({ id: 'Terra.applicationNavigation.header.utilityButtonTitleUser' }, { currentUserName: userConfig.name });
 ```



\
\
And just for reference, some examples of how it should compile:

|userConfig.name|result|
|----|----|
|"TestUser"| `aria-label="User Settings for: TestUser"` |
|"Neil Pfeiffer"| `aria-label="User Settings for: Neil Pfeiffer"` |
|"Pfeiffer, Neil"| `aria-label="User Settings for: Pfeiffer, Neil"` |
|"NP123456"| `aria-label="User Settings for: NP123456"` |
