### ISSUE TITLE
[terra-popup] Missing terra-mixins Dependency

### ISSUE THREAD

**Issue by joel-cohen** [cerner/terra-framework#137]
# Issue Description
The terra-popup component is using terra-mixins ([link](https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/PopupContent.scss#L1)), however the terra-mixins component is not listed as a dependency.

As a result when building our application with webpack the extract-text-webpack-plugin is throwing the following error:

```
ERROR in ./~/css-loader?{"sourceMap":true,"importLoaders":2,"localIdentName":"[name]__[local]___[hash:base64:5]"}!./~/postcss-loader/lib?{}!./~/sass-loader/lib/loader.js?{"data":"$bundled-themes: /"mock/";"}!./~/terra-popup/lib/PopupContent.scss
Module build failed:

^
      File to import not found or unreadable: ~terra-mixins.
      in /home/pophealth/workspace/referral_management/client/node_modules/terra-popup/lib/PopupContent.scss (line 2, column 1)
 @ ./~/terra-popup/lib/PopupContent.scss 4:14-168
 @ ./~/terra-popup/lib/_PopupContent.js
 @ ./~/terra-popup/lib/Popup.js

ERROR in ./~/terra-popup/lib/PopupContent.scss
Module build failed: ModuleBuildError: Module build failed:
```

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Terra should include the terra-mixins as a dependency so that build processes do not fail when looking for terra-mixins when using the Terra-Popup component.

## Current Behavior
Build processes are not able to locate the terra-minixs component, so they are failing.

## Steps to Reproduce
1.  Use the Terra-Popup component in a react component.
2.  Use webpack with the **extract-text-webpack-plugin** with the following loaders: **css-loader**, **postcss-loader**, and **sass-loader**.
3.  Run webpack.

## Environment

* Component Version: 2.4.0
* Browser Name and Version: Google Chrome; Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra; Version 10.12.6

**Comment by bjankord** [comment]
I'll pick up the fix for this.

**Comment by dkasper-was-taken** [comment]
If we are going to continue to use terra-mixins we should remove the bi-di mixins to avoid confusion. Not necessarily part of this change, but prior to this I thought we were trying to discourage the use of this package.
