### ISSUE TITLE
[terra-tabs] Selected tab name getting cut off while other unselected tabs are face up

### ISSUE THREAD

**Issue by juliacalandro** [cerner/terra-framework#1391]
# Feature Request

## Description
I am logging this as a feature request since I don't think it is an actual bug, but just something that can be slightly improved as a delighter.

We noticed that when we have multiple available tabs and the last tab is selected in the tiny viewport, if the tab label is relatively long, it will be shortened while other unselected tabs remain face up. We were thinking that ideally, the selected tab would be prioritized the highest to have its name fully visible if possible, and then the other unselected tabs would be hidden behind the dropdown as necessary.

If I collapse the view to a small enough size, I can make it so that the full tab name is visible once the other unselected tabs are hidden.

## Additional Context / Screenshots
![Screen Shot 2021-03-29 at 1 05 43 PM](https://user-images.githubusercontent.com/39311706/112882528-b28ad500-9092-11eb-8214-b22b24cb659f.jpg)
![Screen Shot 2021-03-29 at 1 06 24 PM](https://user-images.githubusercontent.com/39311706/112882565-bc143d00-9092-11eb-96bc-dc1b7fa10614.jpg)
![Screen Shot 2021-03-29 at 1 05 29 PM](https://user-images.githubusercontent.com/39311706/112882586-c20a1e00-9092-11eb-8d07-2a524bc7d6ae.jpg)

**Comment by ryanthemanuel** [comment]
Closing per my comment above.
