### ISSUE TITLE
[modal-manager][slide-panel-manager] Remove the onMaximize and onMinimize defaulted implementation

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#1392]
# Bug Report

## Description

[Modal-Manager](https://engineering.cerner.com/terra-ui/components/terra-modal-manager/modal-manager/about) and [Slide-Panel-Manager](https://engineering.cerner.com/terra-ui/components/terra-slide-panel-manager/slide-panel-manager/slide-panel-manager) implement the `DisclosureManagerHeaderAdapter` header, which contains the 
`onMaximize` and `onMinimize` props and [implement](https://github.com/cerner/terra-framework/blob/main/packages/terra-modal-manager/src/ModalManager.jsx#L107-L108) them as assumed default behaviors, when they should not be assumed or defaulted. Modal content needing an expand to fullscreen behavior is not standard Cerner UX practice and needed only rarely. Same with slide-panels, which do not require an expand to fullscreen/full-width as a defaulted behavior. 

Having the expand/maximize icon always present in every modal and slide-panel in its current position without ability to opt in or out, for every modal that is presented creates a usability risk, since it is not expected by users and could easily create confusion or interruption.  Removing the implementation of the `onMaximize` and `onMinimize` props for the immediate term is recommended by UX.
 
Future enhancements will likely be addressing these problems, possibly by moving the location and changing the styling of the onMaximize/onMinimize buttons to better align with users' mental model of OS-style window frames and to be less disruptive, or more content-aware or implementation specific.

## Additional Context / Screenshots

Modal-Manager
![Screen Shot 2021-03-30 at 5 14 49 PM](https://user-images.githubusercontent.com/1355485/113163379-bb4fe800-9205-11eb-86d2-5dac257b7c06.png)

Slide-Panel-Manager
![Screen Shot 2021-03-30 at 5 16 49 PM](https://user-images.githubusercontent.com/1355485/113163406-c3a82300-9205-11eb-9ec0-f8171820df29.png)

## Expected Behavior

The expand to fullscreen is a rarely needed with current approaches, and can be implemented by content teams as a prop of the modal or slide-panel to initially disclose at fullscreen. Removing the implementation of the `onMaximize` and `onMinimize` props for the immediate term is recommended by UX.

## Possible Solution

Remove

https://github.com/cerner/terra-framework/blob/45ad1d99ed07912cd88170585c9bc431b6a034ca/packages/terra-modal-manager/src/ModalManager.jsx#L107-L108

and 

https://github.com/cerner/terra-framework/blob/45ad1d99ed07912cd88170585c9bc431b6a034ca/packages/terra-slide-panel-manager/src/SlidePanelManager.jsx#L104-L105

**Comment by ryanthemanuel** [comment]
Prototype: https://github.com/cerner/terra-framework/commit/6668d1e68bed96ca344feb9095ca1684754a65c1
