### ISSUE TITLE
terra-application-navigation not themed for clinical-lowlight-theme

### ISSUE THREAD

**Issue by Me999999999** [cerner/terra-framework#1394]
# Bug Report

## Description

When trying to view terra-application-navigation in clinical-lowlight-theme the theme variables are not being correctly applied.
https://pages.github.cerner.com/orion/orion-application/components/orion-application/demo
<img width="1278" alt="Screen Shot 2021-02-11 at 1 13 59 PM" src="https://user-images.githubusercontent.com/23201118/107686640-1be19080-6c6b-11eb-82cb-c0c55610204f.png">

## Steps to Reproduce

1. Navigate to https://pages.github.cerner.com/orion/orion-application/components/orion-application/demo
2. Switch to clinical-lowlight-theme
3. Nav Bar and portions of the Utility Menu are not themed correctly

## Additional Context / Screenshots

<img width="1278" alt="Screen Shot 2021-02-11 at 1 13 59 PM" src="https://user-images.githubusercontent.com/23201118/107686640-1be19080-6c6b-11eb-82cb-c0c55610204f.png">

## Expected Behavior

All components should be correctly themed when using a theme.

## @ Mentions

@StephenEsser @mjhenkes

**Comment by neilpfeiffer** [comment]
After further investigation of the `_DrawerMenu` and the `_PopupMenu`, theme values are correctly being provided for Lowlight and Fusion themes:

| clinical-lowlight-theme | orion-fusion-theme |
| ---- | ---- |
| [DrawerMenuCommon.module.scss](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/src/clinical-lowlight-theme/DrawerMenuCommon.module.scss) | [DrawerMenuCommon.module.scss](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/src/orion-fusion-theme/DrawerMenuCommon.module.scss) |
| [PopupCommon.module.scss](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/src/clinical-lowlight-theme/PopupCommon.module.scss) | [PopupCommon.module.scss](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/src/orion-fusion-theme/PopupCommon.module.scss) |

\
\
and they are correctly being applied, shown in the WDIO tests:
- [../chrome_large/application-navigation-spec/ 1__Popup_Open.png](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_large/application-navigation-spec/1__Popup_Open.png)

- [../chrome_large/application-navigation-spec/ tabs_roll_up_properly.png](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_large/application-navigation-spec/tabs_roll_up_properly.png)

- [../chrome_small/application-navigation-spec/ 1__Drawer_Open.png](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_small/application-navigation-spec/1__Drawer_Open.png)

- [../chrome_small/application-navigation-spec/ ApplicationNotifications_displays_nav_drawer.png](https://github.com/cerner/terra-framework/blob/main/packages/terra-application-navigation/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_small/application-navigation-spec/ApplicationNotifications_displays_nav_drawer.png)

\
\
It was found that theme context was missing, therefore making the application navigation popup menu and drawer menu appear to not be themed when dynamically switching themes with devsite, resolved by https://github.com/cerner/terra-framework/pull/1393
