### ISSUE TITLE
[terra-slide-panel] Background Color is not Themeable

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-framework#140]
# Issue Description

[SlidePanel.scss:9](https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.scss#L9) is not themeable, just have to update to use a var.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

The slide panel should be themeable

## Environment

* Component Version: terra-slide-panel@2.3.0
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

**Comment by PseudoFaux** [comment]
Addressed in #141.

**Comment by yuderekyu** [comment]
#141 has been merged.
