### ISSUE TITLE
[terra-disclosure-manager] [IE] The maximize/minimize button of the Modal remains highlighted after clicked

### ISSUE THREAD

**Issue by KunigundaLauly** [cerner/terra-framework#1409]
# Bug Report

## Description

The maximize/minimize button of the Modal remains highlighted after clicked in Internet Explorer.

## Steps to Reproduce

1. Open the https://engineering.cerner.com/terra-ui/components/terra-modal-manager/modal-manager/about page
2. Open a modal
3. Click on the maximize/minimize button

## Additional Context / Screenshots

Chrome:
![chrome](https://user-images.githubusercontent.com/47626274/116680756-57f3da00-a9ac-11eb-9f43-9607081feeb0.gif)
IE:
![ie](https://user-images.githubusercontent.com/47626274/116680765-5aeeca80-a9ac-11eb-87d3-b648ef717940.gif)

## Expected Behavior

Chrome and IE should work the same way. IE should not focus/highlight the button after click.

## Environment

* Component Name and Version: terra-application/lib/disclosure-manager
* Browser Name and Version: Internet Explorer 2004
* Node/npm Version: N/A
* Webpack Version:N/A
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ryanthemanuel** [comment]
We would expect this to behave as Chrome behaves in this case. Flagging as a bug.

**Comment by ShettyAkarsh** [comment]
we could close this issue as these buttons have been removed in this PR #1408.

**Comment by KunigundaLauly** [comment]
Since they have bene removed, I'm closing this ticket. Thanks for the feedback.
