### ISSUE TITLE
terra-collapsible-menu-view overrides consumer onClick when expanded

### ISSUE THREAD

**Issue by JoeJennings** [cerner/terra-framework#1412]
# Bug Report

## Description
The menu item behaves differently between if the menu item with a submenu is expanded vs. collapsed. The terra-collapsible-menu-view has its own onClick handler for when the menu button is expanded so it can open and close the menu https://github.com/cerner/terra-framework/blob/main/packages/terra-collapsible-menu-view/src/CollapsibleMenuViewItem.jsx#L146

In the process it is overwriting any onClick handler passed by the consumer. Whereas the terra-menu item in the collapsed menu will call the onClick handler provided by the consumer after doing its own onClick logic https://github.com/cerner/terra-framework/blob/main/packages/terra-menu/src/MenuItem.jsx#L134.

## Steps to Reproduce
1. 

## Expected Behavior
The menu item behaves the same whether the menu item with a submenu is expanded or collapsed.

## Possible Solution
The onClick seems is a first class prop for Menu.Item so removing that would be non-passive. An update to collapsible menu view to also call the onClick handler of the consumer when expanded might be a possible solution

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@jmsv6d

**Comment by ShettyAkarsh** [comment]
@JoeJennings , correct me if i am wrong. so are you seeing the same issue displayed below ?

https://user-images.githubusercontent.com/45097016/122074573-f4682380-ce16-11eb-8e12-fc5e0777803e.mov

**Comment by saket2403** [comment]
I re-created the issue and fixed it using `shouldCloseOnClick` prop. So no changes should be required for the existing component.

https://user-images.githubusercontent.com/42207428/122869209-8efdc080-d349-11eb-8355-cbb51d764b80.mov
