### ISSUE TITLE
[terra-application-navigation] Do not display the menu button for the compact header when the navigation items are empty and the titleConfig has an empty title

### ISSUE THREAD

**Issue by charmse** [cerner/terra-framework#1428]
# Bug Report

## Description

Currently, I am using the application navigation component where we do not have any navigation items and are using the titleConfig, but we simply passing in an empty string for the the title and a logo in the 'element' entry. The issue this creates is that when the screen is compact the menu is button is appearing, but there isn't any content to display in the menu fly-out. This also indents the logo in the header which creates an awkward-looking UI.

I apologize as I'm unsure exactly if this falls within the parameters of a bug or feature request.

## Steps to Reproduce

1. Utilize the application navigation component while 
2. Do do not supply any navigation items and for the titleConfig supply an empty title and image for the element entry.

## Additional Context / Screenshots

Current:
<img width="569" alt="Screen Shot 2021-07-02 at 1 15 00 PM" src="https://user-images.githubusercontent.com/14985371/124331648-41f1c980-db55-11eb-8d45-8a1ec4c73260.png">

<img width="571" alt="Screen Shot 2021-07-02 at 1 14 52 PM" src="https://user-images.githubusercontent.com/14985371/124331635-39998e80-db55-11eb-9632-53d82d9bb84a.png">

After suggested change:
<img width="511" alt="Screen Shot 2021-07-02 at 12 55 40 PM" src="https://user-images.githubusercontent.com/14985371/124331668-4e762200-db55-11eb-9c49-522d3e5e8ddf.png">

## Expected Behavior

I would expect the menu button to not display in the compact header.

## Possible Solution

In the renderMenuButton (L181) function of the _CompactHeader.jsx component, don't simply check if the titleConfig is empty but check to see if `titleConfig.title` is an empty string.

## Environment

* Component Name and Version: terra-application-navigation 1.51.0
* Browser Name and Version: Firefox
* Node/npm Version: [e.g. Node 8/npm 5] 6.14.6
* Webpack Version: 5.28.0
* Operating System and version (desktop or mobile): Mac OS 11.4

**Comment by ryanthemanuel** [comment]
Spoke with @charmse offline and we determined that this is not an issue. The title prop is a required prop due to accessibility concerns.
