### ISSUE TITLE
New terra-pill component

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-framework#1441]
# Feature Request
Create the Pill component based on the OCS designs posted in zeplin:
Basic Pill:
https://app.zeplin.io/project/59b1bfeae515657fa8268300/screen/5b60abaaa8b621561b120d39

Removable Pill: 
https://app.zeplin.io/project/59b1bfeae515657fa8268300/screen/5f3d9d37694a9912ac38b2df

Roll Up Pill: 
https://app.zeplin.io/project/59b1bfeae515657fa8268300/screen/5f3316c0c4dcb05133097579

**Comment by neilpfeiffer** [comment]
### API Update:
After completing initial testing, pills currently has too many options that make some of the interaction combinations undesirable, as such we are proposing another adjustment to the approach.

----

## Mark III - Proposed Changes
### Reduce the mix and match variations to just one type: Filter Pills
Currently the design is separated into (1)basic `Pills` component and (2)`SelectablePills` component, where features include for both they can either (A)be visually limited to a single line or (B)wrap lines as needed, and both included a repeatable `pill` subcomponent that can be either be (C)removable or (D)non-removable.

  The proposed changes are:
* [Pill Group] reduce the types to just a single pill grouping, called `FilterPills`, other dedicated types will follow later with future enhancements
* [Pill Group] remove `onSelect`
* [Pill Group] continue to provide a boolean prop for limiting the pill grouping to either a single line with a rollup “5 more… “ button, or wrap to multiple lines of pills as needed 
* [Pill] limit the included `pill` subcomponent to always be removable
* [Pill] remove the ability for the included `pill` to have a selectable label via a consumer adding a customizable popup (the label is only ever selectable if the text of the label becomes truncated
* [Pill] continue to include internally the popup as a method to show the full `pill` label when it must truncate, making the label section selectable in only those cases (is going to require additional changes to UI to display differently between the two cases)


![FilterPills](https://user-images.githubusercontent.com/1355485/133611011-300bffc5-23e7-456b-bda5-22d512e88847.png)


### Example Usage
```jsx
import React, { useState } from 'react';
import FilterPills from 'terra-pills';

const AppliedFilters = () => {
  const pills = [
    {
      label: ‘Asthma',
    },
    {
      label: ‘Bronchitis',
    },
    {
      label: ‘Fibro',
    },
  ];
  const [pillsState, setPillsState] = useState(pills);

  const handleOnRemove = (pillKey, metaData) => {
    const pillsArray = pillsState;
    pillsArray.splice(metaData.index, 1);
    setPillsState([...pillsArray]);
  };

  return (
    <div className={cx('applied-filters')}>
      <span
        id="terra-pills-example-applied-filters-label"
        className={cx('applied-filters-label')}
      >
        Applied Filters:
      </span>
      <FilterPills
        ariaLabel="Applied Filters"
        ariaLabelledBy="terra-pills-example-applied-filters-label"
        onRemove={handleOnRemove}
      >
        {pillsState.map((pill, index) => (
          <FilterPills.Pill
            label={pill.label}
            pillKey={pill.label}
            metaData={{ index }}
          />
        ))}
      </FilterPills>
    </div>
  );
};

export default AppliedFilters;

```

----

### Prop Changes

**FilterPills:** (pill group)
| Prop Name | Type | Is Required | Default Value | Description |
|----------|------|--------------|---------|--------------|
| ariaLabel | string | required | none | The string that labels the collection of pills, used in cased where the text label is not visible on the screen and required for minimum accessibility standards. Providing this prop adds the `aria-label` attribute to the Pills container element. (Required) |
| ariaLabelledBy | string | optional | undefined |  If a visible text label is used with the collection of pills, provide a string of the ID for the html element containing the visible text label. Supplying the 'ariaLabelledBy' prop will override the 'ariaLabel' prop and adds the aria-labelledby attribute instead to the Pills container element. For best practices, ensure the visible text in the html element id provided to the Pills ariaLabelledbyprop matches the text provided to the ariaLabel prop, for consistency in the case of fallback or errors. |
| ariaDescribedBy | string | optional | undefined | If additional visible information text is used, provide a string containing the IDs for html elements that help describe the intent of the group of pills. |
| children | node | optional | undefined | The content to be shown in the pills container. Should only contain the sub-component `<Pills.Pill>`. |
| isSingleLine | bool | optional | undefined |  Determines if the Pills group should be shown as rolled up or not, limited to a single line of display. |
| onRemove | func | optional | undefined | Callback function triggered on click/keypress of any included removable pill. |
| onSelectRollUp | func | optional | undefined | Callback function triggered on click/keypress of the roll-up pill when group of pills is collapsed. | 
| intl | shape | required (private) | undefined | The intl object to be injected for translations. |

----

### Prop Changes

**FilterPills.Pill** (single pill)
| Prop Name | Type | Is Required | Default Value | Description |
|----------|------|--------------|---------|--------------|
| id | string | required | none | The html 'id' attribute for the pill, needed for proper interactability (Required must be unique) |
| label | string | required | none | The label text for the pill. (Required)|
| pillKey | string | required | undefined | To identify which pill is being removed. |
| metaData | object | required | undefined | Object returned along with the pillKey in the onRemove callback. |
| intl | shape | required (private) | undefined | The intl object to be injected for translations. |


Privately the `Pills.Pill` component will provide these details when the pill is truncated and needs to add it's own popup:
| Prop Name | Type | Is Required | Default Value | Description |
|----------|------|--------------|---------|--------------|
| refCallback | string | optional (private) | undefined | Callback to expose pill element's ref for popup placement, used when pill label is truncated |
| ariaExpanded |  bool | optional (private) | undefined | Sets the aria-expanded attribute to false when the label is truncated and the popup is not visible, and sets it to true when the label is truncated, user has clicked on the label button and the popup is currently visible. |
 | title | string | optional (private) | undefined | Tooltip to display on mouse hover, will show the same contents as the label, added only when the label is truncated | 

----





### Additional Items: 
* Update a11y hint phrases to remove the reference to “pills”, change to neutral “items” plus combine with pill group label for better clarity (updated phrases to be provided)
* Add hint phrases confirming after a filter pill has been removed
* When collapsed to Single Line, add hint phrases confirming additional items are displayed after rollup “X more…” button has been pressed
* Update tests and doc examples with focus only on (Removable) Filter Pills usage

**Comment by ShettyAkarsh** [comment]
@neilpfeiffer, quick questions on the above API's.

1.  i think we might also need **onRemove** callback part of FilterPills.Pill. but as private.
2.  so regarding **labelCategory** prop.  can you provide some more inputs on how this secondary label values should be used and displayed ?

@mjhenkes , @ryanthemanuel , @tbiethman  kindly review the new API and share your thoughts.

**Comment by mjhenkes** [comment]
1. metadata on the pill should be optional
2. tech design nitpick: intl belongs in the private props section.
3. I don't really like the prop names for `isSingleLine` and `onSelectRollUp`, but don't have suggestions, just something to talk about.

**Comment by tbiethman** [comment]
Do we have more clarity around the `isSingleLine` prop and how we expect it to be implemented by consumers? I'd expect the `onSelectRollUp` callback to make it false, but how do we expect it to be re-enabled? Is this state we can maintain internally at this point (start rolled up -> click rollup button to expand -> roll back up when pill container loses focus)?

**Comment by neilpfeiffer** [comment]
Updated the API above to change the approach for the `isSingleLine` and `onSelectRollup` -- now that all inner pills are always interactive, we can move the management to re-collapse the pill group back internally after the pills in the pill group loses focus. (Was originally externalized for consumer responsibility since some pills could be non-interactive). 

This would allow us to remove the `onSelectRollup` prop, and rename `isSingleLine` to `isCollapsible`.

Additional edits per comments above:
- removed the `metadata` prop, as we think it is no longer needed
- intl is listed as a private prop for both `FilterPills` and `FilterPills.Pill`

Also a new addition:
- `labelCategory` is a new prop added to the pill that will display an additional label text string in front of the the standard label, e.g. "**Start Date:** 12/12/2021"

**Comment by neilpfeiffer** [comment]
Updated FilterPills.Pill api table above to remove the `refCallback` and `ariaExpanded` private props, as they can be implemented completely internally when truncation occurs rather than needing to be listed as 1st class props.

**Comment by neilpfeiffer** [comment]
New UX requirement change just added/updated to the tech design above:

Instead of handling when the FilterPills group will automatically "roll up" and collapse based on when/if the pills no longer have focus, instead there is a changed requirement to have the expanded vs. collapsed state be triggered manually in both cases: to expand when rolled up by the user selecting the "5 more..." button, and to collapse back when selecting a new button to be added that will say something like "Hide 5..." or "Show less..."

(cc: @lokesh-0813 @ShettyAkarsh - we can discuss further as the UX designs are finalized)

**Comment by neilpfeiffer** [comment]
Reopening as work is in progress and missed the inactivity warning.
