### ISSUE TITLE
Add panelPosition (start, end) option to slide-panel-manager

### ISSUE THREAD

**Issue by sbulley09** [cerner/terra-framework#1443]
# Feature Request

## Description

Currently, if a consumer wishes to display a slide panel on the left side of the screen, they must use the terra-slide-panel and manually maintain the open state of that panel rather than using the disclosure-manager API. It would be nice to have the same ability for the slide panel manager to display the panel on the left side.

## Additional Context / Screenshots

The Worklist Framework is looking to add the ability to filter its content. The existing MPages Worklist uses a left side panel to house this functionality and we were supposedly looking to do the same thing. To accomplish this, we could maintain an open state for a SlidePanel and manually create the navigation, but would like to use the disclosure manager if possible.

## @ Mentions

@tbiethman

**Comment by ryanthemanuel** [comment]
After discussing with the team, this is functionality that they no longer need. Due to this and additional concerns of adding this functionality (i.e. creating a layer of inconsistency among consumers of the slide panel), we are going to go ahead and close this for now.
