### ISSUE TITLE
[Time Input] not following ISO-8601

### ISSUE THREAD

**Issue by elliott-hoffman-cerner** [cerner/terra-framework#1493]
# Bug Report
Updated to include the single digit hour bug.

The impact if I'm right about these bugs is that consumers wouldn't be able to parse the time value from the control with a standard ISO 8601 parser. Luckily none of these bugs seem to give ambiguous or silently-incorrect values.

## Description
I think Time Input's `value` format is slightly off of ISO-8601, based on a cursory reading of the wiki page at https://en.wikipedia.org/wiki/ISO_8601#Times.

TimeInput will sent a value of `Th:mm`, `Th:mm:ss`, `Thh:mm` or `Thh:mm:ss` based on whether showSeconds is true. However, the standard expects one of these formats:
* `hh:mm:ss` or `Thhmmss`
* `hh:mm` or `Thhmm`

The first bug is we are including both the `T` prefix and the `:` spacers. According to what I read it should be either or. The second bug is we are allowing single-digit hours while the standard specifies double-digit hours. Here are some examples:

* Instead of T9:22 we should either use T0922 or 09:22
* Instead of T13:00:01 we should either use T130001 or 13:00:01

I know wikipedia isn't always the most accurate source, and there are a bunch of ISO 8601 extensions so perhaps in reality this isn' the end of the world? On the other hand we do advertise value as (emphasis added):

> An **ISO 8601 string representation** of the time value in the input.

## How to reproduce
You can reproduce the T/: bug by entering any time into a time input and viewing the `value` in your console. You'll see both the `T` and the `:` spacers.

To reproduce the single-digit hour bug enter 9:22 AM in the time input and view the `value`. You'll see it's `T9:22`

## Possible Solution
A couple ideas:
**Passive proposal**
* For passivity we should immediately update our doc to advertise the format we use for value, and call out the differences from ISO so that our consumers know they can't assume an off-the-shelf library could parse our time values.
* Add a _true_ ISO-complaint isoValue and/or isoValueExtended field(s) that truly follow the format.  

**Breaking proposal**
Change `value` so it's strictly ISO compliant.

**Comment by elliott-hoffman-cerner** [comment]
@benbcai @jmsv6d @neilpfeiffer

**Comment by elliott-hoffman-cerner** [comment]
I updated the description to include a worse bug - single digit hour values. I am finding these while testing accessibility enhancements that I'm implementing on Time Input.

**Comment by elliott-hoffman-cerner** [comment]
Chatting with a few co-workers about this, the consensus is that the single-digit hour bug is legit, but the T/: bug might not be real. It's surprisingly difficult to find a clear and authoritative spec on just the time component of 8601. I looked at the W3C's notes on datetime as well as MDN's doc on datetime, but neither were clear enough for me.

Someone suggested we use W3C's XML spec as a (free) proxy for ISO-8601: https://www.w3.org/TR/xmlschema-2/#isoformats

**Comment by benbcai** [comment]
### **First issue:**
> The first bug is we are including both the T prefix and the : spacers. According to what I read it should be either or. 

From the sources that I read, it sounds like revision ISO-8601-1:2019 or later expects both the `T` and `:` in the _extended format_ whereas earlier revisions omitted the `T`.

Source 1: https://en.wikipedia.org/wiki/ISO_8601#Times

> ISO 8601 uses the 24-hour clock system. As of ISO 8601-1:2019, the basic format is T[hh][mm][ss] and the extended format is T[hh]:[mm]:[ss]. Earlier versions omitted the T (representing time) in both formats.

Source 2: https://262.ecma-international.org/11.0/#sec-date-time-string-format

> THH:mm
> THH:mm:ss
> THH:mm:ss.sss

Source 3: https://momentjs.com/docs/#/parsing/special-formats/

> moment("2010-01-01**T05:06:07**", moment.ISO_8601);
> moment("2010-01-01**T05:06:07**", ["YYYY", moment.ISO_8601]);


### **Second issue:**
> The second bug is we are allowing single-digit hours while the standard specifies double-digit hours. Here are some examples:
> 
> Instead of T9:22 we should either use T0922 or 09:22
> Instead of T13:00:01 we should either use T130001 or 13:00:01

I agree that terra-time-input should use a 2-digit hour. Terra-date-time-picker uses _momentjs_ to format the date [here](https://github.com/cerner/terra-framework/blob/terra-date-time-picker%404.72.0/packages/terra-date-time-picker/src/DateTimePicker.jsx#L643) and it correctly displays the hour with 3-digits.
![Screen Shot 2021-12-10 at 2 37 09 PM](https://user-images.githubusercontent.com/22618655/145639525-0eb1c584-383e-4c6f-834d-fea2a15b4091.png)

time-input doe not have a dependency on momentjs and does the ISO-8601 formatting manually [here](https://github.com/cerner/terra-framework/blob/terra-time-input%404.43.0/packages/terra-time-input/src/TimeInput.jsx#L686). We could add some logic to prepend the hour with a `0` if the hour is a single digit.

**Comment by elliott-hoffman-cerner** [comment]
I put together this codepen on momentjs and ios8601: https://codepen.io/elliott-hoffman-cerner/pen/abLmYYq

**Comment by benbcai** [comment]
An internal issue has been logged to track this issue.
