### ISSUE TITLE
Don't run full build checks on doc/markdown changes

### ISSUE THREAD

**Issue by xenoworf** [cerner/terra-framework#1505]
I propose we change our CI/CD triggers so that a full Travis build isn't run for certain trivial changes. I think it will speed up many PRs:
* Changes to mdx files - should only check for a valid changelog entry, not build the whole things.
* Changes to changelogs
* Changes that are only made in a comment, like `/** something`

Any others? I had a few PRs today held up on such things. It's annoying.

**Comment by elliott-hoffman-cerner** [comment]
@jmsv6d
