### ISSUE TITLE
Update dependabot to not generate PRs for major version bumps

### ISSUE THREAD

**Issue by xenoworf** [cerner/terra-framework#1506]
It would be nice if dependabot only spun up PRs when a minor or patch dependency update was detected. So far I have not seen one example of a dependabot major version bump PR being acted upon; usually the maintainers tend to schedule major bumps themselves when time permits. On the other hand, minor/patch (passive) bumps are great because can be push-button.

* My goal is less PR noise so we can increase our throughput of PRs.
* Am I correct or do we actually want dependabot to generate these automated PRs?

**Comment by elliott-hoffman-cerner** [comment]
@jmsv6d and @benbcai  what are your thoughts?

**Comment by benbcai** [comment]
I agree. Consuming a new major version would require some impact analysis.
