### ISSUE TITLE
[terra-date-time-picker] Keyboard Navigation not working for month dropdown in IE

### ISSUE THREAD

**Issue by saket2403** [cerner/terra-framework#1566]
# Bug Report

## Description
Consumers are not able to  move to different months - more than one level above or below from the months drop down using keyboard (up & down arrows). This issue is there only in IE but it works as expected in Edge and Chrome.

## Steps to Reproduce

https://user-images.githubusercontent.com/42207428/187381121-b96230db-5322-4a60-93a2-89ec96b48bc7.mov

## Environment

* Component Name and Version: Terra date time picker
* Browser Name and Version: IE 10/11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by chrismichalewicz** [comment]
UXPLATFORM-7793 logged to track this internally
