### ISSUE TITLE
Caret for settings menu doesn't rotate appropriately.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#158]
# Issue Description
The caret for the settings dropdown should point up when clicked, but it always points down.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Caret rotates appropriately when menu is opened vs closed.

## Current Behavior
Caret does no rotating.

<img width="124" alt="screen shot 2018-04-19 at 2 54 43 pm" src="https://user-images.githubusercontent.com/2552573/39015114-fdc22b78-43e1-11e8-9b08-b1b6a1a67709.png">

<img width="165" alt="screen shot 2018-04-19 at 2 54 46 pm" src="https://user-images.githubusercontent.com/2552573/39015120-0200d43c-43e2-11e8-961f-3adbaee1b92b.png">

**Comment by alecrowen** [comment]
N/A

**Comment by yuderekyu** [comment]
Curious, was it decided this was a non-issue? UX callouts don't flip the caret. But visually, this makes sense.

**Comment by JakeLaCombe** [comment]
Yup. It's a Non issue, for the reason you stated.
