### ISSUE TITLE
Height constraints on consuming ThemeProvider 

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-framework#180]
# Issue Description
The height of the ThemeProvider is causing the content to collapse.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The content wrapped by themeProvider should not collapse and should occupy the height of the window.

## Current Behavior
The themeProvider wraps its children in a div and it doesn't get height as 100%. 
<img width="562" alt="themeprovider height issue" src="https://user-images.githubusercontent.com/16544484/40081761-98c00d30-5854-11e8-84fb-9eb79174a172.png">

## Steps to Reproduce

1. Use `<ThemeProvider>{children like SlidePanelManager}</ThemeProvider>`
2. Check the height of the div from themeProvider, it is same as height of it children's content and not 100%  
3. It is important that themeProvider occupy the height of the window and not just content height, specially in case we want to use themeProvider to wrap a component like SlidePanel etc. Here the height of the div by themeProvider will be same as main content page and when we navigate to panel view the content of panel view will collapse as themeProvider doesn't occupy the height of the window.

**Comment by bjankord** [comment]
@mayurikini is this still impacting your team. A fix might be to add an inline style to theme provider to set that height as needed.

```jsx
<ThemeProvider themeName="lowlight-theme" style={{ height: '100%' }}>
```
