### ISSUE TITLE
[terra-date-picker] minDate maxDate are not string format

### ISSUE THREAD

**Issue by dp21g** [cerner/terra-framework#1802]
Proptype checks fail here because minDate and maxDate need to be of string format. This is causing our jest tests to fail.

https://github.com/cerner/terra-framework/blob/e631d877bf6dcb3798f62bd980f8d45b02daaeb5/packages/terra-date-picker/src/DatePicker.jsx#L500C17-L500C24

**Comment by dhruvchandak30** [comment]
@dp21g  I would like to work on this issue!
