### ISSUE TITLE
infinite-list rendering error

### ISSUE THREAD

**Issue by aman-106** [cerner/terra-framework#182]
#  Rendering terra infinte List
I am unable to render terra infinte List component. I am getting the error while using the component.

`You likely forgot to export your component from the file it's defined in. Check the render method of InfiniteList`

link for a use case 
https://github.cerner.com/SS051081/CongifToolUI/blob/slide/src/config/components/ConfigMainView.jsx

screenshot for same 
![image](https://user-images.githubusercontent.com/12495142/40111383-4af09c38-5920-11e8-9768-5f219dce9547.png)

 
## Issue Type
- [x] Bug

## Expected Behavior
it should render the infinite list but throws an error message in the console.

## Steps to Reproduce
1.clone the repo https://github.cerner.com/SS051081/CongifToolUI.git
2.npm install 
3.npm start 

## Environment
* Component Version:"terra-infinite-list": "^1.1.0"
* Browser Name and Version:Google Chrome Version 66.0.3359.139 
* Operating System and version (desktop or mobile):desktop

**Comment by ryanthemanuel** [comment]
@aman-106 is this still an issue?

**Comment by ryanthemanuel** [comment]
Talked with @dkasper-was-taken and he said this got resolved.  @aman-106 open a new issue if you're still having problems.
