### ISSUE TITLE
Create component Aggregator to maintain state and focus across component groups

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#19]
# Issue Description

Let's start with a definition.

"microcontainer" - a small, purposeful component with its own state, data sources, interactions with an application framework, etc.

Microcontainers tend to be combined or presented side-by-side to build workflows or information dashboards. This is fine as long as these microcontainers are isolated from one another. However, issues arise when actions within one microcontainer impact another. 

For example, given Microcontainers A and B (M-A and M-B), if a list selection within M-A needs to perform a list deselection within M-B, how does M-B get notified that it needs to update? Or if M-B is in the middle of a complex workflow and cannot perform its deselection without losing user data, how can M-B gracefully deny the intrusion without leaving both components in a half-formed state?

Many of these microcontainers also make use of shared disclosure mechanisms (historically SlidePanels) to present further information. Actions within that disclosure can impact the microcontainer. If a selection in the microcontainer was made to present the disclosure, does closing the disclosure perform a deselection? If the disclosure is managed by a parent component and shared amongst various microcontainers, how does that microcontainer even know that the disclosure was closed?

To help answer these questions, we're going to develop an Aggregator component (final name TBD) that will facilitate communication between its child microcontainers.

Example (pardon the weird flashing with the headers, CloudApp must know that my trial period is over):
![Example](https://d2ffutrenqvap3.cloudfront.net/items/3Z3N2N1M3m2n3x391L3j/Screen%20Recording%202018-01-08%20at%2003.21%20PM.gif)

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Tech design to follow.

**Comment by StephenEsser** [comment]
![hangovermath](https://user-images.githubusercontent.com/6720991/34694304-311a96cc-f48c-11e7-9156-282fe1e49053.gif)

**Comment by tbiethman** [comment]
# Tech Design

The Aggregator has two main responsibilities:
* Managing which child microcontainer currently has "focus"
* Managing the state of its progressive disclosure mechanism

The concept of "focus" is the heart of the Aggregator. When a microcontainer wants focus from the Aggregator, it must first request focus using a provided function (named 'requestFocus' or similar). What the microcontainer does with that focus (selection/disclosure/etc) is entirely its business. The Aggregator is just there to ensure that if one microcontainer has focus, the other ones do not.

When a microcontainer requests focus, it should provide a couple pieces of data:
* An 'id' unique to that microcontainer instance. This id will be used to correlate requests and determine who has focus.
* An 'isLocked' function that returns a resolved or rejected Promise. This function will be called to determine if a microcontainer that currently has focus will give up that focus. If the Promise is rejected, the focus request will be rejected. If the Promise is resolved (or if no isLocked function is provided) the focus will transferred to the requesting microcontainer.
* A 'focusData' Object that holds any transient state data desired by the component if the focus request is accepted. This data parameter will be passed back to the microcontainer as a prop so it can be used for rendering. This data should _not_ be stored within the microcontainer's internal state since there is no good way for the Aggregator to clean it up when the focus changes. The Aggregator "owns" this state, but it doesn't care about its structure.

When focus is granted to a microcontainer, a couple things happen:
* The Aggregator stores the id and data from the focus action in its internal state, triggering a render cycle. The id and data are then given to every microcontainer as props (named 'focusId' and 'focusData' or similar). The individual microcontainers can then render based on these props and update any maintained internal state as necessary.
* The 'requestFocus' function returns a Promise. If rejected, the focus request was denied. If resolved, then the microcontainer can do subsequent actions.

I'm thinking that the Promise returned by 'requestFocus' will be resolved with an Object parameter containing a 'disclose' function that can be used to present content in the Aggregator's progressive disclosure mechanism. I think that is the only safe and reasonable place to expose that functionality; we don't want microcontainers to call it when they don't have focus, and we don't want calling it to be another focus stealing mechanism that bifurcates the API.

I should also note that the disclosure should not be a required side effect of the focus request. Maybe a component just wants to clear any previous selections while changing filters or something. Maybe a modal is being presented instead. I don't know what all folks are going to need, but the disclosure may not be desired 100% of the time.

Let's talk more about the disclosure. The jury is still out on what the disclosure is going be, UX-wise, but in the past the SlidePanel has been used to provide a slide-out disclosure mechanism, and we should probably start with that. I think that the disclosure API should follow that of the ModalManager, AppDelegate and all. However, I'm not sure if we want to support the nesting disclosures here like we do the ModalManager. We'll have to sync up with UX on that. If we follow the same disclosure patterns, and force the microcontainers to only provide serializable data to the requestFocus function, we can use Redux to back the Aggregator, which could be nice. We just need to verify whether its necessary.

The component that is presented within the disclosure will have a few responsibilities as well. It will be provided with a 'close' function that should be called to close the disclosure. When called, this function will hide the disclosure and remove focus from the currently focussed microcontainer. Also, just like how the presenting microcontainer can provide a Promise-generating 'isLocked' function to allow/disallow focus changes, the disclosed component should be able to lock its focus as well. However, we will have to rely on a callback to the Aggregator in the disclosed components 'componentDidMount' implementation to get that working, as there is no other way for the two components to communicate. Doing so should be optional and not very intrusive, but I wish we could align the lock API's better. Otherwise, the disclosed component can be completely autonomous or communicate back to the presenting microcontainer using events.

That is quite a bit to chew on, so here is a couple code examples that might help illustrate my points. Note that the disclosure stuff in these example files is still rough and not following the ModalManager standards. However, this code was used to produce the high-quality gif above.

```
// Example.jsx

import React from 'react';

import Aggregator from './Aggregator';
import Microcontainer from './Microcontainer';

const AggregatorExample = () => (
  <Aggregator>
    <Microcontainer name="Section 1" />
    <Microcontainer name="Section 2" />
    <Microcontainer name="Section 3" />
  </Aggregator>
);

export default AggregatorExample;
```

```
// Aggregator.jsx

import React from 'react';
import SlidePanel from 'terra-slide-panel';

class Aggregator extends React.Component {
  constructor(props) {
    super(props);

    this.requestFocus = this.requestFocus.bind(this);
    this.removeFocus = this.removeFocus.bind(this);
    this.disclose = this.disclose.bind(this);

    this.getLockPromises = this.getLockPromises.bind(this);

    // We don't need to keep these in state; doing so may trigger unnecessary renders.
    this.focusSectionLock = undefined;
    this.disclosureLock = undefined;

    this.state = {
      focusSectionId: undefined,
      focusSectionData: undefined,

      disclosure: undefined,
    };
  }

  getLockPromises() {
    const lockPromises = [Promise.resolve()];

    if (this.focusSectionLock) {
      lockPromises.push(this.focusSectionLock());
    }

    if (this.disclosureLock) {
      lockPromises.push(this.disclosureLock());
    }

    return lockPromises;
  }

  requestFocus(sectionId, sectionLock, selectionData) {
    return Promise.all(this.getLockPromises())
    .then(() => {
      this.focusSectionLock = sectionLock;

      this.setState({
        focusSectionId: sectionId,
        focusSectionData: Object.freeze(selectionData || {}),
      });
      return this.disclose;
    });
  }

  removeFocus(sectionId) {
    if (sectionId !== this.state.focusSectionId) {
      return Promise.reject();
    }

    return Promise.all(this.getLockPromises())
    .then(() => {
      this.focusSectionLock = undefined;
      this.disclosureLock = undefined;

      this.setState({
        focusSectionId: undefined,
        focusSectionData: undefined,
        disclosure: undefined,
      });
      return this.disclose;
    });
  }

  disclose(stuff) {
    if (stuff) {
      this.setState({
        disclosure: stuff,
      });
    }
  }

  render() {
    return (
      <SlidePanel
        fill
        panelBehavior="squish"
        isOpen={!!this.state.disclosure}
        panelContent={this.state.disclosure &&
          React.cloneElement(this.state.disclosure, {
            aggregator: {
              requestClose: () => { this.removeFocus(this.state.focusSectionId); },
              addDisclosureLock: (lock) => {
                this.disclosureLock = lock;
              },
            },
          })
        }
        mainContent={
          React.Children.map(this.props.children, child => (
            React.cloneElement(child, {
              aggregator: {
                activeSection: this.state.focusSectionId,
                sectionData: this.state.focusSectionData,
                requestFocus: this.requestFocus,
                removeFocus: this.removeFocus,
              },
            })
          ))
        }
      />
    );
  }
}


export default Aggregator;
```

```
// Microcontainer.jsx

import React from 'react';
import Button from 'terra-button';
import SelectableList from 'terra-list/lib/SelectableList';
import ContentContainer from 'terra-content-container';
import Header from 'terra-clinical-header';
import DisclosedContent from './DisclosedContent';

class Microcontainer extends React.Component {
  constructor(props) {
    super(props);

    this.handleSelection = this.handleSelection.bind(this);
    this.checkLockState = this.checkLockState.bind(this);
    this.lock = this.lock.bind(this);
    this.unlock = this.unlock.bind(this);

    this.state = {
      isLocked: false,
    };
  }

  checkLockState() {
    if (this.state.isLocked) {
      alert(`${this.props.name} is locked`);
      return Promise.reject();
    }

    return Promise.resolve();
  }

  unlock() {
    this.setState({
      isLocked: false,
    });
  }

  lock() {
    this.setState({
      isLocked: true,
    });
  }

  handleSelection(event, index) {
    const { aggregator, name, clearFocusOnRepeatSelect } = this.props;

    if (clearFocusOnRepeatSelect && aggregator.activeSection === name && aggregator.sectionData.index === index) {
      aggregator.removeFocus(name);
      return;
    }

    aggregator.requestFocus(name, this.checkLockState, {
      index,
    })
    .then((disclose) => {
      disclose((
        <DisclosedContent
          key={name + index}
          id={name}
          name={`Disclosure from ${name} - Row ${index}`}
        />
      ));
    })
    .catch((error) => {
      console.log(`selection denied ${error}`);
    });
  }

  render() {
    const { name, aggregator } = this.props;
    const { isLocked } = this.state;

    let selectedIndex;
    if (name === aggregator.activeSection && aggregator.sectionData && aggregator.sectionData.index !== undefined) {
      selectedIndex = aggregator.sectionData.index;
    }

    return (
      <ContentContainer
        header={(
          <Header
            title={name} endContent={(
            !isLocked ? <Button text="Lock" onClick={this.lock} /> : <Button text="Unlock" onClick={this.unlock} />
          )}
          />
        )}
      >
        <SelectableList
          isDivided
          selectedIndexes={selectedIndex !== undefined ? [selectedIndex] : []}
          onChange={this.handleSelection}
        >
          <SelectableList.Item
            content={
              <div style={{ padding: '10px' }}>Row 0</div>
            }
          />
          <SelectableList.Item
            content={
              <div style={{ padding: '10px' }}>Row 1</div>
            }
          />
          <SelectableList.Item
            content={
              <div style={{ padding: '10px' }}>Row 2</div>
            }
          />
        </SelectableList>
      </ContentContainer>
    );
  }
}

export default Microcontainer;
```

```
// DisclosedContent.jsx

import React from 'react';
import Button from 'terra-button';
import ContentContainer from 'terra-content-container';
import Header from 'terra-clinical-header';
import TextField from 'terra-form/lib/TextField';

class DisclosedContent extends React.Component {
  constructor(props) {
    super(props);

    this.checkLockState = this.checkLockState.bind(this);

    this.state = {
      text: undefined,
    };
  }

  componentDidMount() {
    this.props.aggregator.addDisclosureLock(this.checkLockState);
  }

  checkLockState() {
    if (this.state.text && this.state.text.length) {
      if (!confirm(`${this.props.name} has unsaved changes. Do you wish to continue?`)) {
        return Promise.reject();
      }
    }

    return Promise.resolve();
  }

  render() {
    const { id, name, aggregator } = this.props;

    return (
      <ContentContainer header={<Header title={'Disclosed Content'} />}>
        <div style={{ padding: '10px' }}>
          <h3>{name}</h3>
          <Button
            text="Close" onClick={() => {
              aggregator.requestClose()
                .then(() => {
                  console.log('Close succeeded');
                })
                .catch(() => {
                  console.log('Closed failed');
                });
            }}
          />
          {this.state.text && this.state.text.length ? <p>Dirty!</p> : <p>Not dirty!</p>}
          <TextField
            value={this.state.text || ''}
            onChange={(event) => {
              this.setState({
                text: event.target.value,
              });
            }}
          />
        </div>
      </ContentContainer>
    );
  }
}

export default DisclosedContent;
```

**Comment by jeffmerten** [comment]
Nice write up! :clap: I'm going to play around with this today with some of our existing micro containers, but I had a couple questions in the meantime.

> However, I'm not sure if we want to support the nesting disclosures here like we do the ModalManager.

Do you mean when a disclosed item triggers another disclosure (which ends up overlaying it)?
> we can use Redux to back the Aggregator. 

Do you see this as an alternative to the promise based approach, or an implimentation that has no impact to the proposed API that microcontainers utilize? 

Also, do you see this making the slide panel manager obsolete? https://github.com/cerner/terra-framework/issues/4

**Comment by mjhenkes** [comment]
This has been created
