### ISSUE TITLE
Use injectIntl prop from terra-base

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#203]
# Issue Description
terra-application-utility and terra-application-layout (_ApplicationHeader) use the `injectIntl` prop from `react-intl`. We should use the exposed `injectIntl` prop from terra-base instead (https://github.com/cerner/terra-core/pull/1379)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by corymcdonald** [comment]
I started working on this but am dealing with some minor issues with test failures.

**Comment by bjankord** [comment]
Closing this in relation to https://github.com/cerner/terra-core/issues/1982
