### ISSUE TITLE
[terra-brand-footer] FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by Trupti-Baliga** [cerner/terra-framework#216]
# Bug Report

## Description

Running a <code>yarn install</code> on project which includes the terra-brand-footer results in <code>FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory </code> on Mac-Sierra. Works fine on Mac-High Sierra

## Steps to Reproduce

1.  Terra component 'terra-brand-footer' was added to an existing app. (OS used - mac, high sierra)
2. A user with mac-sierra pulled the code, but is not able to do a <code> yarn install </code>
3. User gets the error as mentioned in the gist link

## Additional Context / Screenshots

Gist: https://gist.github.com/Trupti-Baliga/742b2e935d615fc2192064864b1029dc

## Expected Behavior

Terra-brand-footer should be visible on the page. 

## Environment

* Component Name and Version: Terra Brand Footer, v1.4.0
* Browser Name and Version: Google Chrome
* Node/npm Version: [e.g. Node 8/npm 5] Node v6.9.4/npm 3.10.10
* Webpack Version: ^2.6.1 , webpack-manifest-plugin: ^1.1.0
* Operating System and version (desktop or mobile): Mac Sierra

**Comment by Trupti-Baliga** [comment]
@bjankord : https://github.cerner.com/hisubmissionsdev/submissions/tree/HISUBDEV-119-Terra-Brand-Footer
This is a link to the branch in which we are implementing the Terra-Brand-Footer.

**Comment by Trupti-Baliga** [comment]
@bjankord : Is there any update on this issue?

**Comment by emilyrohrbough** [comment]
@Trupti-Baliga  I am looking at the dependencies you pull into your project and your project is still on React 15. The terra-brand-footer required React 16. This component was developed after our React 16 upgrade, so a react 15 version is not available for consumption.

**Comment by bjankord** [comment]
@Trupti-Baliga Please upgrade to react 16 and test again.

**Comment by Trupti-Baliga** [comment]
@emilyrohrbough @bjankord : Updated the react version to 16. Still facing the same issue. 
Branch : https://github.cerner.com/hisubmissionsdev/submissions/tree/HISUBDEV-119-Footer-with-Updated-React

**Comment by emilyrohrbough** [comment]
@Trupti-Baliga  You still need to bump your terra depenedencies to the correct versions to prevent mixing v15 and v16 of react. For example, you have defined [terra-button v1.14.0](https://github.cerner.com/hisubmissionsdev/submissions/blob/HISUBDEV-119-Footer-with-Updated-React/client/package.json#L55), however to be on a react 16 compatible version, this needs to be bumped to a [minimum of v2.0.0](https://github.com/cerner/terra-core/blob/master/packages/terra-button/CHANGELOG.md#200---february-12-2018). Please check the Changelogs of the components your project uses to find the minimum version that supports react 16.

**Comment by Trupti-Baliga** [comment]
@bjankord : This issue can be closed. It has been solved.
