### ISSUE TITLE
NotificationDialog Variants Icon does not get displayed in IE 11

### ISSUE THREAD

**Issue by paku-sruti** [cerner/terra-framework#217]
# Bug Report

## Description

On clicking the notification dialog in IE the icon does not get displayed. 
## Steps to Reproduce

1. Access the [terra-framework website](https://engineering.cerner.com/terra-framework/#/components/terra-notification-dialog/notification-dialog/notification-dialog)
2. Click on any of the `Trigger NotificationDialog` buttons
3. The notification Dialog pops up without any icon. 

## Additional Context / Screenshots

![screen shot 2018-07-05 at 10 21 29 am](https://user-images.githubusercontent.com/35706779/42332636-21c9f0b2-803e-11e8-95cd-1cda5e7a4dd4.png)

## Expected Behavior

The Icon should be displayed in the pop-up.
<img width="1197" alt="screen shot 2018-07-05 at 10 22 46 am" src="https://user-images.githubusercontent.com/35706779/42332650-2f2c1c9e-803e-11e8-8924-fef900df10b9.png">

## Environment

* Component Name and Version: Notification Dialog 1.1.0
* Browser Name and Version: IE 11
* Operating System and version (desktop or mobile): Windows

**Comment by bjankord** [comment]
I am able to reproduce this in IE 11. It looks like we are setting a background on an SVG in the DOM. We should try setting this background image on a div instead of an SVG element.

**Comment by bjankord** [comment]
I'm starting work on this.
