### ISSUE TITLE
NotificationDialog Text cuts off in IPhone

### ISSUE THREAD

**Issue by paku-sruti** [cerner/terra-framework#222]
# Bug Report

## Description

NotificationDialog text gets cut off in iPhone .

## Steps to Reproduce

1. Access notification dialog in iphone.

## Additional Context / Screenshots

![img_0160](https://user-images.githubusercontent.com/35706779/42400214-50f75df4-8136-11e8-9fec-ad7964622787.PNG)

## Expected Behavior

It should display the complete notification dialog. 
<img width="522" alt="screen shot 2018-07-06 at 3 38 06 pm" src="https://user-images.githubusercontent.com/35706779/42400074-d5d4d480-8135-11e8-811c-b262d01186c6.png">

## Environment

* Component Name and Version: NotificationDialog v1.1.0
* Browser Name and Version: Safari
* Operating System and version (desktop or mobile): IPhone X

**Comment by bjankord** [comment]
@paku-sruti What version of Safari is this happening on?

**Comment by paku-sruti** [comment]
@bjankord It is 11.1.2.

**Comment by bjankord** [comment]
I'm unable to reproduce on Safari 11 on iOS 11.4. I'll look and see if I can get 11.1.2.

**Comment by paku-sruti** [comment]
@bjankord I do not have my old device anymore.

**Comment by tbiethman** [comment]
I'm also unable to reproduce this on v12.0.1.
