### ISSUE TITLE
Update react-onclickoutside to latest major version in terra-hookshot

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#237]
# Feature Request

## Description
A newer major version is available for [react-onclickoutside](https://github.com/Pomax/react-onclickoutside). We should update hookshot to use the latest major release.

**Comment by dkasper-was-taken** [comment]
Looks like the new version relies on classList which isn't fully supported on IE 10 and 11. I don't know if we'd need some sort of polyfill for it.

**Comment by bjankord** [comment]
Ah, good find, yeah if we update to the new version, we'd need to polyfill classlist.

**Comment by bjankord** [comment]
Related: https://github.com/cerner/terra-core/issues/1602
