### ISSUE TITLE
Check if contentNode exists before handling InfiniteList resize

### ISSUE THREAD

**Issue by BrandonKraus30** [cerner/terra-framework#238]
# Bug Report

## Description
Since the handle resize function of the InfiniteList is on a delay, it could potentially get executed after the InfiniteList has already been removed from the page. This causes the following error to occur at [this line](https://github.com/cerner/terra-framework/blob/master/packages/terra-infinite-list/src/InfiniteList.jsx#L270) in InfiniteList.jsx:
"Cannot read property 'scrollHeight' of null"

## Steps to Reproduce
1. Create an element that contains an InfiniteList component.
2. Update the contents of the Infintelist.
3. Unmount the InfiniteList before the resize function is executed within the 250 ms timeframe.

## Expected Behavior
The InfiniteList's handleResize function should verify that this.contentNode is not null before checking if it should resize the component.

## Possible Solution
Modify [this line](https://github.com/cerner/terra-framework/blob/master/packages/terra-infinite-list/src/InfiniteList.jsx#L270) in InfiniteList.jsx to be:
`if (this.contentNode && (this.scrollHeight !== this.contentNode.scrollHeight || this.clientHeight !== this.contentNode.clientHeight))`

## Environment
* Component Name and Version: terra-infinite-list v1.8.0
* Browser Name and Version: Chrome v68
* Node/npm Version: node v8.7.0 / npm v5.4.2
* Webpack Version: 2.7.0
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by ShettyAkarsh** [comment]
Duplicate to #835
