### ISSUE TITLE
Side Menu loses focus after navigating links with keyboard

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#255]
# Bug Report

## Description
When I navigate in the sidebar with a keyboard and go into a submenu, I lose focus on the sidebar, and have to re tab through the page again to get to the navigation. It seems as though we should always be focused on the sidebar when navigating with it.

## Steps to Replicate
1. Tab through the page until you are at the sidebar.
2. Tab to a submenu.
3. Activate the submenu link.

# Expected Behavior
Focus is still in the menu

# Actual Behavior
Focus leaves the menu

**Comment by ryanthemanuel** [comment]
This is for the old terra-application navigation and outdated.
