### ISSUE TITLE
NotificationDialog's onRequestClose prop is unnecessarily marked as required

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#258]
# Bug Report

## Description
The NotificationDialog has a required `onRequestClose` prop that is provided to the `AbstractModal` used internally. I assume it's marked as required for the NotificationDialog because it's required for the AbstractModal. However, the NotificationDialog disables the closing of the AbstractModal with ESC presses and outside clicks, so the onRequestClose function will never be called. 

## Steps to Reproduce

1. Implement the NotificationDialog with a onRequestClose prop.
2. Frustrate yourself trying to get that function to execute.

## Expected Behavior

Consumers should be able to instantiate a NotificationDialog without having to provide a onRequestClose prop.

## Possible Solution
The NotificationDialog could remove onRequestClose from it's API altogether and provide a no-op function to its AbstractModal implementation directly. I think there is still value in keeping onRequestClose required in the AbstractModal because it actually will be required for the majority of use cases. For the NotificationDialog specifically, we should protect its consumers from having to write dead, untestable code.

**Comment by noahbenham** [comment]
I was just about to log this, thanks for creating it @tbiethman.
