### ISSUE TITLE
Correct MenuItem management in NavigationSideMenu

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#265]
# Bug Report

## Description
There are 2 separate issues to be addressed:
1. The shapes required for the menuItems prop accept an `id` value that is supposed to be added to the MenuItem markup as an actual `id` attribute. However, that is not occurring.
2. The data-menu-item attribute added to MenuItems currently has a value based on the MenuItem's text. However, this value may be an internationalized string and is non-deterministic, making it difficult to use for selector queries. We need to use the MenuItem's `key` value instead of `text` for that attribute value.

## Additional Context / Screenshots

* Location of `id` in shape: https://github.com/cerner/terra-framework/blob/79b795cdbcab1211b5dc09f653d3af48d3106e41/packages/terra-navigation-side-menu/src/NavigationSideMenu.jsx#L40
* Location of data-menu-item: https://github.com/cerner/terra-framework/blob/79b795cdbcab1211b5dc09f653d3af48d3106e41/packages/terra-navigation-side-menu/src/NavigationSideMenu.jsx#L170

## Expected Behavior
* `id` attribute is appropriately added to the MenuItem markup
* `data-menu-item` has `key` based value.

## Environment

* Component Name and Version: All
* Browser Name and Version: All
* Node/npm Version: [e.g. Node 8/npm 5] All
* Webpack Version: All 
* Operating System and version (desktop or mobile): All

**Comment by ShettyAkarsh** [comment]
The issue 1 mentioned above is working correctly. we are setting the id attribute value of Menuitem in BuildListItem function of NavigationSideMenu.jsx.

**Comment by tbiethman** [comment]
This was fixed by #407
