### ISSUE TITLE
Create Component to Embed External React Apps

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-framework#27]
# Issue Description
We need the ability to mount external react applications into the DOM. This enables us to combine apps through configuration rather than maintaining a massive webpack instance with dynamic imports that must be updated with each app update. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The component would be consumed like this:
```js
import React, { Component } from 'react';
import EmbeddedComponent from './EmbeddedComponent';

import './App.css';

class App extends Component {
  render() {
    const loading=<div>Loading, please wait</div>;

    return (
      <div className="App">
        <EmbeddedComponent basePath="http://externaldomain.com/myApp" placeholder={loading}/>
      </div>
    );
  }
}

export default App;
```

The `basePath` will point to a base location which is expected to have a file `manifest.json`. The manifest is generated using the [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin). Example manifest:
```json
{
  "ar-intl-local.js": "ar-intl-local.8b89e84b9dd407d27826.js",
  "ar-translations.js": "ar-translations.cdad6be775ddcb106b6c.js",
  "de-intl-local.js": "de-intl-local.e7014c301a02e34b135e.js",
  "de-translations.js": "de-translations.3e802213adb19ffad47f.js",
  "en-GB-intl-local.js": "en-GB-intl-local.466fe7ba468e71f59d48.js",
  "en-GB-translations.js": "en-GB-translations.8d392998b43336e205cf.js",
  "en-US-intl-local.js": "en-US-intl-local.329870131ef92acef02d.js",
  "en-US-translations.js": "en-US-translations.e86978e4d3f21af705c6.js",
  "en-intl-local.js": "en-intl-local.a2db357afa1f66cd3e9e.js",
  "en-translations.js": "en-translations.3b5203d3ff7000964dd2.js",
  "es-ES-intl-local.js": "es-ES-intl-local.50de76237c5b4ea61995.js",
  "es-ES-translations.js": "es-ES-translations.f77d13737c97e31e41da.js",
  "es-US-intl-local.js": "es-US-intl-local.99cbfee4baa20a778e8b.js",
  "es-US-translations.js": "es-US-translations.8d7f66af308b5d2bc5f1.js",
  "es-intl-local.js": "es-intl-local.e002521d76f8191b6b6c.js",
  "es-translations.js": "es-translations.1125a13e088d93527c05.js",
  "fi-FI-intl-local.js": "fi-FI-intl-local.49a9e7ec1da28b3c443e.js",
  "fi-FI-translations.js": "fi-FI-translations.27ac26a371caa681a6a3.js",
  "fr-FR-intl-local.js": "fr-FR-intl-local.c64e61ee5807e87d3309.js",
  "fr-FR-translations.js": "fr-FR-translations.65b2b276063a727981d9.js",
  "fr-intl-local.js": "fr-intl-local.190dc3a90deec3cafcaf.js",
  "fr-translations.js": "fr-translations.0b94599fef74b963a5b3.js",
  "index.css": "index-da3a61b0d0e7609c1b9a.css",
  "index.js": "index.cfbaa75b1d994643bd89.js",
  "intl-polyfill.js": "intl-polyfill.aa6e4001a389d6d438cb.js",
  "pt-BR-intl-local.js": "pt-BR-intl-local.97fe4cdd9f05e789ad35.js",
  "pt-BR-translations.js": "pt-BR-translations.013c4d5364d85ecbb227.js",
  "pt-intl-local.js": "pt-intl-local.3dc1794a6f0f1fc5d5fd.js",
  "pt-translations.js": "pt-translations.aa67b5f1751eb0eeaba8.js"
}
```

 Upon loading the manifest, the component will download each CSS file and require the index.js file as an [AMD module](https://webpack.js.org/api/module-methods/#amd). AMD was chosen because it works cross browser and is supported by webpack. Once `index.js` and css is loaded, the component is mounted and any props passed into `<EmbeddedComponent>` are passed into the mounted external component.

In order make a react app embeddable, it simply needs to define its output in its `webpack.config.js` to be an AMD target and include the manifest plugin:

```js
  output: {
    filename: '[name].[chunkhash].js',
    path: path.join(__dirname, 'dist'),
    publicPath: 'http://externaldomain.com/myApp',
    libraryTarget: 'amd',
    libraryExport: 'default',
  }
```

Once mounted, the EmbeddedApp is part of the react DOM tree and will propagate up errors, events as any normal react component.

### Preloading
It's possible that this component could also expose a library to preload assets so that when they are requested for mounting the component will be mounted instantly without waiting for JS/CSS to load.

## Limitations
* A react 15x app cannot be mounted into a react 16x app.
* The manifest.json response must enable `access-control-allow-origin: *` to be loaded in.

**Comment by mjhenkes** [comment]
I have a couple of concerns about this component. 
I’m worried about our ability to support this component and providing it as a core component to our consumers. To me it looks like cutting edge tech that requires a deep understanding for consumers to know what they’re getting into. 

My recommendation is to move this component to terra-consumer until it matures and reaches broad adoption, then we can reconsider adding it into core terra.

**Comment by bjankord** [comment]
I'm concerned as well about our ability to support this component. I think it is going beyond the scope of a UI component with its ability to load modules client-side and requiring changes to the `Access-Control-Allow-Origin` response header. We typically try to keep what is in the terra-ui ecosystem scoped to UI components, but we do have some stuff like terra-toolkit that goes beyond that. I would recommend moving this to terra-consumer or spinning up a new project for this functionality.

**Comment by mhemesath** [comment]
Noted. Although I will say this is much simpler than XFC which has react counterpart already present in the terra ecosystem.
