### ISSUE TITLE
Side navigation is not closeable by selecting utility menu items (mobile).

### ISSUE THREAD

**Issue by KevinJJackson** [cerner/terra-framework#274]
# Bug Report

## Description
Currently, application-layout injects props into child components to provide access to key features such as checking if the side-nav is open and an event to manually close it. The utility-menu cannot get access to these props and therefore cannot manipulate the side-nav if needed.

## Additional Context / Screenshots
In the .gif below, after selecting a leaf menu item the user then has to close the navigation manually to see the new content.
![current utility menu behavior](https://user-images.githubusercontent.com/30411845/45825767-00a01000-bcc1-11e8-8ebb-9060d5a52cdc.gif)

## Expected Behavior
In mobile viewports, selecting a leaf menu item should be able to close the side navigation.

## Environment
* Component Name and Version: terra-application-layout (v. 2.13.0)
* Browser Name and Version: All
* Node/npm Version: Node 8.9.2/npm 5.7.1
* Webpack Version: 3.11.0
* Operating System and version (desktop or mobile): Mobile (all)

cc: @bjankord

**Comment by tbiethman** [comment]
This issue will be mitigated by #275. The menu will close upon presentation of the utility menu at tiny/small breakpoints.
