### ISSUE TITLE
When application layout toggle menu is opened, focus is not shifted to toggle menu

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#276]
# Bug Report

## Description
When application layout toggle menu is opened, focus is not shifted to opened toggle menu. This makes it difficult for users which are using screen readers to navigate through the menu quickly after opening the toggle menu.

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/example
2. Open toggle menu using VoiceOver or other screen reader.
3. Try to shift focus to opened menu.

## Expected Behavior
When application layout's side toggle menu is open, shift focus to first focusable element in menu or to menu container.

## Environment

* Component Name and Version: terra-application-layout

**Comment by emilyrohrbough** [comment]
We can verify the toggle menu has focus after opening the menu with webdriver's [`hasFocus() command`](http://webdriver.io/api/state/hasFocus.html). We should add this to our tests.
