### ISSUE TITLE
When application layout utility menu is opened, focus is not shifted to utility menu

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#277]
# Bug Report

## Description
When using VoiceOver, when application layout utility menu is opened, focus is not shifted to opened utility menu. This makes it difficult for users which are using screen readers to navigate through the menu quickly after opening it.

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/example
2. Open utility menu using VoiceOver or other screen reader.
3. Try to shift focus to opened menu.

## Expected Behavior
When application layout's utility menu is opened, shift focus to the utility menu.

## Environment

* Component Name and Version: terra-application-layout

**Comment by emilyrohrbough** [comment]
We can verify the utility menu has focus after opening the menu wit webdriver's [`hasFocus() command`](http://webdriver.io/api/state/hasFocus.html). We should add this to our tests.

**Comment by bjankord** [comment]
Tested with VO on iOS. 
Using the utility menu for the actual doc site, the focus is shifted to settings modal correctly.

However, in testing the utility menu in https://engineering.cerner.com/terra-framework/#/components/terra-application-layout/application-layout/example
the focus doesn't seem to shift to the utility menu modal. Need to investigate this some more.

**Comment by yuderekyu** [comment]
@bjankord hmm I'm not able to recreate this issue, are you still seeing this? Seems to be working for me on the doc site and example layout site. After selecting the utility button, pressing tab places focus on the menu header's close button

**Comment by bjankord** [comment]
@yuderekyu Yeah this looks like it is resolved.
