### ISSUE TITLE
Create Application Header Utility w/Utility Menu

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-framework#29]
# Issue Description
Create Application Utility to be placed within the terra-application-header-layout.
Component should also incorporate a Utility Menu to be displayed from the Header Utility.

## Issue Type
- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by PaulSolDev** [comment]
JIRA created

**Comment by PaulSolDev** [comment]
Keyboard navigation within the utility menu appears to function differently than the menu component.  In the menu component the up/down arrows allow transition between selectable option in the menu, in the utility menu the up/down arrow scroll the view but do not change the selected option.
