### ISSUE TITLE
[terra-application-name] App Switcher

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#294]
# Feature Request
Placeholder issue, more discussion is needed. 

OCS requests the application name to open a pop up with a list of applications, similar to how `application-utility` functions with menu items in the header. This requires not only enhancing  `application-name`, but its higher order layout components too

**Comment by neilpfeiffer** [comment]
_terra-aaplication-name_ is end-of-life will be marked as deprecated.
(replaced by _terra-application-navigation_ and a future app switching method yet to be made)

Closing as no longer needed.
