### ISSUE TITLE
terra-base devDependency clean up

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#295]
# Feature Request

## Description
We recently removed terra-base from being listed as a dependency and listed it only as a peerDependency. We missed an instance where its [listed as a devDependency in terra-disclosure-manager](https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/package.json#L26). We should remove this devDependency from terra-disclosure-manager and make terra-base a devDependency in the terra-framework root package.json file similar to what we do for react, react-dom, etc.

**Comment by bjankord** [comment]
@tatchi Yeah, we need to remove [this line here](https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/package.json#L26) and [add it below this line here](https://github.com/cerner/terra-framework/blob/master/package.json#L108).

**Comment by tatchi** [comment]
See: #296
