### ISSUE TITLE
[terra-application-utility] - OCS behaviour requests

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#302]
# Consolidate OCS behaviour requests.
* Add `pressed` state to menu items. 
* Do not render close button on header menu
* Remove custom header and use action-header *or* add margin variables to buttons
* Change [icon](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/utility/_UtilityButton.jsx#L132) next to utility button. Either:
  * Add prop to toggle between icon variants (if icon variants are static)
  * Make icon itself themeable svg

**Comment by neilpfeiffer** [comment]
[terra-application-utility] is end-of-life will be marked as deprecated.
Closing as not longer needed.
