### ISSUE TITLE
[terra-modal-manager] - Focus should be restored to original position after closing modal manager

### ISSUE THREAD

**Issue by ravikiran6565** [cerner/terra-framework#303]
# Bug Report

## Description
Focus should be restored to original position after closing modal manager. User clicks button(Click modal) to open the modal manager, once modal is opened user will close the modal manager and expect focus should retain triggered button(Click modal). 
Above scenario works fine in chrome browser but not in Firefox, safari and IE 10/11. 
Tested it in terra documentation site.
http://terra-ui.herokuapp.com/#/components/terra-modal-manager/modal-manager/example

## Steps to Reproduce
Workflow example: http://terra-ui.herokuapp.com/#/components/terra-modal-manager/modal-manager/example
Please open this URL in different browser -> Example section->Manager child -> terra-modal-manager example program.
Open any Disclose(default, tiny, small, medium, large, huge or full screen) dialog, once it opened immediately close modal and check for tabbing. 

Expected behaviour it should retain the triggered button EX: I have clicked Disclose(tiny) button and modal will open, without changing anything in Modal I will close the modal. Once it is closed successfully I will check for tabbing and I would expect it should focus on Disclose(small) button( I have opened Disclose(tiny) button once it is closed focus should be on Disclose(tiny) on pressing tab it will change its index value from Disclose(tiny) to Disclose(small)). 
Above behaviour is working in Chrome as expected but same is not working in Firefox, Safari and IE(11, 10).

**Comment by dkasper-was-taken** [comment]
After some investigation, this isn't a defect with modal manager. Focus is being set correctly to the previous element. This appears to be a visual bug within terra-button, we manage custom styles for focus and the component is unable to determine how programmatic focus should be handled. I'll log an issue to core to investigate this.

**Comment by dkasper-was-taken** [comment]
I think the difference between browsers from what I can tell is that chrome is handling the onKeyup callback differently.

**Comment by dkasper-was-taken** [comment]
Closing in favor of this issue:
https://github.com/cerner/terra-core/issues/1969
