### ISSUE TITLE
Remove routing from Application Layout component

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-framework#306]
# Feature Request

## Description

With the Application Layout component, you have to pass in a routing config for all routes included in an application. This works for most things but sometimes I have advanced use cases where I would like to control the routes myself using the react-router components or conditionally render the content in the main area of the layout (not the top nav bar or side menu). This may just be a new component to avoid a breaking change or however we want to handle it. 

In my ideal case, usage would look like this:

```js
<ApplicationLayout
  nameConfig={nameConfig}
  utilityConfig={utilityConfig}
  navigationItems={navigationItems}
  menuConfig={menuConfig}
  extensions={<ApplicationExtensions />}
>
  <Switch>
    <Redirect from='/old-path' to='/new-path'/>
    <Route path='/new-path' component={Place}/>
  </Switch>
</ApplicationLayout>
```
or
```js
<ApplicationLayout
  nameConfig={nameConfig}
  utilityConfig={utilityConfig}
  navigationItems={navigationItems}
  menuConfig={menuConfig}
  extensions={<ApplicationExtensions />}
>
  <StatusView ... />
</ApplicationLayout>
```

**Comment by slor** [comment]
I am interested in this feature so I can wrap my components that do routing with the application layout component.

**Comment by JSavage42** [comment]
I am also interested in this solution. I would like to use private routing and removing routing from Application layout would solve this issue.

**Comment by tbiethman** [comment]
I _think_ this should be achievable today by rendering a single component for all routes:
```js
const routeConfig = {
  content: {
    '/*': {
      path: '/*',
      component: {
        default: {
          componentClass: YourRoutingComponent,
        },
      },
    },
  },
};
```

But I also think it would make sense to open up the children prop for the ApplicationLayout to make this more straightforward. Children could be rendered in the content area of the layout, and if children were provided, the content segment of the routingConfig would just be ignored. That would be a passive change, though it would require changes to both the ApplicationLayout and the NavigationLayout. 

One thing that will throw a small wrench into things is the prop-injection that occurs for components rendered in the ApplicationLayout. Any children would still be provided with a `layoutConfig` prop to give components some control over the layout state. Using child components that support custom props (like the StatusView example above) would likely throw some unrecognized prop warnings. It might make sense to transition to a Context-based approach for those APIs to allow for more flexibility, but that would be a larger non-passive change.

**Comment by JSavage42** [comment]
I will add that to the list of things I'm attempting. Thank you.
