### ISSUE TITLE
[terra-navigation-side-menu] - OCS Behaviour Requests

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#307]
# Feature Request
Placeholder issue.

* Add pressed state to menu items
* Render an optional decorative icon, conditional notification icon, and optional count (badge?) component within a menu item.  HOCs consuming `terra-navigation-side-menu` would need to change their APIs to incorporate this. 
* Add css class for `background-color` on the outer [content-container](https://github.com/cerner/terra-framework/blob/master/packages/terra-navigation-side-menu/src/NavigationSideMenu.jsx#L207). 

More discussion is needed on use cases, viability, etc.

**Comment by neilpfeiffer** [comment]
_terra-navigation-side-menu_ is end-of-life will be marked as deprecated.
(replaced by terra-application-navigation and future side navigation component/s yet to be made)

Closing as no longer needed.
