### ISSUE TITLE
Fixed-Width Restriction Notification-Dialog

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-framework#341]
# Feature Request

## Description
I would like a fix width restriction of 500px on the Notification-Dialog component, possibly exposed as a prop, as per the callouts here zpl.io/aBjMZR0 .  The benefit of this is so that dialog components throughout a given app don't have different widths so they stay consistent in width throughout.

## Additional Context / Screenshots
Callouts: zpl.io/aBjMZR0

## @ Mentions
@JakeLaCombe @jordanlawrence15 @bjankord

**Comment by neilpfeiffer** [comment]
## Updated:
Changed to not be an optional prop, but sets the 500px fixed width for all notification dialogs for usages to match OCS behavior request. 

Resolved by #949
