### ISSUE TITLE
[terra-popup] On mobile - unable to click child item

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#350]
# Bug Report
On mobile form factor, we cannot click a child element within the popup examples. A console error for `preventDefault` also appears on click outside.

## Description
Console error - `Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-framework/#/components/terra-popup/popup/popup
2. Change to mobile form factor
3. Select a popup example
4. Select a list item
5. Select outside popup

## Additional Context / Screenshots
![popup-bug-gif](https://user-images.githubusercontent.com/14063284/49163785-7e048400-f2f3-11e8-9bb9-a3a5722782e8.gif)

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-framework/pull/357
