### ISSUE TITLE
Utility Menu Read Only Item

### ISSUE THREAD

**Issue by foxannefoxanne** [cerner/terra-framework#359]
# Feature Request

## Description
We have a use case where we show a correlation id in the Utility Member. This ID is used to help correlate IDs to requests for better investigation. This would typically be something that a user would highlight and copy paste. However, there does not seem to be an option to have a read-only utility item, so any attempt to highlight/copy-paste this item will count as a button click and closes the menu. A read only option would greatly assist this workflow. 

## Additional Context / Screenshots
<img width="240" alt="screen shot 2018-12-04 at 1 50 32 pm" src="https://user-images.githubusercontent.com/7482294/49468885-af85bf80-f7cb-11e8-8f9b-a2b337fd1dea.png">

## @ Mentions
Consulted with @bjankord and he recommended logging a Read Only option terra bug. He also recommended opening a modal to allow users to copy, which I will follow-up on to see if it is a viable option on our side.

**Comment by bjankord** [comment]
Looks like here is where we would want to start adding changes: https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/utility/_UtilityMenuItem.jsx

**Comment by yuderekyu** [comment]
### Potential Non Modal Solution

- Add a new prop, `isReadOnly`, to the [itemShape](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/Utils.js#L24). 
- Add corresponding prop `isReadOnly` to [`_UtilityMenuItem.jsx`](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/utility/_UtilityMenuItem.jsx).
- Inside `_UtilityMenu.jsx`'s menu item generation, conditionally check `isReadOnly` to not attach the `onChange` function to that menu item. Do this [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/utility/_UtilityMenu.jsx#L132).  
- Add an `onChange` existence check [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-utility/src/utility/_UtilityMenuItem.jsx#L104-L106). 
- Use `readOnly` prop to create read-only styles for the menu item.

We'll have to handle edge cases. One example - if someone defines a menu item containing both `isReadOnly` and `isSelectable` -  I'd vote `isReadOnly` takes precedence.
