### ISSUE TITLE
Document Skip to Content Button

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#361]
# Feature Request

The Skip to Content button was added to the application header layout, but never documented in that package. So that developers know what it does, we should mention that button in the documentation README.

**Comment by avinashg1994** [comment]
@JakeLaCombe, @bjankord, Just for clarification, do we require the documentation of "Skip to Content" button to be visible on the "Application Header Layout" description page ([here](https://engineering.cerner.com/terra-framework/#/components/terra-application-header-layout/application-header-layout/application-header-layout))?
