### ISSUE TITLE
[terra-slide-panel-manager] Slide Panel disappearing when viewport size is condensed

### ISSUE THREAD

**Issue by juliacalandro** [cerner/terra-framework#368]
# Bug Report

## Description
When I upgraded the SlidePanelManager/DisclosureManager to the new context-based implementation, I noticed that when I condense the viewport down to what seems to be a medium size, the slide panel disappears. When I expand the viewport to a larger size again, the slide panel does NOT reappear.
Before the upgrade, the slide panel would persist and would eventually take over the screen in smaller viewports. This is the behavior that we want. 
We are using the slide panel in the "squish" mode.

## Steps to Reproduce
1. Navigate to the Squish Example on the Slide Panel Manager page of the Terra UI site.
2. Just to be safe, make sure that your viewport size is at least 3/4 the length of the screen.
3. Select a "Disclose" button (in size range of tiny-huge).
4. Verify that the slide panel appears.
5. Condense the viewport of the screen until you see the slide panel disappear.
6. Expand the viewport of the screen to its original size, and verify that the slide panel does not reappear.

## Expected Behavior
I expect the slide panel to always stay visible unless it is explicitly closed or the page is refreshed.
When the viewport size is condensed, I expect the contents to the left of the slide panel to be "squished" until the viewport is at a small enough size where the slide panel takes over.
When the viewport is expanded, I expect the slide panel to eventually move back to its original position on the right-hand-side of the view and to remain visible until it is closed.

## Environment
I experience the issue in both of these browsers:
Safari - version 12.0.2
Chrome - version 70.0.3538.102

**Comment by bjankord** [comment]
Any thoughts on this one @tbiethman

**Comment by tbiethman** [comment]
http://www.nooooooooooooooo.com/

I broke it. I'll fix it. Might take me a few minutes.
