### ISSUE TITLE
Theme box-shadow for application-layout header 

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-framework#380]
# Feature Request

## Description
There is a need to add a drop shadow along the bottom of the application header. I believe that would require the ability to theme the box-shadow for the header. See screenshots for specifics

## Additional Context / Screenshots
Desired effect:
![screen shot 2018-12-10 at 2 53 35 pm](https://user-images.githubusercontent.com/1236959/49761481-d8ef9100-fc8c-11e8-82a6-e714ec9915fd.png)
Current view:
![screen shot 2018-12-10 at 2 54 48 pm](https://user-images.githubusercontent.com/1236959/49761497-ec026100-fc8c-11e8-96f1-62f3e60d07c8.png)

**Comment by tbiethman** [comment]
We're going to run into some z-index issues with the side-nav panel; it has a z-index set to 5000, and the header would need to be higher than that to render the box shadow over it. I'd have to look at the other components to see why that 5000 value was chosen.

**Comment by bjankord** [comment]
@neilpfeiffer has an update that adds in the drop-shadow in the clinical theme. This should be available once we merge in the OCS theme updates.

**Comment by neilpfeiffer** [comment]
I did also add z-index of 5001 as a quick fix to make it appear correctly over the page and menu, but per @tbiethman we should investigate further the appropriate stacking order and which #num depth we should use for the top application-header navbar and side-nav panel.

**Comment by ryanthemanuel** [comment]
@neilpfeiffer did this end up getting done with your work?
