### ISSUE TITLE
Collapsible menu focus issue

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#390]
# Bug Report

## Description
For collapsible menu view, when you enter the menu using VoiceOver, and attempt to navigate using VoiceOver commands, it says "Safari busy" and will not navigate through the list items. You can access the menu using regular keyboard nav, but focus will move off of the menu and back onto the main page while the menu is still open.

## Steps to Reproduce

1. TBD

## Additional Context / Screenshots
Identified as part of functional verification on [this PR](https://github.com/cerner/terra-core/pull/2004#issuecomment-438396868).

## Expected Behavior
* Navigating the menu using VoiceOver commands works without issue. 
* Prevent focus from moving off of the menu when using keyboard navigation

## Environment

* Component Name and Version: terra-menu
* Browser Name and Version: TBD

**Comment by ShettyAkarsh** [comment]
This is similar to issue #833. closing this as per the [comment](https://github.com/cerner/terra-framework/issues/833#issuecomment-549539562) mentioned over there.
