### ISSUE TITLE
Unexpected behavior in Time-Input onBlur event

### ISSUE THREAD

**Issue by ss037751** [cerner/terra-framework#399]
# Bug Report

## Description
I encountered two issues with the 12-hour terra-time-input component:
1. Although an onBlur event is triggered when the hours loses focus and when the minutes loses focus, no onBlur is triggered when the meridiem loses focus.
2. There is no separate event that is triggered when leaving the time-input component as a whole, only from each field within the component.
This is a problem when validation logic is performed on an onBlur event. Since the onBlur event is fired while the user is still editing the time value, the validation logic is performed too soon, causing premature errors.
 

## Steps to Reproduce
1. Focus into the time input component and enter hours. onBlur event is triggered. Enter minutes. onBlur event is triggered. Enter meridiem and remove focus from the meridiem. No onBlur event is triggered. In the example below, each onBlur event generates a printed line in the Console. No line is printed when tabbing off the meridiem.
2. Observe that the onBlur event is triggered when focus is removed from the hours or minutes but remains within the component. No onBlur event occurs when the TimeInput element as a whole loses focus.

 
## Screen recordings
1. No onBlur fired when meridiem loses focus ![onblur meridiem](https://user-images.githubusercontent.com/45665749/49821605-d488ae00-fd48-11e8-8125-521fe725d79b.gif)

2. onBlur event is fired while focus is still in component 
![onblur time component](https://user-images.githubusercontent.com/45665749/49821642-ed915f00-fd48-11e8-810b-9980c7e8da5d.gif)

## Expected Behavior
The onblur event should be triggered only when when the TimeInput as a whole loses focus.

## Possible Solution
When each individual section loses focus, that can trigger separate events, i.e. onBlurHours, onBlurMinutes, onBlurMeridiem.

**Comment by benbcai** [comment]
These issues have been resolved by #588 and #837
