### ISSUE TITLE
Terra Base Font Family is not inherited for Application Header

### ISSUE THREAD

**Issue by foxannefoxanne** [cerner/terra-framework#405]
# Bug Report

## Steps to Reproduce
1. Set specialized text using --terra-base-font-family
2. View Application Header layout text
3. See text is not set to specified language

## Additional Context / Screenshots
Incorrectly Set Text: 
<img width="682" alt="screen shot 2018-12-13 at 9 26 41 am" src="https://user-images.githubusercontent.com/7482294/49948540-48e25f00-feb9-11e8-8d62-842f14285469.png">

Correctly Set Text (side menu): 
<img width="687" alt="screen shot 2018-12-13 at 9 26 24 am" src="https://user-images.githubusercontent.com/7482294/49948559-50a20380-feb9-11e8-8287-0e476179e308.png">

## Expected Behavior
Font should be the same for all Terra Application Layout components 

## Possible Solution
In my browser, modifying the [Application Tabs scss](https://github.com/cerner/terra-framework/blob/09228b21d3db9a82d8ef292d85b57e9da02d1331/packages/terra-application-links/src/tabs/ApplicationTabs.module.scss) to include ``` font-family: inherit``` worked well for me. 

## Environment
* Component Name and Version:
* Browser Name and Version: Chrome 70.0.3538.110
* Node/npm Version: 8.4.0 for component consuming Terra Application Layout
* Webpack Version: ^3.11.0 for consuming component 
* Operating System and version (desktop or mobile): macOs High Sierra 10.13.3

**Comment by bjankord** [comment]
Talked with @foxannefoxanne about this. Since the element is a `button`, the browser adds a default font-family style it. We [normalize this default browser style in the terra-button component](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.module.scss#L32), but we also need to normalize in this component.

**Comment by neilpfeiffer** [comment]
Will be resolved by updates already made for OCS theme variables when work get merged in

https://github.com/cerner/terra-framework/blob/62a459d5b7be889ccf733b68d9b50536620a89f1/packages/terra-application-links/src/tabs/ApplicationTabs.module.scss#L86
