### ISSUE TITLE
[Terra-popup] Allow the option to click through when a popup is open.

### ISSUE THREAD

**Issue by PandaFlieg** [cerner/terra-framework#408]
# Feature Request

## Description
Currently, when a popup is open, any of the clicks outside of the popup are ignored.  This essentially means I will have to click twice if I click from a popup to something outside of the popup.
Example:
https://engineering.cerner.com/terra-framework/#/components/terra-popup/popup/popup
1) Open the default popup
2) Click the code button
3) The code isnt expanded.

## Expected Behavior
I dont think this is explicitly a bug, which is why I logged it as a feature request, as I can see the use case where this is the desired behavior (IE, if the only way of close the popup is clicking, I dont want to accidentally click something underneath because I was trying to click it.
That being said, for us, we need the click through so that we can see if the related target we are clicking into belongs to a group of elements of the html document.  Without the click through, this is always null.

## Possible Solution
This probably can be done by passing a prop for 'clickThrough' which either enables/disables the background of the popup depending on the status of the boolean.

## @ Mentions
Talked with:
@StephenEsser @mjhenkes 
Some time ago about this issue (9/27/2018), somehow got off my radar.

**Comment by ryanthemanuel** [comment]
@PandaFlieg this is the safest behavior for popups unfortunately which is why we designed it to work this way.  Closing this for now.

**Comment by PandaFlieg** [comment]
So does that mean we can't have an opt in/out of this feature?  For other use cases where it's safer to have the click through rather than the not click through?

**Comment by ryanthemanuel** [comment]
@PandaFlieg, I'd have to know more about specifics about your use case.  This is the pattern we've been going off of from UX's direction.

**Comment by PandaFlieg** [comment]
We have a use case where we have data inside of a popup and depending on where we click, we either clear the data or preserve it.
Without this change, we can't tell where we are clicking and can't make this distinction as the output is always null (resulting in a clearing of the data).

**Comment by ryanthemanuel** [comment]
@PandaFlieg, I'm not sure if you have any call outs or visuals, but I'm still having a hard time grasping what is going on here.  Do you have a UX designer you're working with?  It could be useful to hash this out in person.
