### ISSUE TITLE
Application Header components not aligned correctly

### ISSUE THREAD

**Issue by alex-bronze** [cerner/terra-framework#413]
# Bug Report

## Description
The application header contains a hamburger button (visible when the window is smaller) and the title.
- In Edge and other newer browsers, the title shows properly, left-aligned.
- In IE11, the title shows right-aligned.

## Steps to Reproduce
1. Go to the project staging URL in a new browser (Chrome, Edge, etc.)
   * This is an internal Cerner URL; not sure I can provide it here; could you please contact me directly?
1. The title is left-aligned in the header as it's supposed to.
1. Go to the same URL in IE 11. The title is right-aligned.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/46113607/50407288-3a8e2000-07a2-11e9-864b-41bf316fe54b.png)

## Expected Behavior
This is how the header looks in newer browsers.
![image](https://user-images.githubusercontent.com/46113607/50407282-2813e680-07a2-11e9-996d-c833f48dda6a.png)

## Possible Solution
I see in the debugger that the `ApplicationHeaderLayout` component uses a flexbox layout and specifies `justify-content: space-between`. When I change it in the debugger to `flex-start`, the title is aligned properly.

## Environment
* Component Name and Version: `terra-application-header-layout@2.17.0`
* Browser Name and Version: IE 11
* Node/npm Version: [e.g. Node 8/npm 5] Node 10.14.2 / NPM 6.4.1 (or many other versions)
* Webpack Version: 3.12.0
* Windows 10 (desktop)

**Comment by ryanthemanuel** [comment]
Taggins @dkasper-was-taken and @tbiethman

**Comment by nramamurth** [comment]
> This is an internal Cerner URL; not sure I can provide it here; could you please contact me directly?

@alex-bronze I am trying to reproduce the issue in-house and I'd like to see the behaviour on your side. Could you please send the URL to naveenkumar.ramamurthy@cerner.com? Also, how are you setting the title while creating the `ApplicationHeaderLayout` component?

**Comment by nramamurth** [comment]
**Investigation Notes:** 

I used the [sample ApplicationLayout component](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-layout/src/terra-dev-site/test/application-layout/ApplicationLayoutNoTopNav.test.jsx) to reproduce the issue without Extensions, Utilities and Navigation on IE 11 on Windows 10. I could not reproduce the issue (_screen recording attached_) and I need more information from @alex-bronze regarding how the component is laid out on consumers' side. 

**Environment**

- Component Name and Version: terra-application-header-layout (2.17.0 and 3.2.0), terra-application-layout@2.18.0
- Browser Name and Version: IE 11
- Node/npm Version: Nodejs v8.15.1/ npm v6.4.1
- Windows 10 (Desktop).

**Comment by nramamurth** [comment]
@alex-bronze Thank you for the offline update. I am now able to reproduce the issue with terra-application-layout@4.5.0 and terra-application-header-layout@3.2.0, I shall look into it further.

**Comment by nramamurth** [comment]
**Update -** this issue has started to occur after the introduction of 'Skip to content' button as a sibling to the Logo in `application-header-layout@2.18.0`. The example below illustrates the issue that happens in IE 11, I am working with @neilpfeiffer to find out the root cause of the problem. 

https://www.w3schools.com/code/tryit.asp?filename=G205DQR6M3SB

**Comment by neilpfeiffer** [comment]
Upon further review -- it appears that `justify-content: space-between;` is not at all needed for the `fill` class, or elements that is has been applied to.

So unless it was needed for a specific reason and by removing it solves for the layout bug with IE11 -- suggestion is to remove line 9: [/src/ApplicationHeaderLayout.module.scss#L9](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-header-layout/src/ApplicationHeaderLayout.module.scss#L9).

**Comment by nramamurth** [comment]
That is correct. Like you mentioned offline, 

> the `justify-content` property is meant to position the child elements (that are the _logo_ and the _skip to content_ elements in this particular case), but none of the child elements of the `header-layout` do we even want positioned that way (they all have their own internal positioning or sizing as needed now). 

I was able to confirm that this does fix the original issue without introducing any negative effect. I haven't written an explicit WDIO spec to test this in IE11 but I have the screenshots below. 

**Without Fix:**

<img width="1282" alt="Screen Shot 2019-03-21 at 2 15 33 PM" src="https://user-images.githubusercontent.com/10090859/54742613-ebf8f200-4be7-11e9-9eb4-019cdd6cfa0a.png">
 
**With Fix:**

<img width="1289" alt="Screen Shot 2019-03-21 at 2 15 59 PM" src="https://user-images.githubusercontent.com/10090859/54742622-f1563c80-4be7-11e9-9d70-5231f10a85b0.png">

**Comment by SushmithaBN** [comment]
Application Header components not aligned correctly issue still persists after the new release(version- 4.8.0), I logged another issue https://github.com/cerner/terra-framework/issues/593
