### ISSUE TITLE
Theme LayoutSlidePanel border width.

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-framework#416]
# Feature Request
Need the ability to theme the layout slide panel border to be 0. 

## Description
Ability to theme the border-width property here: https://github.com/cerner/terra-framework/blob/5a4ffb0cc6311ffc7f27ee420071b8bfa343ec68/packages/terra-layout/src/LayoutSlidePanel.module.scss#L61

## Additional Context / Screenshots
See the border on the right of the selected nav item. The border color is themed to `transparent` which shows the slide panel background color.

![screen shot 2019-01-02 at 1 36 40 pm](https://user-images.githubusercontent.com/225765/50608848-78223580-0e93-11e9-8f7f-53ce494c7293.png)

**Comment by bjankord** [comment]
@mhemesath This will be resolved with the OCS variable update. We should have a release cut on this soon.
