### ISSUE TITLE
popUp wiki entry contains broken links

### ISSUE THREAD

**Issue by chriskonopka** [cerner/terra-framework#428]
# Bug Report

## Description

On the following page 
https://engineering.cerner.com/terra-ui/#/components/terra-popup/popup/popup
there is a section that contains links to an App delegate page. However clicking on said links results in a 404 error 

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-popup/popup/popup
2. find the Rendering a popup inside a modal section
3. click on the blue hyperlinked text "App delegate"

## Expected Behavior

the link should direct to a page describing the app deligate

## Possible Solution

update the embedded hyperlink

## Environment

* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Mac OS

**Comment by yuderekyu** [comment]
AppDelegate is now deprecated. We should update the documentation to reflect the DisclosureManager's context API instead. Logged https://github.com/cerner/terra-framework/issues/438
