### ISSUE TITLE
Modals created with Modal Manager need onClose property

### ISSUE THREAD

**Issue by danplubell** [cerner/terra-framework#43]
# Issue Description

We need an onClose on modals that are managed by the Modal Manager.  When a modal is closed or canceled the application needs a hook to execute any actions that are needed if the modal is canceled.  The current implementation works ok if a Cancel button is provided and the user presses the cancel button.  But, if the user closes by using the ESC key there isn't a way to dispatch any actions that are needed.
## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

An example is changes to redux state that we need to dispatch on cancel of a model.  If the user presses the Cancel button we can dispatch the appropriate action.  
The expectation is that the same action can be dispatched when the user cancels the model with the ESC key.

## Current Behavior

Currently, if the user uses the ESC key the application state is left is not is the appropriate state because the "cancel" action wasn't dispatched.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by alecrowen** [comment]
completed with aggregator work.

**Comment by emilyrohrbough** [comment]
[Terra-Aggregator docs](https://github.com/cerner/terra-framework/tree/master/packages/terra-aggregator/docs)
