### ISSUE TITLE
[terra-application-links] tab and menu updates

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#431]
## Enhancements

Requested updates:
- Primary navigation tabs currently have a fixed width, would be ideal for each tab to be able to dynamically flex in width based on label length, between a minimum and maximum width value, and still apply truncation after full container starts losing available space and tabs need to flex smaller.
- Update the menu/overflow portion of primary navigation (the last tab) to change the selection visuals to not use the left-border & background treatment to show selection, but checkmark for the selected item similar to terra-menu.

**Comment by ryanthemanuel** [comment]
@dkasper-was-taken and @tbiethman can you take a look at this one?

**Comment by neilpfeiffer** [comment]
(terra-application-links_ is end-of-life will be marked as deprecated.
(replaced by _terra-application-navigation_)

Closing as Resolved by enhancements made to the new primary navigation tabs in #445.
