### ISSUE TITLE
[terra-navigation-side-menu] minor style/theme refactoring

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#432]
## Enhancements

Possible items to look at:
- Explore refactoring styles for selected item to switch from border-left with different padding than unselected items, to inset box-shadow and other visual options showing selection that is better for other themes
- Explore refactoring for theming that uses transparency so each item can have subtle background color for each state, pull fill the empty space below with an empty item that also has similar visual style applied

**Comment by ryanthemanuel** [comment]
@dkasper-was-taken and @tbiethman can you take a look at this one?

**Comment by neilpfeiffer** [comment]
_terra-navigation-side-menu_ is end-of-life will be marked as deprecated.
(replaced by terra-application-navigation and future side navigation component/s yet to be made)

Closing as no longer needed.
