### ISSUE TITLE
[terra-application-utility] minor layout updates

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#433]
## Enhancements:

Requested updates to the layout: 

#### Header Utility Button/Target
-  Add an additional inner span around the photo/avatar+name+chevron so that it can receive a hover and focus treatment that is inset from the full button block shape that fills the top to bottom vertical "tab" placement in the application-header
- Make the down-arrow icon themeable and replace min-width with actual size and margins-left and right, swap for alternate dots icon when no username or userphoto provided.

#### In the Utility Menu
- Long names doesn't look to be handled for inside the menu version, which should either wrap or truncate.
- Replace top header with action-header for consistency if possible, should grow in height if text wraps more than one line
- Dividers could be refactored and done differently
- Allow footer to grow in height based on content and if text needs to wrap

**Comment by ryanthemanuel** [comment]
@dkasper-was-taken and @tbiethman  can you take a look at this one?

**Comment by neilpfeiffer** [comment]
[terra-application-utility] is end-of-life will be marked as deprecated.
Closing as not longer needed.
