### ISSUE TITLE
Application Navigation Enhancements

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#445]
# Feature Request

## Description

The ApplicationLayout was terra-framework's first attempt at creating a reusable application navigation system. As discussions with our UX partners have progressed, and as enhancement requests have come in from our consumers, we have realized that larger changes need to be made to support future designs and make the components easier to consume.

#### Decoupled Routing
The ApplicationLayout and NavigationLayout today operate under the assumption that react-router is being used. We would like to decouple the usage of client-side routing from the UI of navigation altogether. However, we would also like to build routing helpers/wrappers that will (optionally) provide similar functionality to the existing ApplicationLayout. (Related #244, #306)

#### Decoupled Side Navigation
Side navigation will be removed from the application layout altogether. We will provide side navigation with a separate component that can be dropped into the application layout (or not, if a different navigation design is desired).

#### Navigation State Management
As a result of the routing decoupling, the application layout will expose a callback prop for navigation item selections and a prop that indicates which navigation item should be rendered as selected. (Related #322)

#### Application Header Responsive Patterns
At larger breakpoints, the application layout will behave as it does today. However, at smaller breakpoints, the following changes will be made:
* Extensions/Utilities will still be accessible from the header. Responsive patterns for those individual pieces are still being discussed.
* The navigation tabs will continue to be rendered in the toggle-able menu. However, they will be the only things in that menu. If no application tabs are provided to the application layout, then the menu will not exist.

#### Package Consolidation

The components that make up the terra-application-layout are currently separated into a number of packages. We would like to consolidate those packages to make consumption more straightforward and more clearly communicate our intended usage of those components. The following changes have been proposed:

|Package Name|Status|Description|
|---|---|---|
|`terra-application-navigation`|New|A replacement package for terra-application-layout containing the desired API and behavior changes.|
|`terra-side-navigation`|New|A new package with a component that provides a responsive side-navigation component.|
|`terra-application-base`|New|A new package with a component that provides a baseline of features/dependencies for application development (terra-base, modal manager, active breakpoint provider, theme provider, etc.|
|`terra-application-links`|**Deprecated**|All relevant logic will be moved into `terra-application-navigation`.|
|`terra-application-header-layout`|**Deprecated**|All relevant logic will be moved into `terra-application-navigation`.|
|`terra-application-menu-layout`|**Deprecated**|All relevant logic will be moved into `terra-application-navigation`.|
|`terra-application-name`|**Deprecated**|All relevant logic will be moved into `terra-application-navigation`.|
|`terra-application-utility`|**Deprecated**|All relevant logic will be moved into `terra-application-navigation`.|
|`terra-navigation-side-menu`|**Deprecated**|All relevant logic will be moved into `terra-side-navigation`.|
|`terra-application-layout`|Unchanged|This package will remain as is and will not see any enhancements.|
|`terra-navigation-layout`|Unchanged|This package will remain as is and will not see any enhancements.|
|`terra-layout`|Unchanged|This package will remain as is and will not see any enhancements.|

#### Existing Issues

These are the current navigation issues that will be corrected or rendered moot by the desired changes:
* #432 [terra-navigation-side-menu] minor style/theme refactoring
* #431 [terra-application-links] tab and menu updates
* #272 Terra Utility Menu needs to have the option to switch it's role.
* #270 Add wrapperClass prop to terra-navigation-layout configuration
* #267 Add appropriate roles to terra framework components for Accessibility
* #306 Remove routing from Application Layout component
* #124 Add ability to render layout at full page height
* #244 Better support for 404 pages in application layout
* #255 Side Menu loses focus after navigating links with keyboard
* #322 Make Navigation Items in top level navigation selectable when on page

These are the current navigation issues that need further design input:
* #409 Add support for ability to add icons top navigation
* #307 [terra-navigation-side-menu] - OCS Behaviour Requests
* #268 Add an accessibility toolbar for the application layout
* #50 [Framework] Navigation on mobile needs to allow the user to abort and return to their previous base screen
* #48 [Framework] Breadcrumb back-style navigation pattern needs to be built into a mobile header component

#### Guides and Education
Thorough guides and examples will need to be created to help consumers of the ApplicationLayout to transition from the ApplicationLayout to the new components.

**Comment by nickpith** [comment]
> * The navigation tabs will continue to be rendered in the toggle-able menu. However, they will be the only things in that menu. If no application tabs are provided to the application layout, then the menu will not exist.

@tbiethman I have a question about this one. What will the responsive UX be if the side-navigation exists for a page if it won't be in the toggle-able menu?

**Comment by tbiethman** [comment]
@nickpith Toggling the presentation of side navigation in small viewports would have to occur outside of the application header. Conversations with UX about this are ongoing, but at this point I can't speak with any authority about what this will end up looking like.

**Comment by tbiethman** [comment]
Little update:

#695 will result in the creation of the `terra-application-navigation` package.
#678 will result in the creation of the `terra-application` package (referred to above as `terra-application-base`)

Options for side navigation concepts are still being explored. I will update this issue (or log a separate one) when development work starts up in earnest.
