### ISSUE TITLE
[terra-collapsible-view] import new terra-form-checkbox

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#451]
# Feature Request

## Description
- Uplift the collapsible menu view to import the new terra-form-checkbox (currently uses old terra-form/lib/control, which is unthemeable). 
- Checkbox may need enhancement to have non-padded/margin option (needs investigation) #2197 
- will be major version bump

**Comment by nramamurth** [comment]
As discussed offline with @neilpfeiffer - since it is recommended to work on this after https://github.com/cerner/terra-core/issues/2197 is wrapped up, I shall hold on starting the development for now.

**Comment by mjhenkes** [comment]
@ryanthemanuel can we prioritize this issue? 

This will cause this error for everyone using terra-dev-site
```
WARNING in terra-base
  Multiple versions of terra-base found:
    3.33.2 ./~/terra-form/~/terra-base
    5.6.0 ./~/terra-base
```
It looks pretty bad that we're still pulling in a version of terra-base 2 major versions behind.

**Comment by neilpfeiffer** [comment]
We'll get the tech design for [#2197](https://github.com/cerner/terra-core/issues/2197) started so we can roll out a new standalone checkbox and unblock @Naveen to complete this issue.

**Comment by ryanthemanuel** [comment]
@neilpfeiffer if we can make progress on this (even if we need to custom style the checkbox within the collapsible menu view) that would be my preference.  We can then replace it once #2197 is done
