### ISSUE TITLE
[DateTimePicker] throws NPE if manually entered valid date is outside range of allotted dates

### ISSUE THREAD

**Issue by Jmacek** [cerner/terra-framework#452]
# Bug Report

## Description
If you manually enter a _valid_ date into the `Date` field that is outside the range allowed by a `minDate`, `maxDate` or any other type of date filtering then enter a time; an exception is thrown when attempting to format the time into the existing date. (which is because the existing date, while valid, does not exist due to it being outside the allotted dates)

## Steps to Reproduce

1. Navigate to the [`terra-date-picker component` page](https://engineering.cerner.com/terra-ui/#/components/terra-date-time-picker/date-time-picker/date-time-picker)
2. Open browser `dev tools` and navigate to console
3. Scroll down to an example that filters specific dates (I used `Min Max Selection Options`)
4. Manually enter a `date` outside the allotted dates (I used `11/11/1999`)
5. Enter a `time`
6. See console output `Uncaught TypeError: Cannot read property 'format' of null`

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/8560946/49183429-7d371680-f322-11e8-86b5-22b49f26a1a8.png)

Null field is [`updatedDateTime`](https://github.com/cerner/terra-core/blob/master/packages/terra-date-time-picker/src/DateTimePicker.jsx#L245)

## Expected Behavior
Should not throw NPE.

## Possible Solution
Preferred: Add condition to `isValidDate` to ensure date is within the bounds of the allotted dates.
Quick and dirty: Check for null before using `updatedDateTime` 

## Environment

* Component Name and Version: terra-date-time-picker ^2.36.0
* Browser Name and Version: Chrome
* Node/npm Version: v10.13.0/6.4.1
* Operating System and version (desktop or mobile): Desktop OS X High Sierra 10.13.6

## @ Mentions
I brought up the issue to @benbcai

**Comment by ryanthemanuel** [comment]
Closed with https://github.com/cerner/terra-framework/pull/503
