### ISSUE TITLE
Allow consumer to specify timezone used by the DateTimePicker

### ISSUE THREAD

**Issue by RHolland13** [cerner/terra-framework#457]
# Feature Request

## Description

Currently, the `DateTimePicker` uses the system timezone as seen by the user's browser to control DST related functionality, and to determine the ISO value of the component.  We would like to have the ability to specify a timezone to use instead of the browser's timezone.  This can be an optional property, allowing for fallback to the current behavior if no timezone is provided, which would allow this to be a passive change.

## Additional Context / Screenshots

The user could be using a device in one timezone (or have their device configured for a particular timezone), while needing to enter data about something occurring in another timezone.  This is especially apparent when the two timezones have different treatment of DST (the transition might take place on a different date, with a different sized shift, or not at all), but applies for all situations where the timezones have different offsets, as it affects the ISO value of the component.

**Comment by benbcai** [comment]
@RHolland13 Do you expect that the date-time-picker component provides some kinds of visual component for the end user to select the timezone or are you requesting that date-time-picker just provides a new prop for consuming applications to set the timezone?

**Comment by RHolland13** [comment]
@benbcai, for our use we are wanting to be able to pass in a prop to specify which timezone to use.

**Comment by benbcai** [comment]
## Design

### terra-date-time-picker

- Add a new prop named `timeZone`. If the `timeZone` prop is provided, set this timezone for moment to use by calling `moment.tz.setDefault()` in the constructor.

For example:
`moment.tz.setDefault("America/New_York")`

- See [default-timezone](https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/) for details. If the provided timezone is an invalid timezone or not supported by moment, calling setDefault should just be a no-op. 

- Moment objects created before setting the timezone are not affected so it is important to ensure that existing moment objects are updated should the `timezone` prop changes on re-renders. 

- terra-date-picker does not need this prop since it doesn't involve the time element.

**Comment by RHolland13** [comment]
Perhaps I wasn't clear in the original request, but we need the ability to handle several dates, some of which need to be in one timezone, while others might be in another timezone.  Meaning that we will have multiple instances of the terra-date-time-picker on the page with different `timeZone` props.  Setting the default timezone for moment would cause the different instances to fight with each other over what the default timezone should be (as well as breaking anything else on the page that uses moment and expects the default timezone to remain unchanged).

I think that replacing all calls to `moment(...)` with with `moment.tz(..., timeZone)`, using the provided `timeZone` prop, should remove the dependency of the terra-date-time-picker on the current default timezone, and allow multiple components to be present on the page using different timezones without interfering with each other.

**Comment by benbcai** [comment]
@RHolland13 Thanks for the clarification on your use case. Yes, it makes sense to use the provided timezone to determine the date/time value to prevent interfering with other instances.

**Comment by lokesh-0813** [comment]
@benbcai I am not sure  of what I have done to set the default timezone is right [here](https://github.com/cerner/terra-framework/pull/1044/files#diff-0a8a568512ba2dc166f3b71e47749752R246) .

I am doubtful and I was thinking you could take a look and provide a better design approach ?

I have tried something like
```
const momentDate = moment(date).tz(timeZone).format();
```

It fails. And I couldn't figure out why exactly the above line was failing.

Also I am thinking `setDefualt` would modify the global object for the browser's moment instance ? And probably is not a right thing to do ? I could be wrong here.

I have created a draft [PR](https://github.com/cerner/terra-framework/pull/1044)

Let me know your thoughts.

**Comment by benbcai** [comment]
@lokesh-0813 Given the last update that consumes will render many date-time-pickers components and each once has the potential to be on a different timezone, we would need to use `moment.tz(date, timezone).utc().format()` to get the formatted date/time display. 

What issues are you see when you used `moment(date).tz(timeZone).format();`?

Note that there is a big difference between `moment(date).tz(timeZone)` and `moment.tz(date, timeZone)`. Take a look at this [documentation](https://momentjs.com/timezone/docs/#/using-timezones/).
