### ISSUE TITLE
DateTime and Timezone fields misalignment

### ISSUE THREAD

**Issue by Nahusha-MS** [cerner/terra-framework#461]
# Bug Report

## Description

When we set the date time to ambiguous DST Fall Time and select pre or post DST option, we get timezone field. This field is misaligned with Date/Time input fields
## Steps to Reproduce

1. Open DateTime picker and select 11/04/2018 01:52 . 
2. We get a popup asking for standard or daylight time. Select any option
3. We get a timezone field next to time input.

## Additional Context / Screenshots

![screenshot-6 1](https://user-images.githubusercontent.com/41947815/44445611-3fc63d00-a5ff-11e8-8a04-092e2904fe0c.png)

**Comment by benbcai** [comment]
This issue was fixed when we worked on the clinical theme project. This is how it looks now in the dev site.

![screen shot 2019-02-20 at 2 31 58 pm](https://user-images.githubusercontent.com/22618655/53122669-c4493800-351c-11e9-8870-cb727a2759c1.png)
