### ISSUE TITLE
Datepicker is opening on any key press

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#466]
# Bug Report

## Description
The Datepicker is opening when keys other than space and enter are pressed. For our requirements, only enter and space should open the datepicker.

## Steps to Reproduce
1. Click on one of the datepickers
2. Press Tab
3. Press E

## Additional Context / Screenshots
Datepicker is opening on any key press

## Expected Behavior
The datepicker does not open

## Possible Solution
Our onKeyDown event can be modified so that we only trigger onKeyDown when those keys are pressed. However, this can potentially block any teams that require their own specific onKeyDown functionality.

## Environment
* Component Name and Version: terra-date-picker - current version
* Browser Name and Version: All
* Node/npm Version: current
* Webpack Version: current
* Operating System and version (desktop or mobile): Desktop

**Comment by bjankord** [comment]
This has been resolved, but I don't recall which PR we resolved it in. This can be tested by navigating to https://engineering.cerner.com/terra-ui/components/terra-date-picker/date-picker/date-picker and completing the following steps:

* Click on one of the date pickers
* Press Tab
* Press E
