### ISSUE TITLE
[Framework] Navigation containers to be able to string together

### ISSUE THREAD

**Issue by amberwilks** [cerner/terra-framework#47]
# Issue Description
The responsive pattern of the navigation containers should be able to string together with drill-in functionality.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [x] Usability Concern
- [ ] Bug
- [ ] Other

## Expected Behavior
The user should be able to drill-in through multiple levels of navigation

## Current Behavior
Not all levels of navigation string together.

**Comment by mjhenkes** [comment]
We believe the application-layout already supports this behavior. The user can drill in through multiple levels of navigation as can be seen in the gif below. From the home page, to the component page, to the modal manager components. Further disclosures are supported with the various disclosure managers.

![screen recording 2018-06-28 at 03 31 pm](https://user-images.githubusercontent.com/1588747/42059208-4b5c6208-7ae8-11e8-9b7e-262968886135.gif)

**Comment by sethbroox** [comment]
Based off of my understanding of how this was explained, the current implementation satisfies the need requested.
