### ISSUE TITLE
Left and right arrow keys do not work for navigation between menu and submenus when using JAWS.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#472]
# Bug Report

## Description
Left and right arrow keys do not work for navigation between menu and submenus when using JAWS.

## Steps to Reproduce

1. TBD

## Additional Context / Screenshots
Identified as part of functional verification on [this PR](https://github.com/cerner/terra-core/pull/2004#issuecomment-438396868).

## Expected Behavior
Left and right arrow keys work for navigation between menu and submenus when using JAWS

## Environment

* Component Name and Version: terra-menu
* Browser Name and Version: IE 11 + JAWS

**Comment by ShettyAkarsh** [comment]
> This issue in Jaws is due to its default behavior of right and left arrow keys. In jaws while reading text left and right arrow keys are meant for reading next and previous characters hence the navigation to sub menu is not happening on right and left arrow key press. Fixing this issue will change the JAWS default behavior of right and left arrow keys for menu.
> However Navigation on menu can be done through other keys as well like Space and Enter Keys. I would like to know if we can keep this issue as exception for JAWS since it's expected behavior of JAWS or do we need to proceed with fixing the issue.

@bjankord , @neilpfeiffer  please share your thoughts on this. so that we can proceed.

**Comment by bjankord** [comment]
My thoughts are let's close this issue. My understanding of JAWS has grown since logging this issue and now I understand that JAWS has special treatment for arrow keys. I don't think we should try to override that behavior. I also agree that since users can navigate to options using other keys, this seems fine to close.

**Comment by ryanthemanuel** [comment]
Closing this with respect to brett's comments
