### ISSUE TITLE
Menu - Ability to define content attachment 

### ISSUE THREAD

**Issue by ChelseaRyanAnderson** [cerner/terra-framework#473]
# Feature Request

## Description
Like the popup, it would be nice to choose where the menu is attached, at least left or right. Since we aren't using the arrow, it would be nice if all the text could align (as closely as possible) on the left.

## Additional Context / Screenshots
current:
![image](https://user-images.githubusercontent.com/35141408/46420157-05b78300-c6f5-11e8-9f63-0c908f7c867f.png)

desired:
![image](https://user-images.githubusercontent.com/35141408/46420566-f5ec6e80-c6f5-11e8-8bbb-96a46eb11218.png)

I've discussed this and potential work arounds with @neilpfeiffer

**Comment by neilpfeiffer** [comment]
If anyone is looking to still looking for a method to implement this request -- it's actually possible with current API without needing any additional enhancement if the menu is on the left side of the screen (or) on the left side within a larger parent/page container.  If the unit is on the left side of a larger parent container on the page (needs to a be a page frame or panel, a toolbar would be too small), by using the `boundingRef` prop and giving it the `ref` of the larger page/panel container will automatically act as a border/edge forcing the menu to the right side of the target button, similar to how the edge of the screen (screen = `document.window` if no value is provided to the `boundingRef` prop) will naturally cause the menu to push to the right when the target button is all the way on the left side of the app on a device screen or application edge.

I am closing this issue, as is hasn't received any interest from the initial request, and is pseudo-achievable by the methods mentioned above. 

cc: @ryanthemanuel @mjhenkes @tbiethman
