### ISSUE TITLE
[terra-tabs] additional style 

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#480]
## Enhancement
Adding additional features detailed here https://zpl.io/2y1JrGq
- modular style of tabs
- center aligned modular tabs

**Comment by nramamurth** [comment]
@ryanthemanuel @jmsv6d @neilpfeiffer 

Is this issue still valid? Aren't we going to _not_ support Modular Tabs and remove the dead code from `terra-tabs`?
