### ISSUE TITLE
Allow Tabs to display inline when placed in smaller containers

### ISSUE THREAD

**Issue by ruthvikgopidi** [cerner/terra-framework#484]
# Bug Report

## Description
terra-tabs gives drop-down list when the component is placed in small containers.

>
## Additional Context / Screenshots
![tabsbug](https://user-images.githubusercontent.com/17086836/44231431-c42e4100-a163-11e8-9c4d-e5b5cddd3635.PNG)

## Expected Behavior
 Tabs appear inline instead of drop down list
## Possible Solution
The Tabs uses Responsive Element component which has responsiveTo props which default value is set to 'parent' changing it window would solve the issue. 
## Environment

* Component Name and Version: terra-tabs v3.16.0
* Browser Name and Version: Internet Explorer v11.1206.15063.0
* Node/npm Version: npm v5.7
* Webpack Version: v3.6.0
* Operating System and version (desktop or mobile): windows 10 Enterprise v1703

**Comment by nramamurth** [comment]
@neilpfeiffer 

> if a user sets it to none, that means it will never collapse into the menu - which should only be reserved for situations like icon only tabs, or when consumer is in full control and has been tested where they will always fit face-up (including all i18n) in all possible container/window sizes.

Are we looking for this behavior ⬇️ or do we want to avoid even showing the "More.." when there is no space assuming that the consumers **_for sure_** use this setting **_only_** when all the tabs fit in even in the smallest viewport? 

![tabs-menu-responsive-none](https://user-images.githubusercontent.com/10090859/67852799-1a05c380-fb33-11e9-9448-a3d17539873a.gif)

**Comment by neilpfeiffer** [comment]
@nramamurth -- if we can keep the `More` overflow even with a `none` prop applied, that would appropriate when there is not enough space to display all tabs, as you have in your example above.

The example you have would solve for the original request to have a set of icon-only tabs that all fit faceup in a smaller container.
