### ISSUE TITLE
[terra-tabs] - Menu dropdown is not displayed near dropdown text

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-framework#485]
# Issue Description

On small viewports the Tab component collapses each tab into a drop down. The options are left aligned but the menu is displayed to the right. 

![image](https://user-images.githubusercontent.com/6720991/35634434-4fead89a-0671-11e8-8736-6b2e15cc81cb.png)

![image](https://user-images.githubusercontent.com/6720991/35634597-acecb64e-0671-11e8-8853-0b6ff5775b25.png)

This may be related to: https://github.com/cerner/terra-core/issues/1056

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Cosmetic
- [ ] Other

## Expected Behavior

The Menu dropdown should display near the dropdown text.

## Current Behavior

The Menu and drop down text are not displayed near each other.

## Steps to Reproduce

1. Create a Tabs component
2. Shrink the screen down to a small view port
3. Click the Tab text to open the drop down
4. Observe the drop down is not displayed near the dropdown text

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by nramamurth** [comment]
@neilpfeiffer 

> the alignment of the text label in the single dropdown tab needs to be updated, should be center-aligned text within the box (was missed from initial specs). 

Could you please clarify which of the images below is closer to the proposal above? 

1. 
<img width="269" alt="Screen Shot 2019-10-30 at 3 24 07 PM" src="https://user-images.githubusercontent.com/10090859/67847954-c2af2580-fb29-11e9-9be1-9d5c9727a82e.png">

2. 
<img width="271" alt="Screen Shot 2019-10-30 at 3 24 41 PM" src="https://user-images.githubusercontent.com/10090859/67848017-dfe3f400-fb29-11e9-8a21-8c5e90b7a81f.png">

**Comment by neilpfeiffer** [comment]
Option 1 looks correct per https://zpl.io/2y1JrGq (all the way at the bottom of the page).
