### ISSUE TITLE
[Framework] Main navigation needs to support popover container to handle both static and dynamic content

### ISSUE THREAD

**Issue by amberwilks** [cerner/terra-framework#49]
# Issue Description
There are use cases of options that will need to be handled with a popover menu for the main navigation header. This content does not fit into any other existing components.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The application header should support a popover menu option. 

## Current Behavior
Currently, the application header does not support a popover control.

**Comment by sethbroox** [comment]
The current implementation satisfies the needs of a popover for the roll-up pattern. The current OCS API requirements/designs do not call for any other "Tab" besides the roll-up to invoke a pop over.
