### ISSUE TITLE
Keycode Utils

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#5]
# Issue Description
Currently, Terra components have their own key code constants defined within their respective packages. This results in key codes being repeated throughout components. Consolidating these into a reusable util file would reduce boilerplate.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by tbiethman** [comment]
I know we've talked about creating a 'terra-util' or similarly named package to house some of these things. However, I assume that it'd be packaged with terra-core instead of terra-framework.

**Comment by yuderekyu** [comment]
Yeah, I was planning on moving this over to utils when we created that repo

**Comment by jmsv6d** [comment]
@yuderekyu I believe it's going to be in the terra-core repo, it's not getting it's own. There was already an issue created for this there: https://github.com/cerner/terra-core/issues/1010 so we can just close this one.
