### ISSUE TITLE
Replace local keyCode value definitions with keycode-js dependency

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#519]
# Feature Request

## Description
terra-core packages that parse keyboard input typically define constants for the various keyCode values they care about. There's a lot of duplication between packages, and we've talked about drying up those definitions for a while. 

We could replace those local keyCode definitions with values from [keycode-js](https://www.npmjs.com/package/keycode-js), a small and well-supported third-party package.

**Comment by gabeparra01** [comment]
Is this issue supposed to be in terra-core? I'm interested in working on this one

**Comment by bjankord** [comment]
We have [one in terra-core](https://github.com/cerner/terra-core/issues/2235) that @AlexBrizi just [finished up](https://github.com/cerner/terra-core/pull/2248). He's just started work on this in terra-framework.

**Comment by gabeparra01** [comment]
@bjankord ok cool

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-framework/pull/540
