### ISSUE TITLE
Add new supported width of 560px to disclosure-manager

### ISSUE THREAD

**Issue by ChaseSinclair** [cerner/terra-framework#520]
# Feature Request

## Description
UX wants disclosure manager's within our app to have a width of ~540px~ 560px. This isn't currently an [available disclosure width](https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L18). Since custom values are also not supported I propose adding ~540px~ 560px to the list of available widths.

**Comment by neilpfeiffer** [comment]
Talked with the requesting UX Designer and modifying the request for the new size to be adjusted to **560 px** (_in place of 540px_) as an additional reserve size to better match existing grid of other modal sizes.
