### ISSUE TITLE
[terra-date-picker] Unexpected behavior inside modals

### ISSUE THREAD

**Issue by taahamohsin** [cerner/terra-framework#527]
# Bug Report

## Description
When used with [terra-disclosure-manager](https://github.com/cerner/terra-framework/tree/master/packages/terra-disclosure-manager) with the disclosure size set to 'small', the date-picker renders on top of the actual date field, and for mobile view as well as small desktop viewports, the datepicker in portal view does not render in the center of the modal. Instead, the bottom half of the picker gets cropped out and only the top half is visible.

## Steps to Reproduce
1. Create a form that uses terra-date-picker and render it in a modal using the ```disclose``` function of terra-disclosure-manager
2. Set the ```size``` argument to small in the ```disclose``` function mentioned above
3. Open the datepicker

## Additional Context / Screenshots
![screen shot 2019-02-25 at 2 53 17 pm](https://user-images.githubusercontent.com/16749117/53425445-ff32ec00-39b2-11e9-8a51-31217e18fa5f.png)
![screen shot 2019-02-25 at 2 53 22 pm](https://user-images.githubusercontent.com/16749117/53425414-f0e4d000-39b2-11e9-99a2-7e0bd2dc706e.png)
![screen shot 2019-02-25 at 2 53 33 pm](https://user-images.githubusercontent.com/16749117/53425436-f8a47480-39b2-11e9-9b2d-438d7619bf56.png)

## Expected Behavior
It should behave as the modal example on the Terra UI website does.
![screen shot 2019-02-26 at 10 41 41 am](https://user-images.githubusercontent.com/16749117/53425567-4620e180-39b3-11e9-9554-3a99efa222d5.png)
![screen shot 2019-02-26 at 10 42 02 am](https://user-images.githubusercontent.com/16749117/53425572-4a4cff00-39b3-11e9-9962-58f5d95ee369.png)

## Possible Solution
These lines could potentially be the culprit : https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss#L511-L513

## Environment
* Component Name and Version: 2.39.0
* Browser Name and Version: Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)
* Node/npm Version: Node v18.4.0/yarn v 1.13.0
* Operating System and version (desktop or mobile): mac OS High Sierra 10.13.6

## @ Mentions
@dkasper-was-taken

**Comment by bjankord** [comment]
I'd like us to explore putting the date-picker in terra-popup when it opens in popup form to see if it helps resolve the issue in this screenshot. I know the popup has a logic to help determine this that we lifted to terra-date-picker when we updated to use terra-hookshot. I think having this logic centralized in popup may be better.

![odd positioning](https://user-images.githubusercontent.com/16749117/53425414-f0e4d000-39b2-11e9-99a2-7e0bd2dc706e.png)

**Comment by jmsv6d** [comment]
I've been working on switching DatePicker over to use popup. I have a few things to note from this work:

- We are currently using the `attachmentBehavior` of `flip` This means that if hookshot can't display the content below the target it will flip it above, and if there is no room above then it will push the content over the target to fit the space available. This will still be the case when switching to use popup. We could switch `attachmentBehavior` to `auto` to allow the popup to display to the sides of the target, which would make the likelihood of the input being covered smaller.
- In the push scenario the arrow should not display as the target is not visible, the switch to popup does resolve this.

**Comment by jmsv6d** [comment]
@taahamohsin was the issue here that the Date Picker popup was not allowed to render outside the bounds of the modal?
I also just noticed that this issue was logged for version 2.39.0 of the Date Picker, this version the date picker was still using react-popper, in version 3.12.0 we replaced react-popper with terra-hookshot. @taahamohsin could you try upgrading to 3.12.0 or higher and see if it resolves your issue?

**Comment by taahamohsin** [comment]
@jmsv6d 
> @taahamohsin was the issue here that the Date Picker popup was not allowed to render outside the bounds of the modal?

The concern was more about the date-picker popup covering the actual date field, but in the 'expected behavior' screenshot from the Terra website that was posted with the original issue, the popup does seem to render partially outside the modal, which should be fine as long as its fully visible to the user.

> I also just noticed that this issue was logged for version 2.39.0 of the Date Picker, this version the date picker was still using react-popper, in version 3.12.0 we replaced react-popper with terra-hookshot. @taahamohsin could you try upgrading to 3.12.0 or higher and see if it resolves your issue?

We're currently using version 3.12.0, and it works fine with a small modal:
![image](https://user-images.githubusercontent.com/16749117/58585526-f1e20380-8226-11e9-932d-bedf7162679b.png)

The problem still persists with the mobile view. For example, here's what it looks like on the iPhone XS Max:
![image](https://user-images.githubusercontent.com/16749117/58585632-3f5e7080-8227-11e9-9e26-093186e0fcb3.png)

The last row of dates renders out of view.

**Comment by jmsv6d** [comment]
@taahamohsin The popup covering the input is expected behavior in scenarios where there is not enough room for the popup to display above or below the field. In the original screenshot it looked like there probably was enough room, but I believe this was an issue with react-popper's calculations of available space. A fix for the mobile view went in for v3.14.0.

**Comment by dkasper-was-taken** [comment]
Looks like the change log v3.14.0 might be off, just running it, I think maybe it was pushed to the v4.0.0 release.

**Comment by taahamohsin** [comment]
@jmsv6d @dkasper-was-taken Looks like the issue is fixed in 4.x. Thanks for the help!
