### ISSUE TITLE
Remove terra-heading dependency from terra-modal-manager

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#531]
# Feature Request

## Description
We just released a major version of terra-heading and I was checking which packages downstream use terra-heading and notice [terra-modal-manager has a dependency on it](https://github.com/cerner/terra-framework/blob/4e962cc32526a5d534ee44cc5ba57c0415c8557a/packages/terra-modal-manager/package.json#L38). The [terra-heading component doesn't look like it is used in terra-modal-manager](https://github.com/cerner/terra-framework/search?q=terra-heading&unscoped_q=terra-heading) and it would be safe to remove it.

**Comment by gabeparra01** [comment]
I will work on this one
