### ISSUE TITLE
[Terra Dialog Modal] Add a feature that to have Dialog Modal isRelativeToContainer.

### ISSUE THREAD

**Issue by matlapuditeja** [cerner/terra-framework#534]
# Feature Request

## Description

Need a prop isRelativeToContainer in Dialog modal so that I can keep the Modal is relative to the triggering container.

## Additional Context / Screenshots

Add a Prop isRelativeToContainer in Dialog Modal which is similar to Overlay

## @ Mentions

@ryanthemanuel

**Comment by bjankord** [comment]
Our team would not recommend creating this at the Terra UI level. I'd recommend reaching out to UX to get some guidance on this.

**Comment by neilpfeiffer** [comment]
@matlapuditeja -- I can help your team find an alternate solution that ideally doesn't use terra components in a "creative" way (e.g. overlay + card + dialog to recreate a custom modal), and is something that works with your specific IE browser video-player scenario.
