### ISSUE TITLE
terra-modal-manager is not responsive in Edge browser

### ISSUE THREAD

**Issue by benisonlg60** [cerner/terra-framework#538]
# Bug Report

## Description

terra-modal-manager is not responsive in Edge, but it works fine in chrome and firefox. I encountered this issue while running wdio tests for my component.

## Steps to Reproduce

1. Open the [terra-modal-manager](https://engineering.cerner.com/terra-ui/#/components/terra-modal-manager/modal-manager/example) examples in Edge browser.
2. Resize the window to mobile view.
3. Click on the Disclose(Large)

## Additional Context / Screenshots

<img width="437" alt="screen shot 2019-03-06 at 5 06 34 pm" src="https://user-images.githubusercontent.com/24696981/53879543-cf2fbc80-4034-11e9-9969-a8e3239afb0b.png">

## Expected Behavior

<img width="394" alt="screen shot 2019-03-06 at 5 25 34 pm" src="https://user-images.githubusercontent.com/24696981/53879574-e8386d80-4034-11e9-8284-8f52e127aa62.png">

## Environment

* Browser Name and Version: Edge
* Operating System and version (desktop or mobile): Mobile

**Comment by dkasper-was-taken** [comment]
I believe this is a long known issue with edge:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14375647/

**Comment by dkasper-was-taken** [comment]
With edge converting to chromium we should re-evaluate this issue.

**Comment by nramamurth** [comment]
I tested it with Microsoft Edge 42.17134.1.0 and I don't seem to see the issue. 

![edge](https://user-images.githubusercontent.com/10090859/68195707-51fe8200-ffdd-11e9-875b-b3abe80eb566.gif)

@dkasper-was-taken, I think we can close this issue.

**Comment by ShettyAkarsh** [comment]
Closing. as we are not able recreate this issue
