### ISSUE TITLE
ModalManager dynamic height support with limitations

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-framework#559]
# Feature Request

## Description
I know I've brought this topic up recently in offline conversations and in the past. I believe this is what lead to https://github.com/cerner/terra-framework/issues/167 and the creation of the `terra-dialog-modal`. However, I want to revisit it because I'm getting questions again from teams. I wonder if there is compromise here where ModalManager supports dynamic heights but with some caveats. 

Here are my feature suggestions:

* Add support to ModalManager so that `size` has a `dynamic` value or the default is `dynamic` if not given.
  * If necessary, dynamic height content can be constrained if that makes things easier. 
  * If the reason why dynamic height content was not allowed was due to use cases where a consumer wanted the content of the modal to fill the available space in the modal. I don't see why the content couldn't define it's height and the ModalManager always support dynamic height. 
  * There is real value in just having a single way to deal with modals and allow for the content to contain things like popups that take focus away.  

* Update ModalManager docs to discuss use cases and reasons why consumers of ModalManager would want to define a height when opening a modal. 
  * It is unclear to myself and others consuming ModalManager why consumers have to specify a height when every other modal implementations don't require it.  

I know there will be push back on this request based on previous conversations but I think having DialogModal and ModalManager is confusing to consumers. Maybe my concerns can be summed up as follows:

> Why does ModalManager care about height at all?

## @ Mentions
@tbiethman, @bjankord & @neilpfeiffer

**Comment by dkasper-was-taken** [comment]
This has been repeatedly discussed. The offline decision was to provide further documentation to modal manager to have a consistent point of reference for why set heights were required.

Closing in favor of this documentation issue logged:
#567

**Comment by neilpfeiffer** [comment]
Reasons as to why this issue was closed, and spawned issue #567, are resolved by:
- [cerner/terra-framework/pull/1574](https://github.com/cerner/terra-framework/pull/1574) 
and 
- [cerner/terra-application/pull/309](https://github.com/cerner/terra-application/pull/309)
