### ISSUE TITLE
Slide panel panelSize medium size

### ISSUE THREAD

**Issue by Chris-Boyle** [cerner/terra-framework#563]
# Feature Request
I would really like to have a medium size for the slide panel component.  Currently there is a large and a small.  Neither of these look good for our content.
## Description
Create a medium panelSize in the Slide Panel component.
There are two options here:
1.  Make a medium size that is scalar .4
2. Make a medium size that is fixed at about 500 px.
## Additional Context / Screenshots
Changes in:
1. https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.module.scss#L65
2. https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.module.scss#L114
3. https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.jsx#L32
Small
![image](https://user-images.githubusercontent.com/20329437/54853390-c9390d00-4cbd-11e9-9465-acd9e9d3df6c.png)
Large
![image](https://user-images.githubusercontent.com/20329437/54853426-e077fa80-4cbd-11e9-87ae-4e0ab01134d5.png)
We would like something similar to this screen shot, or 500 px
![image](https://user-images.githubusercontent.com/20329437/54853500-0a312180-4cbe-11e9-8aae-41fa2566729f.png)

**Comment by Chris-Boyle** [comment]
I am working on a PR for this.

**Comment by neilpfeiffer** [comment]
Thanks @Chris-Boyle - curious to know more about your content and workflow, and if you have been working with a designer to guide your layouts. UX has currently kept the slide-panel reserved to only two sizes, large and small, with defined template layouts and most likely will not want to add another size. Responsive details are also a consideration of how best to achieve a layout you are desiring, it might be there is another pattern or layout UX can provide you as good direction.

FWIW - hard to tell is this is exactly what you need, but from your screenshots, if you are looking for a split-view with a 40% left panel, 60% right panel (slide-panel set to squish) - the dimension can actually be achieved by switching your main-content and panel-content.

**Comment by Chris-Boyle** [comment]
@neilpfeiffer we need to have the the left side of our slide panel always in view as the screen is resized.  This would work if the panelContent was set to the start position but the only two options for it being on the left side of the view is large or small.  These two sizes are either not big enough for the panelContent or obnoxiously large.  We worked with Scott on our design some but he couldn't be on board anymore due to time constraints.
Small
![image](https://user-images.githubusercontent.com/20329437/54950468-56bf6b80-4f0f-11e9-9b9a-cb94166b8675.png)
Large
![image](https://user-images.githubusercontent.com/20329437/54950513-6e96ef80-4f0f-11e9-88fe-2f8563b0faef.png)
Our current implementation with the panelContent on the right. We need the panelContent on the left so that it is always in view as the screen is resized or a small(mobile) form factor is used
![image](https://user-images.githubusercontent.com/20329437/54950593-9c7c3400-4f0f-11e9-8fdc-07f6f6a23ffd.png)

**Comment by Chris-Boyle** [comment]
We want to achieve the UI look that Scott Johnson approved but with better resizing.

**Comment by Chris-Boyle** [comment]
@neilpfeiffer your FWIW won't work for our use case because you are saying set the panelContent to the right side as 60%.  We need it to be on the left side so that when the window is resized the left side content always stays in view.  PanelContent has to be on the left and 40% so that it's content is always in view on small form factors.

**Comment by bbellville** [comment]
![image](https://user-images.githubusercontent.com/49045081/55196308-03eaeb80-517d-11e9-884c-541c3f5ef01b.png)

**Comment by kschuste** [comment]
@neilpfeiffer we also are interested in a medium slide-panel width, especially for desktop views where the small width appears way to little and the large view can be way too much.

**Comment by neilpfeiffer** [comment]
Thanks @bbellville and @kschuste, I am currently reviewing this request more broadly with UX and any risks it may cause with cross-framework integration before determining a final outcome or alternate design recommendations.

**Comment by Chris-Boyle** [comment]
@neilpfeiffer any updates on this?

**Comment by neilpfeiffer** [comment]
Thanks @Chris-Boyle, I will be reaching out to work with your team on an alternate code solution for your project with similar effect.  Due to needing to keep certain elements of our various frameworks aligned for cross-app consistency, adding an addition size to the API would put the consistency at risk, so we intentionally will not want to add an addition size at this time. 

@bbellville and @kschuste - your UX Designer will discuss it further with your team as well.

**Comment by JakeLaCombe** [comment]
Given the feedback we have received from UX, this issue will be closed.
