### ISSUE TITLE
[terra-modal-manager] Update documentation to provide height explanation

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-framework#567]
# Feature Request

## Description
Update documentation to explain the reasoning behind limiting the height selection of disclosure to a subset of heights. As this behavior has needed to be expanded upon many times, we should a provide reference for consumers.

**Comment by pranav300** [comment]
The documentation was updated in PR https://github.com/cerner/terra-framework/pull/624.

**Comment by neilpfeiffer** [comment]
Re-opening as key part of issue listed was not addressed by #624 (only a simple documentation of modal sizes, but not reasons or guidance doc).

**Comment by chrismichalewicz** [comment]
UXPLATFORM-6896 logged to track this internally

**Comment by neilpfeiffer** [comment]
Will be resolved by:
https://github.com/cerner/terra-framework/pull/1574
and 
https://github.com/cerner/terra-application/pull/309
