### ISSUE TITLE
Convert forked react datepicker to css modules

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#575]
# Feature Request

## Description
Now that react-datepicker has been forked, it's worthwhile to convert it over to CSS modules to be in line with how we are dealing with the rest of our components.

**Comment by pranav300** [comment]
I have spoken with @neilpfeiffer regarding how the implementation of line-height must be done as previously it was being used with `px` and `rem`.

**Comment by yuderekyu** [comment]
are we converting it to unit-less?

**Comment by neilpfeiffer** [comment]
Provided direction offline to update line-heights to sass variables with multipliers so they work like unit-less, but will be clear which base variable "size" unit they should remain relative to.
