### ISSUE TITLE
Terra Component not working properly.

### ISSUE THREAD

**Issue by saurabh2293** [cerner/terra-framework#591]
# Bug Report

## Description
I am using React Framework and in react framework I am using Terra component but its not working properly .The alignment and responsive behavior is not working in proper manner.

## Steps to Reproduce

1. I ran create-react-app command .
2.In that I use terra-component and import it in app.js file.
3.
4.

## Additional Context / Screenshots
GITHUB REPO: https://github.cerner.com/sg064071/Saurabhworkplace

## Expected Behavior
The component should be open the way it is displayed in terra-Ui.com

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 6]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
I didnot know anyone in terra-team people

**Comment by bjankord** [comment]
If you are wanting to explore using terra components in create-react-app, I have an demo app that I can link to you. It also has a branch that uses the application layout you can check out.

If you have similar questions, there is a Terra Teams channel you can ask support questions in. We try to keep the GitHub issues to feature requests or bug reports.
