### ISSUE TITLE
Make Menu Item font-weight a Custom Property

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-framework#594]
# Feature Request
Would like to request font-weight to be a custom property on the [menu item ](https://github.com/cerner/terra-framework/blob/master/packages/terra-menu/src/MenuItem.module.scss#L2).  This is needed because some fonts require a special weight to use the font. 

Example of Proxima-Nova Semibold

<img width="429" alt="image" src="https://user-images.githubusercontent.com/225765/55630853-4b283c00-577c-11e9-96f8-e37c707b9bfd.png">

## Description
Make font-weight a custom property for the menu-item component which defaults to "inherit" as it currently does.

**Comment by bjankord** [comment]
Reopening. The SCSS linked in the original issue was to terra-menu. We updated terra-menu in this [PR](https://github.com/cerner/terra-framework/pull/636)

The associate implementing the client theming noted that this change is actually needed for the menu items in terra-navigation-side-menu. I'll send out a PR for this shortly.
