### ISSUE TITLE
terra-slide-panel Takes focus while panel is closed

### ISSUE THREAD

**Issue by Me999999999** [cerner/terra-framework#606]
# Bug Report

## Description
After pulling in terra-slide-panel version 3.3.0 our functionality broke for an input-field inside the slide panel. While the slide-panel was closed the input-field would lose focus after each letter you entered. This was not the case while the slide-panel was open, in this case the text area functioned as expected.

## Steps to Reproduce
1. Create a SlidePanel with an InputField as part of its mainContent
2. Type into the InputField while the SlidePanel is closed
Focus will be removed from the InputField

## Additional Context / Screenshots
For our specific case our InputField is the child of an Item, which is the child of a List, which is the mainContent of the SlidePanel.

## Expected Behavior
The InputField should remain focused while typing in to it.

## Possible Solution
It seems the problem that handleTransitionEnd will always be called when the panel is closed; giving the mainNode focus.

## Environment
* Component Name and Version: terra-slide-panel 3.3.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Mac Desktop

**Comment by tbiethman** [comment]
This would be resolved with #447. We need to remove the handleTransitionEnd/preparePanelForTransition logic here: https://github.com/cerner/terra-framework/blob/master/packages/terra-slide-panel/src/SlidePanel.jsx#L87-L108

**Comment by mfried1** [comment]
I am experiencing a similar occurrence. I have a SlidePanel and a Select on a modal dialog (The Select is not contained within the SlidePanel.) When I click on the Select, the dropdown opens and immediately closes because the SlidePanel takes focus.

**Comment by makr28** [comment]
I am seeing a similar issue. Whenever our code calls setState, the slidepanel gets the focus and our page scrolls down to it
