### ISSUE TITLE
SlidePanel flashes in IE

### ISSUE THREAD

**Issue by hboege** [cerner/terra-framework#618]
# Bug Report

## Description
SlidePanel "flashes" or seems to quickly animate when in IE.

## Steps to Reproduce

1.  Go to the "Slide Panel" Component page in terra-ui in an IE browser.
2. Click on the "Main Toggle Panel".
3. See that the panel re-animates/jumps.  You can even see the "Panel Content" display over the "Main Content" for a split second.

## Expected Behavior
Do not blink.  Be more like Chrome where it appears to stay open.

## Environment

* Component Name and Version: terra-slide-panel ^3.1.0
* Browser Name and Version:   IE
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): desktop

**Comment by bjankord** [comment]
@hboege We are having difficulty reproducing this issue. Can you reach out to @tbiethman or @ryanthemanuel to provide some more info on this.

**Comment by nramamurth** [comment]
@hboege Do we have an update on this one?

**Comment by ShettyAkarsh** [comment]
closing. as we are not able to reproduce this issue
