### ISSUE TITLE
Notification Dialog taking entire screen width in IE

### ISSUE THREAD

**Issue by SushmithaBN** [cerner/terra-framework#621]
# Bug Report

## Description
Notification Dialog taking entire screen width in IE for long texts

## Steps to Reproduce

1. Open [terra-notification-dialog](https://engineering.cerner.com/terra-ui/#/components/terra-notification-dialog/notification-dialog/notification-dialog) in IE 11
2. Check for 'Complete Notification Dialog With Long Message' example
3. Trigger notification dialog
4. Notice that it takes more width than normal (width varies with the number of characters in the text)

## Additional Context / Screenshots
**IE:**
![image](https://user-images.githubusercontent.com/42537313/56380791-b409bc80-6230-11e9-9f4c-676a580f3a85.png)
**Chrome:**
![image](https://user-images.githubusercontent.com/42537313/56380812-c71c8c80-6230-11e9-98c6-6e6972f8fa45.png)

## Expected Behavior
It should display as it is displaying in chrome

## Environment

* Component Name and Version: terra-notification-dialog (2.10.0)
* Browser Name and Version: IE 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Operating System and version (desktop or mobile): Mac/Windows

**Comment by yuderekyu** [comment]
### Preliminary Investigation
Internet Explorer seems to have issues with the `calc()` function. Looking up `calc()` in [caniuse](https://caniuse.com/#search=calc): 
> IE11 is reported to have trouble with calc() with nested expressions, e.g. width: calc((100% - 10px) / 3); (i.e. it rounds differently)
 
`terra-abstract-modal`'s [max-width](https://github.com/cerner/terra-framework/blob/master/packages/terra-abstract-modal/src/AbstractModal.module.scss#L6) uses `calc()`. Below is what is calculated. 
<img width="958" alt="ie-abstract-modal-max-width (1)" src="https://user-images.githubusercontent.com/14063284/56384244-8d706500-61e1-11e9-821d-c2976a10c7dd.png">
