### ISSUE TITLE
[terra-tabs] Add themable keyboard focus style

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#627]
# Feature Request

## Description
The UX team has provided specific visuals to draw more attention to the tab that is in focus when tabs are focused via keyboard.
Need to implement keyboard focus detection and related styles.

**Comment by ShettyAkarsh** [comment]
@bjankord , @dkasper-was-taken  will this issue be taken care during #481 ?

**Comment by bjankord** [comment]
I believe so, I think #481 would be a good place to handle this change.

**Comment by ShettyAkarsh** [comment]
This will be fixed during issue #481.
