### ISSUE TITLE
Add functionality to shift focus into date picker when opened and maintain focus within until a date is selected or the user closes the date picker

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#630]
# Feature Request 

## Description
When the date picker is opened, we should shift focus into it. While the date picker is open, we should trap focus in the date picker so users don't cycle out of it as this could cause some confusion. We'd also want to ensure the ability to close the date picker via escape key.

**Comment by pranav300** [comment]
I have checked all the functionality and it seems to work as expected.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29273628/62270267-38382680-b453-11e9-9fd8-0cf2349a392b.gif)
I have even checked it with voice over

**Comment by bjankord** [comment]
This has been resolved in https://github.com/cerner/terra-framework/pull/866
