### ISSUE TITLE
[terra-disclosure-manager] afterDismiss promise is resolved prior to dismissing

### ISSUE THREAD

**Issue by mschile** [cerner/terra-framework#648]
# Bug Report

## Description

The afterDismiss promise is being resolved prior to dismissing [1] the component. If disclosureManager.closeDisclosure() is then called in afterDismiss to close the rest of the disclosure stack, an exception is thrown and the disclosure is not properly closed.

[1] https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L430

Example project: https://github.com/mschile/terra-framework/tree/afterDismiss

## Steps to Reproduce

1. After starting the example project, navigate to http://localhost:8080/#/tests/terra-modal-manager/modal-manager/modal-manager-after-dismiss
2. Click 'Disclose B' button
3. Click 'Disclose C' button
4. Click 'Dismiss C' button and observe the disclosure is not properly closed.

## Additional Context / Screenshots

<img width="1792" alt="Screen Shot 2019-05-02 at 10 18 54 AM" src="https://user-images.githubusercontent.com/2002044/57090310-c4f00e80-6cc3-11e9-9c31-72da75b4f01b.png">

## Expected Behavior

The disclosure is properly closed.

## Possible Solution

Resolve the afterDismiss promise after the component has been dismissed.

https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L430

## Environment

* Component Name and Version: terra-disclosure-manager 4.9.0
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5] Node 8.16.0 / npm 6.4.1
* Webpack Version: 4.30.0
* Operating System and version (desktop or mobile): macOS 10.14.4

## @ Mentions

@tbiethman

**Comment by nramamurth** [comment]
@tbiethman Should the deferred `afterDismiss` promise be resolved after Line 440 to ensure that the disclosure was closed / a disclosure was popped out before resolving it? 

https://github.com/cerner/terra-framework/blob/ab093a9a2203d5f4a90fe3aaa66e18c719328e02/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L427-L441

**Comment by tbiethman** [comment]
Correct, I think it would make the most sense to add callback function arguments to closeDisclosure/popDisclosure and execute them as setState callbacks:

```jsx
popDisclosure(callback) {
  this.setState({
    ...
  }, callback);
}

// When executed
this.popDisclosure(() => {
  this.dismissChecks[key] = undefined; 
  this.resolveDismissPromise(key); 
}); 
```

It might also make sense for popDisclosure to internally call closeDisclosure if there's only one item in the stack. That would simplify the existing handler logic.
