### ISSUE TITLE
[time-input] The height of the time-input increases as the container width becomes smaller.

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-framework#665]
# Bug Report

## Description
When the container width becomes smaller than the width of the time-input, the input to the right (minute/meridiem) gets pushed to the next line, causing the overall height of the time-input to increase.

## Additional Context / Screenshots
![time-input](https://user-images.githubusercontent.com/22618655/57733554-6765a580-7665-11e9-8041-cf8559dcaa11.gif)

## Possible Solution
Set the `width` on the time-input container to `max-content`

**Comment by pranav300** [comment]
@benbcai Is this the expected behavior?
<img width="86" alt="time input" src="https://user-images.githubusercontent.com/29273628/60790806-f4b60980-a17f-11e9-9052-48fd909a96a6.PNG">

**Comment by nramamurth** [comment]
Related: https://github.com/cerner/terra-framework/issues/706

@neilpfeiffer

**Comment by benbcai** [comment]
This has been fixed by #837
