### ISSUE TITLE
Terra Menu Item text is bold in Edge browser

### ISSUE THREAD

**Issue by eKilberg** [cerner/terra-framework#675]
# Bug Report

## Description
Terra Menu Item text is bold in Edge browser. In Chrome, IE, and FireFox text is normal.

## Steps to Reproduce
1. View [Terra Menu examples](https://engineering.cerner.com/terra-ui/#/components/terra-menu/menu/menu) in Edge browser 

## Expected Behavior
The Terra Menu Item Text should not be bold

## Environment
* Component Name and Version: Terra Menu
* Browser Name and Version: Edge
* Node/npm Version: Node 8.12.0/npm 6.4.1
* Webpack Version:
* Operating System and version (desktop or mobile): Windows desktop

**Comment by bjankord** [comment]
<img width="646" alt="Screen Shot 2019-05-16 at 9 52 58 AM" src="https://user-images.githubusercontent.com/633148/57863869-71e88200-77c0-11e9-9713-40fa8ca4a722.png">
It does appear to be a bit bolder than intended.
