### ISSUE TITLE
[terra-date-time-picker] Date Time Picker (12-Hour format) doesn't re-size itself to fit in mobile device screen

### ISSUE THREAD

**Issue by lulz010** [cerner/terra-framework#706]
# Bug Report

## Description
The Date Time Picker component, 12-Hour format, doesn't resize itself to fit on mobile devices screens. It was confirmed to be happening on android and iOS devices. If the font size is adjusted to small on the CT-50 device's settings the component is displayed correctly. Modifications to the devices' display settings seems to help, but the component still doesn't fit entirely on the screen.

## Steps to Reproduce
1. Open CareAware Connect Messenger App's Set My Status View on a mobile device (iPhone 8, Galaxy S9, and Honeywell CT-50).
2. Select Unavailable or Do Not Disturb options on the 'Set your status to...' radio button
3. Select Custom on the 'Clear your status after...' drop down

## Expected Behavior
The Date Time Picker component (12-Hour Format) should resize itself to fit on a mobile device screen.

## Environment
* Component Version: 4.2.0
* Operating System and version (desktop or mobile): mobile android and iOS

## Example Screenshot
<img width="864" alt="Screen Shot 2019-06-11 at 1 23 53 PM" src="https://user-images.githubusercontent.com/1355485/59296714-41272b80-8c4c-11e9-89c3-58d74822706c.png">

## Mentions
The issue was mentioned on the Terra Component Support channel on Teams. It was addressed by Dave Kasper @dkasper-was-taken and Neil Pfeiffer @neilpfeiffer .

**Comment by nramamurth** [comment]
@neilpfeiffer 

From the UX standpoint, what is the expected outcome? Should the Time Input wrap around like something below or should Date Picker and Time Input completely resize (get smaller (?)) accordingly and remain inline with each other?

![Screen Shot 2019-07-09 at 12 30 12 PM](https://user-images.githubusercontent.com/10090859/60866326-acf9b580-a245-11e9-8020-a457d0db8b27.png)

**Comment by neilpfeiffer** [comment]
For an immediate fix - lets have the inputs wrap, but rework css to have an alignment similar to below. (Note: we'll also need to re-check with the enhancement that adds the Seconds input, if the entire time-input will fit all on one line):

<img width="480" alt="Screen Shot 2019-07-09 at 7 56 58 AM" src="https://user-images.githubusercontent.com/1355485/60889691-3944b200-a21f-11e9-9d6f-d0fe08295287.png">

**Comment by nramamurth** [comment]
@neilpfeiffer 

BTW I checked out of https://github.com/cerner/terra-framework/pull/722 's branch that adds the Seconds input and looks like it'll further break upon moving the Time Input. I don't think it's good idea to further wrap the Meridiem group, what is the stand from the UX point here?

<img width="281" alt="Screen Shot 2019-07-10 at 2 08 18 PM" src="https://user-images.githubusercontent.com/10090859/60954246-4bf0e100-a31c-11e9-800e-6ddc8bc03d53.png">

**Comment by nramamurth** [comment]
**Update:** 

Since this issue will show itself up when Seconds input is introduced, @neilpfeiffer mentioned that this needs to be further discussed with the OCS group as to whether the Time Input unit needs to be redesigned a bit to suit for mobile view.

**Comment by neilpfeiffer** [comment]
New design changes will also resolve this found issue #710 by removing the desktop dropdown/select implementation.

**Comment by neilpfeiffer** [comment]
------------------------------------------------------------------
**Design Updates**

Updated designs for the time input (and shown here as consumed in the date-time-picker). Important notes: currently there are two layout options for the time input based on `isConsideredMobileDevice` (one for when it is above 1024px and one for below and detects for DocumentTouch/maxTouchPoints/msMaxTouchPoints), this change removes the two version and now there will only be a single UI for all situations that does not visually separate the hour/minute/second inputs, does not use the dropdown select for the AM/PM but instead only uses the button-group.  

\
**24 hour:**
<img width="1510" alt="24-hr-date-time-picker-wrapping" src="https://user-images.githubusercontent.com/1355485/62472583-aedf6780-b764-11e9-91c6-7b778c0db434.png">

**12 hour:**
<img width="1853" alt="12-hr-date-time-picker-wrapping" src="https://user-images.githubusercontent.com/1355485/62472610-c0287400-b764-11e9-87ed-7f784526a182.png">


------------------------------------------------------------------

**Code Updates:**
Updates to code will be:
```
(adding code details here)
```

**Comment by nramamurth** [comment]
Thanks for the input, @neilpfeiffer. I shall get this done.

**Comment by nramamurth** [comment]
@neilpfeiffer 

Upon refactoring, this is how it looks upon maximum resize on Chrome. I guess this is fine keeping in mind the current behavior put forth on #665. What do you think?

<img width="153" alt="Screen Shot 2019-08-09 at 4 25 00 PM" src="https://user-images.githubusercontent.com/10090859/62774438-51c81680-bac2-11e9-8ccc-dc93b652d061.png">

**Comment by benbcai** [comment]
This has been fixed by #837
