### ISSUE TITLE
Terra-collapsible-menu-view breaks with a single large item.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-framework#713]
# Bug Report
Terra-collapsible-menu-view breaks with a single large item.

## Description
If you have a single large item in the collapsible menu view, the item will not collapse and will overflow.

## Steps to Reproduce
1. Create a collapsible menu view
2. Add a large item group
3. Dispair

The following code should be close, I haven't tested it myself.
```javascript
const SettingsMenu = () => {
  return (
    <CollapsibleMenuView className={cx('flex-collapse')} key="menu">
      <CollapsibleMenuView.ItemGroup>
        <CollapsibleMenuView.Item
            text="long text"
            key="derp"
          />
        <CollapsibleMenuView.Item
            text="long text"
            key="derp1"
          />
        <CollapsibleMenuView.Item
            text="long text"
            key="derp2"
          />
        <CollapsibleMenuView.Item
            text="long text"
            key="derp3"
          />
        <CollapsibleMenuView.Item
            text="long text"
            key="derp4"
          />
        <CollapsibleMenuView.Item
            text="long text"
            key="derp5"
          />
      </CollapsibleMenuView.ItemGroup>,
    );
    </CollapsibleMenuView>
  );
```

## Additional Context / Screenshots
![Screen Shot 2019-06-04 at 1 09 06 PM](https://user-images.githubusercontent.com/1588747/58903015-fd6f7780-86c9-11e9-9351-d4e75393dd46.png)

## Expected Behavior
If this first item is too big, it collapses.

## Possible Solution
A cheap work around is to always add an undefined item as a child. But it's gross.

## Environment
* Component Name and Version: terra-collapsible-menu-view@6.1.0
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@mjhenkes

**Comment by pranav300** [comment]
I was trying to recreate the issue but wasn't able to reproduce it. I tested it in terra-dev-site and found to work as expected. Can you tell me how to reproduce?

**Comment by pranav300** [comment]
@mjhenkes I tried creating the collapsible-menu as children of terra-clinical-header and it seems to work as expected. I am attaching the code and screenshots of chrome and IE.

Code: 
```javascript
import React from 'react';
import Header from 'terra-clinical-header';
import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
import IconFolder from 'terra-icon/lib/icon/IconFolder';
import IconTrash from 'terra-icon/lib/icon/IconTrash';
import CollapsibleMenuView from '../../../CollapsibleMenuView';

const CollapsibleMenuViewSingleItem = () => (
  <Header title=" hello title" startContent="hello start">
    <CollapsibleMenuView>
      <CollapsibleMenuView.ItemGroup>
        <CollapsibleMenuView.Item icon={<IconPrinter />} text="Print Message" className="Print" key="print" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconFolder />} text="Move Message to Folder..." className="Move" key="move" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconTrash />} text="Trash Message" key="trash" className="Trash" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconPrinter />} text="Print Message" className="Print" key="print" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconFolder />} text="Move Message to Folder..." className="Move" key="move" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconTrash />} text="Trash Message" key="trash" className="Trash" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconPrinter />} text="Print Message" className="Print" key="print" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconFolder />} text="Move Message to Folder..." className="Move" key="move" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconTrash />} text="Trash Message" key="trash" className="Trash" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconPrinter />} text="Print Message" className="Print" key="print" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconFolder />} text="Move Message to Folder..." className="Move" key="move" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconTrash />} text="Trash Message" key="trash" className="Trash" isIconOnly />
        <CollapsibleMenuView.Item icon={<IconTrash />} text="Trash Message" key="trash" className="Trash" isIconOnly />
      </CollapsibleMenuView.ItemGroup>
    </CollapsibleMenuView>
  </Header>
);

export default CollapsibleMenuViewSingleItem;
```

Google Chrome: without overflow
<img width="766" alt="googlechrome" src="https://user-images.githubusercontent.com/29273628/59175656-ff2ab680-8b73-11e9-83a2-0c1e1758bb90.PNG">

Internet Explorer: without overflow
<img width="766" alt="IE" src="https://user-images.githubusercontent.com/29273628/59175691-12d61d00-8b74-11e9-9587-fdf52f690732.PNG">

Google Chrome: with overflow
<img width="767" alt="gc" src="https://user-images.githubusercontent.com/29273628/59175705-1e294880-8b74-11e9-8f14-17a906c0f6a5.PNG">

**Comment by mjhenkes** [comment]
@pranav300 
I've created a branch re-creating this issue
https://github.com/cerner/terra-framework/tree/collapse-issue-recreate

Once you've built and started the branch, navigate to:
http://localhost:8080/#/tests/terra-collapsible-menu-view/collapsible-menu-view/single-item-group

The key appears to be setting children as an array.
