### ISSUE TITLE
[Terra-Collapsible-Menu-View] Large viewport tests fail in MpagesTheme

### ISSUE THREAD

**Issue by lokesh-0813** [cerner/terra-framework#724]
# Issue Description

WDIO tests fail for Large viewport when updating Mpages Theme for terra-collapsible-menu-view. 

Reference : https://github.com/cerner/terra-framework/blob/55d95c07154f628962c4ba125d892f4f17d4c44b/packages/terra-collapsible-menu-view/tests/wdio/collapsible-menu-view-spec.js#L15

**Comment by yuderekyu** [comment]
The test tries to click on the collapsible toggle button. In the mpage theme, the menu has enough space for all items at large viewports, so the collapsible toggle button does not exist. Anyone against removing the large viewport? We'll still test tiny, small, and medium responsiveness.

**Comment by bjankord** [comment]
Let's add more buttons to the test so this works for both the open source theme and mpage theme.
