### ISSUE TITLE
Add the ability to query the display mode of embedded iOS web content

### ISSUE THREAD

**Issue by madsolar8582** [cerner/terra-framework#733]
JIRA: [UXPLATFORM-5822](https://jira2.cerner.com/browse/UXPLATFORM-5822)

# Feature Request

## Description
With the introduction of iOS 13, Apple now allows for a system-wide dark mode. When activated by the user, system elements adapt by changing their semantics to a dark equivalent. For embedded web content, that content needs to respond as well. Please investigate what would be required to make this possible using `prefers-color-schemes` for themes to adjust between light and dark mode.

## Additional Context / Screenshots
[Dark Mode HIG](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/)
[Safari 13 (WebKit) Release Notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_release_notes)
[WebKit Dark Mode](https://webkit.org/blog/8840/dark-mode-support-in-webkit/)

## @ Mentions
cc @mjhenkes

**Comment by bjankord** [comment]
Currently, we do not provide a first-class/OCS theme for a dark mode for terra components. This is something that you'd need to reach out the UX team to about if your app needs it.

In terms of implementation, by using `window.matchMedia` to detect if the `(prefers-color-scheme: dark)` media query matched, one could use that to pass a class to the terra-theme-provider component which contained CSS custom properties defined for a dark-mode theme.

```css
.dark-mode {
  --terra-button-background-color-neutral: #222;
  --terra-button-color-neutral: #ddd;
}
```
```jsx
const colorScheme = window.matchMedia("(prefers-color-scheme: dark)").matches ? 'dark-mode' : undefined;

<ThemeProvider themeName="colorScheme">
{children}
</ThemeProvider>
```

**Comment by chrismichalewicz** [comment]
Logged UXPLATFORM-5822 to track this work and linked to it in the description.
