### ISSUE TITLE
DatePicker is not being Displayed in tiny Breakpoints for some of the DatetimePicker tests.

### ISSUE THREAD

**Issue by ShettyAkarsh** [cerner/terra-framework#743]
## Description
Datepicker is not being displayed in tiny breakpoints for some of the Datetimepicker tests. due to which WDIO tests of MPAGE Theme repo are failing as the datepicker element is not being found in the DOM.

During the PR #2452 for **[UpdateBreakpoint ranges]** the defaultElement prop of ResponsiveElement was removed and existing defaultElement prop was updated to tiny. this needs to updated in this repo as well for terra-datepicker. 

## Steps to Reproduce
Refer Terra-responsive-element from master branch of terra-core and check the below tests for Terra-Datetime-picker in tiny breakpoints.

https://engineering.cerner.com/terra-framework/#/tests/terra-date-time-picker/date-time-picker/date-time-picker-filter-dates

## Additional Context / Screenshots

issue screenshot :-

![image](https://user-images.githubusercontent.com/45097016/59683843-83291200-91f6-11e9-8bf4-3bbde58a8129.png)

Correct screenshot :- 

![image](https://user-images.githubusercontent.com/45097016/59684569-e9fafb00-91f7-11e9-826a-7a7485ec4beb.png)

## Expected Behavior
DatePicker should display for all the breakpoints of datetimepicker examples

## Possible Solution
Update defaultElement prop of ResponsiveElement in DatePicker.jsx as tiny

**Comment by StephenEsser** [comment]
For clarity, this is only a problem in the theme repositories because they are pulling all snapshots from master. Terra Framework cannot be updated until the changes to the responsive element have been released.

**Comment by supreethmr** [comment]
Just found couple of place which also needs to be updated with Responsive element changes : 

1. [terra-application-header-layout](https://github.com/cerner/terra-framework/blob/2fd333ba89df84706294c1e844498a65b967263d/packages/terra-application-header-layout/src/terra-dev-site/doc/example/HeaderWireframe.jsx#L51)

2.[terra-tabs](https://github.com/cerner/terra-framework/blob/2fd333ba89df84706294c1e844498a65b967263d/packages/terra-tabs/src/Tabs.jsx#L198)

**Comment by supreethmr** [comment]
Fixed by : https://github.com/cerner/terra-framework/pull/745
