### ISSUE TITLE
[terra-tabs] Add font-weight prop for active tab to support mpagestyle theme

### ISSUE THREAD

**Issue by kc4181** [cerner/terra-framework#753]
# Feature Request

## Description
Need to add font-weight prop for active tab to support mpagestyle theme

## @ Mentions
@neilpfeiffer

**Comment by jmsv6d** [comment]
@neilpfeiffer Did we actually want font-weight style for the active tab? This could cause width of tab to change on selection.

**Comment by neilpfeiffer** [comment]
I also recognized that it can cause a change of the width and erratic behavior and relayed the concerns. For this case, we will expose it as themeable, but will keep the default, and for most themes usages, set the font-weight intentionally the same to prevent the changes.
