### ISSUE TITLE
[terra-date-time-picker] onBlur called before/during DST resolution, selections lost

### ISSUE THREAD

**Issue by prmeznar** [cerner/terra-framework#758]
# Bug Report

## Description
This relates to https://github.com/cerner/terra-framework/issues/521 and https://github.com/cerner/terra-framework/issues/522. In short, with 521 requested for the ambiguous date resolution to occur before onChange, as onChange is what was causing our component to call our service to update the date. With 522 that was going to change to the newly consolidated onBlur, meaning we would need the ambiguous date resolution to occur before onBlur as well.

521 went through and worked well for our onChange implementation. Once 522 was completed and we updated our implementation (making it _much_ cleaner and easier for us, thank you again), DST issues reappeared.

## Steps to Reproduce
1. Have some external service called when onBlur is invoked from a date-time component.
2. Select an ambiguous hour (Nov 3, 1:15) and navigate away from the component.
3. Modal appears simultaneously with update going through, the value from the modal is essentially lost.

## Additional Context / Screenshots
Below you can see that the time zone is not being honored.
![image](https://user-images.githubusercontent.com/47360296/60216935-08cd4300-9831-11e9-8d3a-73e4a295dbfe.png)
![image](https://user-images.githubusercontent.com/47360296/60216940-0c60ca00-9831-11e9-817e-e8214d9fa726.png)
![image](https://user-images.githubusercontent.com/47360296/60216946-0f5bba80-9831-11e9-8f7e-34a178deae74.png)
![image](https://user-images.githubusercontent.com/47360296/60216955-14b90500-9831-11e9-9449-df0d939ca34d.png)
These screenshots were generated by updating to the ambiguous hour, selecting and deselecting the component, which generates the modal (our wrapper will not call our service if the underlying time did not change), and picking one and then the other of the offsets. Despite changing the offset, the underlying time did not change.

## Expected Behavior
If the ambiguous hour is entered, onBlur is not called until after the modal is dismissed. The modal does not put focus back into the other parts of the component. To a consumer/user, interacting with the modal is still part of modifying the time, and onBlur (at least as requested in 522) is a signal that the user is done modifying the time.

## Possible Solution
Check if we're in the ambiguous hour prior to calling the onBlur prop, call the onBlur prop whenever the modal is dismissed.

## @ Mentions
@benbcai

**Comment by nramamurth** [comment]
@benbcai @jmsv6d 

I put together an initial draft here: https://github.com/cerner/terra-framework/compare/on-blur-DTP Please note that I had to hack around `checkAmbiguousTime` a bit to get `TimeClarification` dialog open in India (it shall be removed later). 

It'll be great if you could take a quick look and let me know if there are a certain cases that I should probably test before I go ahead and open a PR if this draft looks good.

**Comment by prmeznar** [comment]
@nramamurth if it's not too much work to get a snapshot out there I'd be happy to play around with it some

**Comment by nramamurth** [comment]
@prmeznar 

Great! Thank you and I appreciate it. I have cleaned it up a bit and here is the branch that you could point to and play around - https://github.com/cerner/terra-framework/tree/on-blur-DTP. I have also reached out to you on Teams.

**Comment by nramamurth** [comment]
@prmeznar 

I have a snapshot built as well and you could use the snapshot if you do not want to point to the branch.

```
"terra-date-time-picker": "https://github.cerner.com/terra/terra-snapshots/blob/master/terra-framework/on-blur-DTP/terra-date-time-picker.tgz?raw=true",
```

**Comment by prmeznar** [comment]
Snapshot behaves better in that the blur does not occur until the dismissal of that window.

However, in some of our crazier workflows there's still some unexpected behavior. For the workflow:
* Update to the ambiguous hour, modal pops
* Specify the hour, close modal, our service is called and page refreshed with updated value
  * On our refresh, we will no longer display the timezone face up, which our strategists have OKed (Since we provide times in UTC, ideally the component could figure out (or at least intelligently guess) at before/after daylight saving given system time zones, and display that guess without needing a blur, but it's not a priority)
* Click into the field, blur without changing any values, modal pops
* Specify the same hour (so CDT -> CDT), modal closes, I assume blur is called but it _**does not update**_ due to our consuming logic (the time has not changed)
* Edit the time (say, from 1:30 -> 1:40). Blur does not seem to get called but I would expect it to.

You can see a video of the last three steps of that process [here](https://cernerprod.sharepoint.com/:v:/s/OrdersandPlansDev/Projects/EUldTWVE2fhHg_vHJOHmpEwBA4yN924mILUSH1NIyJ8fjQ?e=uDrrWY)

I'm guessing this is because the logic is "if you're in the ambiguous hour only invoke blur when the modal closes" but I think better reasoning is "only allow blur when the ambiguity is resolved and the date time component loses focus" -- and then anytime that little timezone specifier thing shows it would qualify as 'resolved' (along with closing the modal). You can see the current approach suggested by me above but I hadn't thought it fully through - sorry. 

As a side, I would expect to be able to update the time and immediately click that time zone specifier without blur being invoked (i.e., I'd say that time zone qualifier is part of the date time component). That may be 'free' - I'm not sure how y'all managed the magic of not calling blur when hopping from one 'subcomponent' to another, but I'm super glad you did.

**Comment by nramamurth** [comment]
@prmeznar 

Thanks for the feedback and I appreciate it. I think that's a legit scenario and I have updated the snapshot to account for it. If it's not too much work, then could you test it out and lmk how it behaves?

**Comment by prmeznar** [comment]
@nramamurth Looks good! Thanks for the quick turnaround.
