### ISSUE TITLE
Introduce terra-application-layout

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#77]
# Issue Description
We're going to reintroduce the terra-application package. Instead of the very simple wrapper that it previously exported, it will export a configurable Application component that utilizes the various 'terra-application-x' components and layouts that have been created in an opinionated fashion. This should be used as a starting point for application creation.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by bjankord** [comment]
I'm not really familiar with this intent or scope of this. My initial thought is this is probably outside of the scope of terra-ui. I'm thinking this is likely more a component named, orion-application which uses terra-ui components to compose the UI for the application.

**Comment by mjhenkes** [comment]
The engineers working on this are getting close to delivering a pull request. I propose that they move forward with getting the pull request out and we can review intent, scope and naming in the war room on Friday.

**Comment by bjankord** [comment]
Talked with @mjhenkes @ryanthemanuel @JakeLaCombe and reached consensus on moving forward with this as terra-application-layout.

**Comment by mjhenkes** [comment]
merged with #116
