### ISSUE TITLE
terra-application-layout seems to be missing terra-disclosure-manager dependency

### ISSUE THREAD

**Issue by nbeyer** [cerner/terra-framework#778]
# Bug Report

## Description
terra-application-layout seems to require terra-disclosure-manager to operate but doesn't depend on it, so it must be separately added as an explicit dependency.

## Steps to Reproduce
1. Add terra-application-layout to project
2. Use ApplicationLayout component
3. The component will fail to load because the disclosure manager is not found
4. Add terra-disclosure-manager to project
5. Reload and the component will load

## Additional Context / Screenshots
Here's the stack trace ...
```
fromRequireContextWithGlobalFallback.js:21 Error: Cannot find module 'terra-disclosure-manager'
    at webpackMissingModule (ModalManager.js:38)
    at Object../node_modules/terra-modal-manager/lib/ModalManager.js (ModalManager.js:38)
    at __webpack_require__ (bootstrap:63)
    at Object../node_modules/terra-application-layout/lib/ApplicationLayout.js (ApplicationLayout.js:38)
    at __webpack_require__ (bootstrap:63)
    at Module../app/javascript/components/Application.jsx (.*$:38)
    at __webpack_require__ (bootstrap:63)
    at webpackContext (.*$:23)
    at fromRequireContext.js:13
    at Object.getConstructor (fromRequireContextWithGlobalFallback.js:15)
```

## Possible Solution
Add terra-disclosure-manager as a dependency or documentation as to when and why.

**Comment by emilyrohrbough** [comment]
It's marked as a peer dependency. You should have seen something like the following in the console after running npm install if `terra-disclosure-manager` was missing.

```bash
npm WARN terra-application-layout@5.0.0 requires a peer of terra-disclosure-manager@^4.9.0 but none was installed.
```

**Comment by nbeyer** [comment]
Yes, indeed, that is happening. Why is this a peer dependency though, while the others are just dependencies?

This is the first time I've encountered an NPM module that can't operate without a peer dependency.

**Comment by mjhenkes** [comment]
NPM will resolve version incompatible dependencies by duplicating the dependency in a sub folder
https://npm.github.io/how-npm-works-docs/npm3/duplication.html

Some packages we don't want duplicated because of the ill effects that this can cause. React is one example of a package we don't want duplicated. In this case we don't want to duplicate terra-disclosure-manager because it exports a react context object.

We use peer dependencies as one method to prevent duplication by asking the consuming app to provide the dependency and resolve any unmet peer dependency warnings that may result from incompatible versions. Another method is our duplicate package checker webpack plugin.

**Comment by nbeyer** [comment]
I understand the use of peer dependencies in NPM, I just haven't experienced any other use of peer dependencies that are explicitly required to operate. I've gotten peer dependency warnings left and right, but never needed to resolve them to operate initially.

Can the documentation be changed, at least? It's incomplete. The documentation implies that all that's needed is a single NPM add - https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/about. The warning isn't enough to resolve "Getting Started".

**Comment by bjankord** [comment]
We'll work on adding documentation updates to indicate that peer dependencies listed for terra packages are expected to be installed in the app consuming said terra packages and list out which specific peer dependencies are expected for each terra package.

**Comment by bjankord** [comment]
We've added documentation regarding peer dependencies to terra components:
* Example on the doc site: https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/about
* Example in the README: https://github.com/cerner/terra-framework/blob/master/packages/terra-application-layout/README.md#peer-dependencies

**Comment by nbeyer** [comment]
Thanks!
