### ISSUE TITLE
Horizontal Scroll bar gets added for tabs at Medium viewport when base-font-size is 75%

### ISSUE THREAD

**Issue by supreethmr** [cerner/terra-framework#793]
# Bug Report

## Description
In Medium viewport min-width property exceeds width property of Tabs when terra-base-font-size is set to 75%. i.e. min-width gets computed to 85.716px which is greater then width of tab 85.7031px. (difference can be seen on screenshot below)

## Steps to Reproduce
1. Navigate to https://engineering.cerner.com/terra-framework/#/tests/terra-tabs/tabs/tabs/default-tabs
2. Toggle viewport to Medium (width: 768px IPad in chrome)
3. Change terra-base-font-size to 75%
4. Horizontal Scroll bar will shows up for the tabs.

## Additional Context / Screenshots
In mpage-Fusion-Theme terra-base-font-size is set to 75% which makes more tabs to show up on screen as shown below : 
<img width="1658" alt="Screen Shot 2019-07-19 at 2 54 21 PM" src="https://user-images.githubusercontent.com/12869809/61528480-87865c00-aa3c-11e9-9213-a7db48161f70.png">

Total 9 tabs shows-up in medium viewport each having min-width of 85.716 which sums up to 771.444 px which is greater than width of medium viewport (768 px). this causes tabs to overflow from available screen width of 768 px. Due to this overflow of tabs WDIO tests in mpage fusion theme were failing with **"endX is out of range"** error.

## Expected Behavior
Tabs should not overflow on given viewport

## Environment

* Component Name and Version: Terra-Tabs / 6.6.0
* Browser Name and Version: Chrome  ( Latest )
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Tab ( Medium Viewport 768px)

**Comment by supreethmr** [comment]
Need assistance with tabs overflowing issue for font size 75%. with Initial investigation I found that
this issue can be fixed by changing parseInt() to parseFloat() for retrieving min-width of tabs. Since horizontal bar shows up due to tabs overflow in tabs_collapsible_container, using parseFloat() returns actual min-width of tabs without rounding of fractional part of min-width. With Actual min-width it would be more accurate to check whether tabs are fitting in available width or not. 

Even in terra-framework tabs have min-width slightly greater than available viewport's width. For Large viewport (1000px) width total number of tabs displayed are 10 tabs including toggle-menu which will have total min-width of 100.002px. since difference here is considerably lesser horizontal scroll-bar was not added. 

By changing below line in handleResize() method we can make sure that total sum of min-width of tabs displayed will always be lesser than available width.

```javascript
const minWidth = parseInt(window.getComputedStyle(tab, null).getPropertyValue('min-width'), 10); 
```
To 
```javascript
const minWidth = parseFloat(window.getComputedStyle(tab, null).getPropertyValue('min-width')); 
```
Branch with code changes and updated screenshots : [Tabs-overflow](https://github.com/cerner/terra-framework/commit/0067fc49e52e8ac6c3df9e1e5c28ce21fc02b136)

Need some inputs to proceed with this fix.

**Comment by ShettyAkarsh** [comment]
The solution provided by using parsefloat looks fine. as it actually fixes the issues existing in medium viewport and large viewport. though the screenshot of the large view port is different (1 tab less) than what we actually have now in the main repo. but we might have to check for different font size available in our theming repos.

@StephenEsser @ryanthemanuel your thoughts.

**Comment by StephenEsser** [comment]
The parseFloat sounds like a reasonable solution to me. We may need to investigate if this causes any issues with the other calculations for the component. Because the change is small, I would recommend moving forward with creating a PR. We can test the branch snapshot in the theme repositories and get more feedback from other engineers on the PR.

cc: @dkasper-was-taken @jmsv6d
