### ISSUE TITLE
Date picker does not validate entry of dates without slashes

### ISSUE THREAD

**Issue by oc018228** [cerner/terra-framework#797]
# Feature Request

## Description
The Date picker should validate if entered dates have slashes between day/month/year. If not present, they should be automatically inserted to prevent errors or workflow disruptions.

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/53089156/61541814-555e0580-aa0e-11e9-9c65-ee8393d367d4.png)

**Comment by benbcai** [comment]
Closing this in favor of #468 .
