### ISSUE TITLE
Controlled date picker misforms date entry as slashes are added to it

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#800]
# Bug Report

## Description
When typing a date into the controlled date picker component, slashes will be added to it after typing in 5 numbers into the input. When this happens, the numbers that were originally entered are also updating malforming the entered data.

## Steps to Reproduce

1. Navigate to https://engineering.cerner.com/terra-ui/#/components/terra-date-picker/date-picker/date-picker
2. Scroll down to the Controlled Component example
3. Start typing in a date, `01011234`
4. When you press `3`, the date entered becomes malformed, changing to `05/03/0101`

## Additional Context / Screenshots

<img width="212" alt="Screen Shot 2019-07-22 at 11 38 17 AM" src="https://user-images.githubusercontent.com/633148/61648628-68beda00-ac75-11e9-9c10-2f9bd7afccff.png">

## Expected Behavior
Date values should not be malformed as users enter data into the date picker input.

## Environment

* Component Name and Version: terra-date-picker 4.7.0
* Browser Name and Version: Chrome Latests
* Node/npm Version: [e.g. Node 8/npm 5] node 8 / npm 5
* Webpack Version:
* Operating System and version (desktop or mobile): macOS 10.14

## @ Mentions
@benbcai

**Comment by nramamurth** [comment]
Below is the line that causes it because apparently "0101123" is valid and proceeds to format it. 

https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L361

The question however is - when exactly should it check for validity and format the date if not while the user is entering the text? 

@bjankord @benbcai @neilpfeiffer

**Comment by bjankord** [comment]
@nickpith mentioned looking at removing the onRawChange handler in the example controlled function.

**Comment by bjankord** [comment]
I tested removing the `handleDateChangeRaw` handler from updating the `<Datepicker />` value prop, but then I was unable to type data into the input.

```jsx
class DatePickerExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      date: this.props.value,
      rawDate: this.props.value,
    };
    this.handleDateChange = this.handleDateChange.bind(this);
    this.handleDateChangeRaw = this.handleDateChangeRaw.bind(this);
  }

  handleDateChange(event, date) {
    this.setState({ date });
  }

  handleDateChangeRaw(event, date) {
    this.setState({ rawDate: date });
  }

  render() {
    return (
      <div>
        <p>
          Selected ISO Date:
          <span className={cx('date-wrapper')}>{this.state.date}</span>
        </p>
        <p>
          Selected Raw Date:
          <span className={cx('date-wrapper')}>{this.state.rawDate}</span>
        </p>
        <Field label="Enter Date" htmlFor="controlled-dates">
          <DatePicker
            name="controlled-input"
            id="controlled-dates"
            onChange={this.handleDateChange}
            onChangeRaw={this.handleDateChangeRaw}
            value={this.state.date}
          />
        </Field>
      </div>
    );
  }
}
```
I believe that will handler will need to stay the way it is.
In regards to formatting, it looks like `0101123` is being formatted into `05/03/0101`. I'm not entirely sure why this is being formatted that way. Would need to test that some more with how we are formatting the date.
