### ISSUE TITLE
[terra-menu] Arrow key focus is broken for menu item groups

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-framework#801]
# Bug Report

## Description
Arrow key focus breaks when cycling through a menu item group to get to other menu items.

### Down arrow
1. https://engineering.cerner.com/terra-framework/#/raw/tests/terra-menu/menu/menu/large-menu
2. Use the down arrow key to cycle focus
3. Focus jumps from the first menu item group item (Default 61) back to first menu item (Default 1).

### Up arrow
1. https://engineering.cerner.com/terra-framework/#/raw/tests/terra-menu/menu/menu/large-menu
2. Use the up arrow key to cycle focus
3. Focus toggles between last menu item group item (Default 153) and last menu item (Default 16).

![test_optimized](https://user-images.githubusercontent.com/14063284/61661868-c877ae00-ac92-11e9-9b1d-bcc9eb3be381.gif)

**Comment by nramamurth** [comment]
`onClick` navigation is broken as well. 

![chrome-capture](https://user-images.githubusercontent.com/10090859/61782171-39e66680-ae23-11e9-8b23-479643fff625.gif)

**Comment by nramamurth** [comment]
So, while investigating into the original issue I seem to be noticing another strange behavior with keyboard navigation and mouse navigation in the scenario below - 

1. Navigate to https://engineering.cerner.com/terra-framework/#/raw/tests/terra-menu/menu/menu/large-menu
2. Open the Menu. 
3. Click on "Default 5" menu item.
4. Press Down arrow key and make sure that the focus is now set to the first Group Item that is "Default 61".
5. Click on "Default 62" menu item and notice that the checkmark icon appears on "Default 62" but the focus flips back to "Default 61". This is evident in the evidences below. 

<details>
<summary>Evidence 1</summary>

![chrome-capture](https://user-images.githubusercontent.com/10090859/61785732-ec212c80-ae29-11e9-99bc-131ddf07961d.gif)

</details>

<details>
<summary>Evidence 2 (Focus/Active CSS changed)</summary>

![chrome-capture (2)](https://user-images.githubusercontent.com/10090859/61785774-078c3780-ae2a-11e9-91f6-c132af0bfb89.gif)

</details>

This issues is not really related to the original issue imo but is this a bug? This is seen on all major browsers. What could possibly be stealing the focus again?
