### ISSUE TITLE
Create date form field

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#808]
# Feature Request

## Description
The date field would be a new form field specifically for entering known dates like Date of Birth. Date of Birth is a common form field that has been requested by a few teams now.
It is frequently displayed as 3 form fields grouped together.

<img width="407" alt="Screen Shot 2019-07-22 at 4 47 55 PM" src="https://user-images.githubusercontent.com/633148/61818634-dce4b380-ae16-11e9-8525-7450ea0e12e2.png">

**Comment by bjankord** [comment]
# Tech Design - Terra Form Date
## Expected behavior
This component uses a value and onChange prop to drive its value. The value prop expects a ISO 8601 date format (`YYYY-MM-DD`). 

The value prop has some logic built into it to handle values that are not provided in the ISO 8601 date format (`YYYY-MM-DD`).

We'll try and parse out values that are invalid. If the `value` prop is given a value of `2001-34-02`, we'll set the year to 2001 and the day to 02, but we can't do anything with the month as `34` is not a valid month and the component doesn't have a way to display this type of value.

### Examples of value input/output:

|`value` prop input| onChange callback return values (value, isValidDate)| Comment |
|-|-|-|
|2000-01-02|2000-01-02, true| example of valid format |
|-01-|-01-, false| example of year and day are not valid format |
|2000--02|2000--02, false| example of month is not valid format |
|2001-34-02|2001--02, false| example of month is not valid format|
|2000-1-2|2000--, false| example of  month and day are not valid format |
|2000-02-1|2000-02-, false| example of  day is not valid format |

### Component validation
While the date component will try to prevent erroneous values from being entered like `2001-34-02`, it doesn't prevent invalid dates from being entered, such as `2001-02-31`. The component will check the value entered and provide a boolean argument in the onChange callback with whether or not the value prop is a valid date.

This can then be used with a library like react-final-form to handle displaying error messages.

The valid date check looks like this:
```
function isValidDate(day, month, year) {

  const formattedDay = Number(day);
  const formattedMonth = Number(month) - 1; // Account for 0-indexed month
  const formattedYear = Number(year);

  const d = new Date(formattedYear, formattedMonth, formattedDay);

  const yearMatches = d.getUTCFullYear() === formattedYear;
  const monthMatches = d.getUTCMonth() === formattedMonth;
  const dayMatches = d.getUTCDate() === formattedDay;

  return yearMatches && monthMatches && dayMatches;
}
```

## Code Sample
```jsx
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ''
    }

    this.handleDateChange = this.handleDateChange.bind(this);
  }

  handleDateChange(value, isValidDate) {
    this.setState({
      value: value
    })
    console.log(isValidDate);
  }

  render() {
    return (
      <Base locale="en">
        <DateSelect label="Date of Birth"  dateId="dateOfBirth" value={this.state.value} onChange={this.handleDateChange} />
        <p>Selected Date: {this.state.value}</p>
      </Base>
    );
  }
}
```

## Props
This component is intended to be a controlled component.

| Prop Name | Type | Is Required | Default Value | Description |
|-|-|-|-|-|
|label|string|required|none|The label of the form field. e.g `Date of Birth`|
|dateId|string|required|none|Unique HTML ID for the field. Used to populate unique mapping in the field.|
|isLabelHidden|bool|optional|false|Whether or not the label is visible. Use this prop to hide a label while still creating it on the DOM for accessibility.|
| value | string | optional | `''` | Sets the value of the date control. |
| onChange | function | optional | none | Callback function run when user changes the input value of the date field.  Returns value in `YYYY-MM-DD` format. Example, if only a month is entered, will return `-11-`. Similarly, if only a day is entered, will return `--02`. |
| displayFormat |string | optional | `month-day-year` | Sets the display format for the component. Can be one of 2 values: `month-day-year` or `day-month-year`. |
| disabled | bool | optional | false | Whether or not the field is disabled. |
| isInvalid | bool | optional | false | Whether or not the field is invalid. |
| required| bool | optional | false | Whether or not the field is required. |

## Responsiveness
No planned responsive behavior at this time.

## Internationalization
This component will support translations for the month names as well as the month, day, year placeholder values (`Month`, `DD`, `YYYY`).

This component also supports rendering the display of the component in `month-day-year` or `day-month-year` format depending on the needs of the app to support expected date entry in various locales.

## Accessibility
This component is intended to be built with our [terra-form-fieldset component](https://engineering.cerner.com/terra-ui/components/terra-form-fieldset/form-fieldset/form-fieldset) and [terra-form-input component](https://engineering.cerner.com/terra-ui/components/terra-form-input/form-input/input). It will also use a native select for the month drop down.* These components all use semantic HTML elements and should work with screen readers.

\* Using the native select allows us to pass onKey down handler to the select to clear the month field when the  user presses backspace and shift focus to the day field if the format is in `day-month-year` format. It also allows better keyboard experience on mobile devices when selecting a month.

The component will shift focus as the user has entered the required amount of data into each input. Pressing backspace will clear the input, pressing backspace one the input is cleared will cycle focus to the previous input in the date fieldset.

**Comment by benbcai** [comment]
Just wanted some clarification on the value returned in the onChange callback. Does the returned value indicate what was changed only in that input or does it also include current values in the other inputs? For example, if the month is changed to `08` and then the date is changed to `15`, is the value returned by the date change going to be `-0815` or just `--15`?

**Comment by bjankord** [comment]
Starting with an empty date control, if the month is set to `08` using the month select, the value returned is `-08-`. Then the day is set to 15, the first value returned in the onChange will be `-08-15`, the second value will be `false` which indicates that `-08-15` is not a valid date.
