### ISSUE TITLE
Using DateTimePicker in a Modal causes an infinite loop. 

### ISSUE THREAD

**Issue by adarrah** [cerner/terra-framework#817]
# Bug Report

## Description
I am trying to update my team's application to use the newly added seconds field on the DateTimePicker. One of our DateTimePickers is contained in a modal container, whenever one of the fields is focused it causes the application to freeze and requires the browser to kill the process. Once the process has been stopped the console is full of errors that state there has been too much recursion (see attached screenshot). 

## Steps to Reproduce
1. Open application
2. Open modal container
3. Select to focus either time or date field
4. Experience loops

## Additional Context / Screenshots
<img width="1680" alt="Screen Shot 2019-07-26 at 3 31 18 PM" src="https://user-images.githubusercontent.com/7127845/61980430-608bd500-afbc-11e9-9ff9-626b09824f10.png">

## Expected Behavior
I expect whenever the component is focused that it will quickly bring up the calendar view to allow for a date to be selected. 

## Environment

* Component Name and Version: Terra-date-time-picker, 4.7.0
* Browser Name and Version: Mozilla Firefox, 68.0.1
* Node/npm Version: 8.16.0/6.9.0
* Webpack Version: 4.19.0
* Operating System and version (desktop or mobile): OSX 10.14.5

**Comment by bjankord** [comment]
What modal package are you using and what version of that package are you using?

**Comment by adarrah** [comment]
Modal package and version: terra-modal-manager and terra-disclosure-manager, 4.1.0 and 3.2.0

**Comment by bjankord** [comment]
It looks like the current release of terra-modal-manager is: `6.7.1`
And the current release of terra-disclosure-manager is: `4.16.0`.

Can you try updating those packages and test with the latest terra-date-time-picker and see if the error persists.

**Comment by adarrah** [comment]
When I updated to the latest version of those two components it solves this issue
