### ISSUE TITLE
[terra-menu] screen readers move focus out of popup

### ISSUE THREAD

**Issue by mmalaker** [cerner/terra-framework#833]
# Bug Report

## Description
When using the desktop versions of Voice Over on Safari and JAWS on Chrome, it is possible to move focus out of a menu while the popup is still open. The screen reader this starts reading other parts of the main page. You can also reverse navigate from the page back to the popup.

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-ui/components/terra-menu/menu/menu
2. Navigate to the default menu Click Me button (or any of the examples).
3. Using the screen reader's navigation buttons (left/right arrow for VO, up/down for JAWS), navigate among the menu items.
4. Continue navigating up past the top menu item
5. The screen reader leaves the popup and starts reading the content on the main page.

Note that on VO, I've gotten the screen reader to leave focus both at the top and the bottom of the menu. Looks like JAWS only loses focus from the top.

## Expected Behavior
Screen readers should maintain focus within the menu popup until the user dismisses the popup.

**Comment by bjankord** [comment]
Look into using inert/aria-hidden. Will work for popups in app. 
With popups in a modal, we'd need to add inert/aria-hidden to the modal. 

Want to check and see if the user can interact with anything when the move out of the popup or if it is only read mode.

**Comment by pranav300** [comment]
I looked into it and was not able to recreate the issue.

**Comment by saket2403** [comment]
I used inert/ aria-hidden, looks like the fix works fine for Voice Over on Safari and JAWS on Chrome and IE .But when using Voice Over on Chrome the focus is moving out of popup.Is it a difference in behaviour of VO with safari and chrome?
@mmalaker and @bjankord  your thoughts?

**Comment by mmalaker** [comment]
Hello @saket2403, you don't have to worry about Voice Over on Chrome. The only browser/screen reader combinations that we officially support are VO on Safari and JAWS on Chrome.

**Comment by dkasper-was-taken** [comment]
We can close/backlog this issue. As the proper holistic solution to this involves the implementation of a stack management system to control inert with a combination of disclosures and popups.
