### ISSUE TITLE
[terra-infinite-list] Cannot read property 'scrollHeight' of null

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-framework#835]
# Bug Report
"Cannot read property 'scrollHeight' of null" 

## Description
When resizing there is a debounce timeout set in the InfiniteList, if it is umounted during the timeout the reference to "this" or "this.contentNode" will become null and the subsequent call for it's scrollHeight will cause an error.

## Steps to Reproduce
1. Resize browser
2. Either programmatically remove the infinite list or use the dev-stie to select another tab

## Possible Solution
Adding additional clearTImeout to the cleaup should fix it:
clearTimeout(this.timer);

https://github.com/cerner/terra-framework/blob/master/packages/terra-infinite-list/src/InfiniteList.jsx#L233

**Comment by ShettyAkarsh** [comment]
Closed #849
