### ISSUE TITLE
terra-abstract-modal throwing error in IE 10

### ISSUE THREAD

**Issue by harshadbarve** [cerner/terra-framework#901]
# Bug Report

## Description
I am using terra-modal-manager version 6.8.0 which uses terra-abstract-modal. In my scenario, I have modal 1 allowing the user to search for items and on selecting any one item, modal 2 pops up. When the modal 2 pops up, I am seeing the following error:

> Object doesn't support property or method 'focus'

## Steps to Reproduce

1. Open Modal 1 
2. Trigger opening of Modal 2 on top of it.
3. Notice the error

## Additional Context / Screenshots
Link: https://github.com/cerner/terra-framework/blob/f788aec29cefd2570a84bd400168a7f830f9c4ae/packages/terra-abstract-modal/src/AbstractModal.jsx#L159

https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1568980377888?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1568980377888&teamName=Terra&channelName=Component%20Support&createdTime=1568980377888

<img width="705" alt="modalTriggerAsObject" src="https://user-images.githubusercontent.com/31926118/65593575-64cd7200-dfae-11e9-9865-c7ee029f2f22.png">

## Expected Behavior
Error should not be seen.

## Possible Solution
No

## Environment

* Component Name and Version: terra-modal-manager 6.8.0
* Browser Name and Version: IE 10
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Desktop, Windows

## @ Mentions
@nramamurth @ShettyAkarsh

**Comment by nramamurth** [comment]
I was able to reproduce this when the modal is disclosed via a non-HTML element (SVG for example). In the test case below, `modalTrigger` is the SVG element (that does not support `focus()`) on IE but it is the `body` element on other major browsers. 

<details> <summary> Reduced Test Case </summary>

```
import React from 'react';
import PropTypes from 'prop-types';
import ContentContainer from 'terra-content-container';
import { withDisclosureManager, disclosureManagerShape } from 'terra-disclosure-manager';
import ModalManager from 'terra-modal-manager';

class DisclosureComponent extends React.Component {
  constructor(props) {
    super(props);

    this.disclose = this.disclose.bind(this);
    this.closeDisclosure = this.closeDisclosure.bind(this);
  }

  disclose(size, dimensions) {
    const { disclosureType, nestedIndex } = this.props;

    const newIndex = nestedIndex + 1;
    return () => {
      this.props.disclosureManager.disclose({
        preferredType: disclosureType,
        size,
        dimensions,
        content: {
          key: `DemoContainer-${newIndex}`,
          component: <WrappedDisclosureComponent identifier={`DemoContainer-${newIndex}`} nestedIndex={newIndex} />,
        },
      });
    };
  }

  closeDisclosure() {
    this.props.disclosureManager.closeDisclosure();
  }

  render() {
    const { disclosureManager, identifier } = this.props;

    return (
      <ContentContainer id={identifier} className="nested-component" fill header={<h2>IE Focus Issue</h2>}>
        <br />
        <div>
          <svg width="75" height="25">
            <g>
              <rect x="0" y="0" width="100%" height="100%" fill="#da552f" />
              <text x="10" y="17" onClick={this.disclose()}>Disclose</text>
            </g>
          </svg>
        </div>
        {disclosureManager && disclosureManager.closeDisclosure ? <button type="button" className="close-disclosure" onClick={this.closeDisclosure}>Close Disclosure</button> : null}
      </ContentContainer>
    );
  }
}

DisclosureComponent.propTypes = {
  disclosureManager: disclosureManagerShape,
  identifier: PropTypes.string,
  disclosureType: PropTypes.string,
  nestedIndex: PropTypes.number,
};

DisclosureComponent.defaultProps = {
  nestedIndex: 0,
};

const WrappedDisclosureComponent = withDisclosureManager(DisclosureComponent);

const ModalManagerDefault = () => (
  <div role="main">
    <ModalManager>
      <WrappedDisclosureComponent identifier="root-component" disclosureType="modal" />
    </ModalManager>
  </div>
);

export default ModalManagerDefault;

```
</details>

<details> <summary> Behavior on IE 10 </summary>

![ie-focus-issue](https://user-images.githubusercontent.com/10090859/65679140-2a2d0d80-e072-11e9-89a5-64a4a31e4288.gif)
</details>

<details> <summary> Behavior on Chrome </summary> 

![chrome-focus-issue](https://user-images.githubusercontent.com/10090859/65679154-31ecb200-e072-11e9-97d8-1242cef792f7.gif)
</details>

---

**Solution?** 

Check whether `focus` method is defined on `modalTrigger` before invoking it. This is apparently [more evident when iFrame is involved](https://github.com/davidtheclark/focus-trap-react/pull/19) (like in Powerchart).

**Comment by nramamurth** [comment]
@ryanthemanuel @bjankord @tbiethman 

So, @ShettyAkarsh had an interesting follow-up question to the behavior here. 

When a modal is disclosed by clicking on a SVG element, since IE considers the SVG element as the `modalTrigger` while the other major browsers consider the HTML body element as the `modalTrigger`, the focus goes back to the `body` element on Chrome, Safari, etc. while focus does not get restored on IE on any element with the fix that went in. In such a scenario, do we not have to ensure that our functionality works the same across all browsers? 

Personally, I don't think we need to do that because I think we can never be sure how the default browser implementation for each browser may further change in the future. 

However, if we need to maintain the same behavior across all browsers as of today, then I think that we may have to explicitly set the focus back to the 'body' element - 

```diff
if (this.state.modalTrigger && this.state.modalTrigger.focus) {
   // Shift focus back to element that was last focused prior to opening the modal
   this.state.modalTrigger.focus();
- }
+ } else {
+  document.getElementsByTagName('body')[0].focus();
}

```

I'd like to know your thoughts on whether this needs to be further 'fixed'.

**Comment by bjankord** [comment]
I'm happy with the behavior that has been implemented in https://github.com/cerner/terra-framework/pull/904 but I can also see value in adding the else block noted in your comment @nramamurth
