### ISSUE TITLE
[terra-popup] Code not shown for few examples in devSite.

### ISSUE THREAD

**Issue by lokesh-0813** [cerner/terra-framework#925]
## Description
In DevSite, example code is not shown for terra-popup in few examples.

## Steps to Reproduce
Navigate to https://engineering.cerner.com/terra-ui/components/terra-popup/popup/popup.
Implementation code is not shown for few examples.

## Expected Behavior
Implementation code should be shown.

**Comment by pranav300** [comment]
I and @ShettyAkarsh had a conversation on converting all the examples in the popup to `hooks`, display code for all examples and remove the common example file.
