### ISSUE TITLE
[terra-aggregator] Ensure the focus is released forcefully, when the corresponding item is removed from view

### ISSUE THREAD

**Issue by VivekChittamuri** [cerner/terra-framework#931]
# Bug Report

## Description
When a component with auto/manual refresh capability uses a terra-aggregator, the disclosed component continues to remain in view even after the item that invoked it is removed from the parent component. And when a second refresh happens on the parent component (with or without the item in focus) the disclosed component is removed as an unintended effect

## Steps to Reproduce
1.  Load a component with Aggregator having a bunch of items that have disclosure capabilities
2. Click on an element within one of those items say (item A) and allow the disclosure component to open
3. On a timeout or probably a button action update the aggregator with a new set of items (without item A)
4. The expectation is to see the disclosed component close out. However it would continue to persist
5. Now if the component reloads with initial data set. The disclosed component will close on you.

## Expected Behavior
Focus should release as expected when item is dynamically removed based on user activity or a refresh interval from aggregator

## Possible Solution
The reasoning for this behavior is because of this line [Aggregator.jsx#L54](https://github.com/cerner/terra-framework/blob/master/packages/terra-aggregator/src/Aggregator.jsx#L54). When checking if focused item is present in the view or not, the check should be made on the incoming props.However, it is being made on prevProps resulting in this behavior

## @ Mentions
@tbiethman

**Comment by ShettyAkarsh** [comment]
@VivekChittamuri, is this the issue which you are seeing ?
![Aggregator-issue](https://user-images.githubusercontent.com/45097016/67068063-672e8080-f196-11e9-8c28-389abde346fc.gif)

**Comment by VivekChittamuri** [comment]
@ShettyAkarsh  Yes, that is the behavior am seeing. If we change the line I tagged to `this.props.items.forEach` instead of `items.forEach` the code would work as expected. I was able to validate it locally on my node_modules.
