### ISSUE TITLE
Date Picker throws console log errors when min/max dates are set

### ISSUE THREAD

**Issue by pc592** [cerner/terra-framework#935]
# Bug Report

## Description
When creating a time range using two date pickers (**from** and **to**), and setting min/max dates to enforce date constraints, selecting dates in the **to** date picker results in console log errors that something (the year dropdown reference) is undefined.

## Steps to Reproduce
1. Make two date pickers, a **from** and a **to**.
2. For the **from** date picker, set the minDate to null and the maxDate to the **to** date picker's value (or today if not yet set).
3. For the **to** date picker, set the minDate to the **from** date picker's value (or null if not yet set) and the maxDate to today.
4. Select a date on the **from** picker and a date on the **to** picker.
5. Look at console logs.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/22568286/67104609-db642680-f18c-11e9-8c02-15e448d99135.png)
![Screen Recording 2019-10-18 at 10 04 32 2](https://user-images.githubusercontent.com/22568286/67107577-55e37500-f192-11e9-86e5-d19f558f0dd3.gif)

## Console log
```
Uncaught TypeError: Cannot read property 'contains' of undefined    at isEventTargetContainedWithinCalendarControl (calendar.js?14c6:88)
    at eval (calendar.js?14c6:93)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:362)
```

## Expected Behavior
No console logs.

## Possible Solution
Looking at developer tools, the issue comes from calendar.jsx:
![image](https://user-images.githubusercontent.com/22568286/67104708-0c445b80-f18d-11e9-9eb7-13be484e825c.png)
specifically:
```_this.yearDropdownRef``` is undefined.
[It looks like this is set to undefined here](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L504-L506) and so throws [here, which is where the source/developer tools showed us it was being thrown at](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L285).
So the fix is that it probably needs some guard statements in place, e.g.:
... this.yearDropdownRef && this.yearDropdownRef.contains(target)

## Environment

* Component Name and Version: Date Picker, 4.15.0
* Browser Name and Version: Chrome, 77.0.3865.90
* Node/npm Version: Node ,10.16.0/npm, 6.9.0
* Webpack Version: 4.35.2
* Operating System and version (desktop or mobile): MacOS|mojave, 10.14.6, desktop

## @ Mentions
I'm not sure if he's terra, but @dev-cprice helped me find where the issue was coming from!

**Comment by bjankord** [comment]
I'm working on resolving this in https://github.com/cerner/terra-framework/pull/932

**Comment by nramamurth** [comment]
@benbcai Do we know if #932 resolves this issue as well?

**Comment by benbcai** [comment]
@nramamurth Yes, this [change](https://github.com/cerner/terra-framework/commit/8afff4dcdcc9b0a98cdd038055eacc2108377d20) on #932 fixes this issue. I'll close this.
