### ISSUE TITLE
[Spike] [terra-menu] - Investigate Allowing Submenu Resizing

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-framework#952]
# Feature Request

Investigate allowing the terra-menu to resize for submenu navigation.

## Description

When the menu opens the initial height of the menu establishes the static height the menu will be for the lifetime of that popup.

Teams are starting to uncover workflows where the initial main menu height is relatively small and the submenu height is much larger. We should spike on the feasibility/usability of allowing menus to resize. 

## @ Mentions

@jmsv6d @neilpfeiffer

**Comment by lokesh-0813** [comment]
@StephenEsser  Are we looking at exposing a prop to set the height of the menu? Or we could reset the menu height based on subMenu items(My initial opinion and still need to dig more). Any thoughts on this?

**Comment by StephenEsser** [comment]
@lokesh-0813 

When logging this issue originally I was thinking something similar to a prop that sets an auto  dynamic height of the menu as necessary. Similar to the terra-popop auto height API.

This request came through from a UX designer and a few other teams. We should get more confirmation about the expected functionality. 

cc: @neilpfeiffer

**Comment by jmsv6d** [comment]
Currently the menu will auto size the height based on the height of the main menu, but maintains that height for submenus. There is code in the menu right now that forces this to happen. If the submenu is smaller than the main menu, this is fine, but there are some scenarios where the submenu is longer than the main menu and the user may end up with a small popup with a scrollbar. I was thinking we have a couple of options (or some combination of these options)
1) Bool prop that allows for dynamic sizing of submenus. The downside to this approach is that resizing of menu could cause the popup to need to be repositioned, causing a jarring user experience.
2) Open up the prop with all the popup menu sizing options. Then consumers could pick the set height for the menu, users wouldn't have the potentially jarring experience of the popup resizing during menu navigation and they could choose a size that would be more appropriate for all the menu's "pages".
But I think we need input from @neilpfeiffer on what approach we want to take and if we want to make a change at all.

**Comment by neilpfeiffer** [comment]
Should also pair with a fix missing headers and text wrapping/flexing header height:
https://github.com/cerner/terra-framework/issues/474

Changes needed were discussed during the UX Audit:
https://github.com/cerner/terra-framework/issues/1297
