### ISSUE TITLE
[Infinite List] Stuck Initial Loading Indicator when the request data changes before loading completely

### ISSUE THREAD

**Issue by prasadkhedekar** [cerner/terra-framework#953]
# Bug Report

## Description

I have a component that accepts a request data object as a prop and then renders the Infinite List. I have defined the "onRequestItems" callback which manipulates the request data object received as prop and makes an async request. The problem occurs when I'm loading a set of data, and the request data object prop to my component is changed in the midst of loading, i.e. my async request is still pending, I'm stuck with the loading indicator and the infinite list does not even invoke the "onRequestItems" callback. Ideally, since my props changed the infinite list should invoke the "onRequestItems" to load the new set of data.

## Steps to Reproduce

1. Create component that accepts request data as a prop and renders Infinite List.
2. Change the request data prop to the component while the initial loading indicator still appears/request not complete.
3. Stuck loading indicator with no call to the "onRequestItems"

## Expected Behavior

Ideally, since my props changed the infinite list should re-render and invoke the "onRequestItems" to load the new set of data.

## Possible Solution

I found a workaround wherein I added a key prop to the infinite list which is tied to my incoming request data object prop to ensure uniqueness and make sure React identifies it uniquely and renders with the new data. But I'm curious if the Infinite List could handle this internally.

## Environment

* Component Name and Version: Infinite List ^3.0.0
* Browser Name and Version: Chrome Version 77.0.3865.120
* Node/npm Version: 5.5.1
* Webpack Version:
* Operating System and version (desktop or mobile): Desktop and Mobile

## @ Mentions

Discussed this issue with @tbiethman

**Comment by nramamurth** [comment]
@prasadkhedekar 

Do you have a reduced test case that illustrates this behavior? Does the code below get closer to what you have? 

<details>
 <summary>ProgressiveLoadingInfiniteList</summary>

```
import React from 'react';
import InfiniteList, { Item } from 'terra-infinite-list/lib/index';

const mockData = (pageKey) => {
  let isFinalPage = false;
  const nextPageKey = (pageKey >= 0 ? pageKey : 0) + 1;
  if (nextPageKey > 3) {
    isFinalPage = true; // If the prefix of the data item is > 3, then this is the final page.
  }

  const items = [];
  for (let i = 0; i < 2; i += 1) {
    items.push(
      {
        title: `Item ${pageKey * 10 + i}`,
        key: `unique-${pageKey * 10 + i}`,
      },
    );
  }

  return {
    nextPageKey,
    items,
    isFinalPage,
  };
};

const mockRequest = pageKey => new Promise(resolve => setTimeout(() => { resolve(mockData(pageKey)); }, 3000));

const MyInitialLoadingIndicator = () => (
  <div style={{ border: '1px dashed', padding: '3px' }}> Initial Loading Indicator </div>
);

const MyProgressiveLoadingIndicator = () => (
  <div style={{ border: '1px dashed', padding: '3px' }}> Progressive Loading Indicator </div>
);

// eslint-disable-next-line react/prop-types
const MyExampleContainer = ({ children }) => (
  <div>
    {children}
  </div>
);

class ProgressiveLoadingList extends React.Component {
  constructor(props) {
    super(props);
    this.requestData = this.requestData.bind(this);
    this.state = {
      isFinishedLoading: false, items: [],
    };
  }

  requestData() {
    // eslint-disable-next-line react/prop-types
    mockRequest(this.props.currentPageKey).then(response => (
      this.setState(prevState => ({
        isFinishedLoading: response.isFinalPage,
        items: prevState.items.concat(response.items),
      }))
    ));
  }

  createItems() {
    return this.state.items.map(item => (
      <Item key={item.key}>
        <div style={{ border: '1px dashed', padding: '3px' }}> {item.title} </div>
      </Item>
    ));
  }

  render() {
    return (
      <MyExampleContainer>
        <InfiniteList
          dividerStyle="standard"
          isFinishedLoading={this.state.isFinishedLoading}
          onRequestItems={this.requestData}
          initialLoadingIndicator={<MyInitialLoadingIndicator />}
          progressiveLoadingIndicator={<MyProgressiveLoadingIndicator />}
        >
          {this.createItems()}
        </InfiniteList>
      </MyExampleContainer>
    );
  }
}
export default ProgressiveLoadingList;

```
</details>

<details>
<summary> ProgressiveLoadingListBase </summary>

```
import React from 'react';
import ProgressiveLoadingList from './ProgressiveLoadingList';

class ProgressiveLoadingListBase extends React.Component {
  constructor(props) {
    super(props);
    this.updateKey = this.updateKey.bind(this);
    this.state = { currentPageKey: 1 };
  }

  updateKey() {
    this.setState(() => ({
      currentPageKey: Math.floor((Math.random() * 9) + 1),
    }));
  }

  render() {
    return (
      <div>
        <button type="button" onClick={this.updateKey}>
          Refresh
        </button>
        <h2>
          Data Item starts with No.
          {this.state.currentPageKey}
        </h2>
        <ProgressiveLoadingList currentPageKey={this.state.currentPageKey} />
      </div>
    );
  }
}
export default ProgressiveLoadingListBase;
```
</details>

> I found a workaround wherein I added a key prop to the infinite list which is tied to my incoming request data object prop to ensure uniqueness. 

I wanted to know if the behavior below is similar to what you're seeing for me to troubleshoot further. If not, then I'd appreciate it if a reduced test case is provided.

**Note:** I wait 10 secs for my async request to finish and I assume that the list has _finished loading_ if the data item starts with a number > 3.


**without unique key:** 

![select-special-logic`](https://user-images.githubusercontent.com/10090859/67763665-3be94280-fa6e-11e9-81ee-8528e01df149.gif)

**with unique key:**

![select-special-logic2](https://user-images.githubusercontent.com/10090859/67763687-460b4100-fa6e-11e9-91b5-7251da26f8c0.gif)

**Comment by mjhenkes** [comment]
Your possible solution is our expected solution for this problem. We've added an issue to document this for terra-infinite- list
https://github.com/cerner/terra-framework/issues/956
