### ISSUE TITLE
[terra-application-navigation] Add callback to provide the state of the Drawer menu to consumers

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-framework#960]
# Feature Request

## Description
There is a request from a consumer to know what state the navigation drawer menu is in. We should add a callback function that reports the state of the navigation drawer as it is either changed or reset.

The prop should be named:
OnDrawerMenuStateChange

**Comment by lokesh-0813** [comment]
@mjhenkes I need some clarification here. When you say `state of the navigation drawer menu` are we looking at close/open(boolean) or additional data ?

If its a boolean that is returned by`OnDrawerMenuStateChange`, should we expose some logic to the user to do something with this value(Like closing the menu or may be something else) ?

**Comment by mjhenkes** [comment]
@lokesh-0813 The callback should fire when this state changes and contain the updated state:
https://github.com/cerner/terra-framework/blob/master/packages/terra-application-navigation/src/ApplicationNavigation.jsx#L138

No we should not expose any logic for the user to open or close the menu, That would be a controlled component.
