### ISSUE TITLE
[terra-tabs] Overflow in icon-only collapsible tabs. 

### ISSUE THREAD

**Issue by nramamurth** [cerner/terra-framework#970]
# Bug Report

## Description
This issue occurs _only_ when all tabs are icon-only. In a scenario when some tabs need to be collapsed into a menu due to unavailability of space, container supposedly appears to overflow — few tabs that needed to be _actually_ hidden are visible pushing the "More" button to the right and causing an overflow. 

## Steps to Reproduce
1. Display, let's say, 50 icon-only tabs.

## Additional Context / Screenshots
![icon-only](https://user-images.githubusercontent.com/10090859/68773425-8adbce00-0651-11ea-88e5-79ac246a65cb.gif)

## Repro

```
import React from 'react';
import IconSearch from 'terra-icon/lib/icon/IconSearch';
import Tabs from 'terra-tabs';

const createTabPanes = () => {
  const tabPanes = [];
  for (let i = 0; i < 50; i += 1) {
    const tabPane = (
      <Tabs.Pane label={`Search${i}`} icon={<IconSearch />} isIconOnly key={`Search${i}`} id={`search${i}`} />
    );

    tabPanes.push(tabPane);
  }
  return tabPanes;
};

const IconOnlyTabs = () => (
  <Tabs id="icononlytabs" responsiveTo="none">
    {createTabPanes()}
  </Tabs>
);

export default IconOnlyTabs;

```
## Expected Behavior
Horizontal scroll should not appear, 'More' button should not look cut off. 

## Possible Solution
The minimum width set to icon-only tab affects the [logic that we have to calculate the `hideStateIndex`](https://github.com/cerner/terra-framework/blob/6cf7f8722f57836915c06589297b30efd09fb1df/packages/terra-tabs/src/_CollapsibleTabs.jsx#L109-L130) that decides how many tabs to show and how many to collapse into the menu. **Increasing the min-width fixes this issue**. 

https://github.com/cerner/terra-framework/blob/6cf7f8722f57836915c06589297b30efd09fb1df/packages/terra-tabs/src/Tabs.module.scss#L58-L62

## Environment

* Component Name and Version: terra-tabs v6.18.0
* Browser Name and Version: All browsers.

## @ Mentions
@neilpfeiffer

**Comment by nramamurth** [comment]
@neilpfeiffer, thoughts?

**Comment by neilpfeiffer** [comment]
Not fully understanding why min-width fixes the dynamic `handleResize` calculation, but would interested to see the change applied in PR and evaluate.

**Comment by nramamurth** [comment]
@neilpfeiffer 

Draft PR - https://github.com/cerner/terra-framework/pull/984
Deployment - [WIP]

**Comment by jeremyfuksa** [comment]
> Not fully understanding why min-width fixes the dynamic `handleResize` calculation, but would interested to see the change applied in PR shown with a new test case and evaluate.

I don't understand how it affects that either. But it seems to work.
