### ISSUE TITLE
[Terra-date-picker] Update date selection keyboard focus styling

### ISSUE THREAD

**Issue by gustavofulton** [cerner/terra-framework#988]
# Bug Report

## Description

When a date is selected in the first few days of the month, when you navigate to the previous month, it highlights both the selected one and the same in the previous month. This happens in both `Terra-date-picker` and `Terra-date-time-picker`

## Steps to Reproduce

1. Default datepicker value to a day between 1-5 of the month.
2. Open datepicker
3. Navigate to previous month
4. Vouila

## Additional Context / Screenshots

![duplicate-date](https://user-images.githubusercontent.com/10981250/70833360-2e3d1180-1dbd-11ea-94b8-521465a6fef5.gif)

## Expected Behavior

Only show one date at a time. Either the previous month or the current selected one.

## Possible Solution

Only show one date at a time. Either the previous month or the current selected one.

## Environment

* Component Name and Version: Terra-date-time-picker 4.23.0
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5] Node 10.16.2, npm 6.9
* Webpack Version: 
* Operating System and version (desktop or mobile): Mac

**Comment by neilpfeiffer** [comment]
Confirmed bug, examples to replicate:

### Date-Time-Picker:
Change value to `value="2019-12-01T01:00:00"`, run test and navigate forward and back months:
https://github.com/cerner/terra-framework/blob/e1f6de9934b6e08b957c411eaf43da0e00dc15ce/packages/terra-date-time-picker/src/terra-dev-site/test/date-time-picker/DateTimePickerDefaultDateTime.test.jsx#L4-L8

### Date-Picker:
No change needed - run test and navigate forward and back months:
https://github.com/cerner/terra-framework/blob/e1f6de9934b6e08b957c411eaf43da0e00dc15ce/packages/terra-date-picker/src/terra-dev-site/test/date-picker/DatePickerStartDate.test.jsx#L8-L14

**Comment by neilpfeiffer** [comment]
Correcting previously misunderstood issue - date picker is not currently selecting two dates simultaneously, but has a keyboard focus-style that mimics the selection style, so is confusing to the user. Behavior/Code is actually performing mostly as intended, visual styling needs to be updated with some minor keyboard focus behavior updates to make it inline with user expectations.

Renaming to "Update date selection keyboard focus styling" to be more accurate.
